### ISSUE TITLE
`launchApp` commands doesn't work the with env parameters (1.26.0)

### ISSUE THREAD

**Issue by retyui** [mobile-dev-inc/maestro#1004]
command:
```sh
$HOME/.maestro/bin/maestro test file.yaml -e SKIP_AUTH=true
```

yaml:
```yaml
- launchApp:
    clearState: ${SKIP_AUTH !== 'true'}
    clearKeychain: ${SKIP_AUTH !== 'true'}
    stopApp: true
```

error: 
```java
java.lang.IllegalArgumentException: Cannot deserialize value of type `java.lang.Boolean` from String "${SKIP_AUTH !== 'true'}": only "true" or "false" recognized
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: java.util.ArrayList[0]->maestro.orchestra.yaml.YamlFluentCommand["launchApp"]->maestro.orchestra.yaml.YamlLaunchApp["clearState"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4393)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4334)
	at maestro.orchestra.yaml.YamlCommandReader.readConfigAndCommands(YamlCommandReader.kt:106)
```

more: https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1681987726369719

**Comment by felipevolpone** [comment]
@retyui Thanks for reporting. This indeed seems a bug

**Comment by soutua** [comment]
The environment variable support would be nice to get fixed. Our use case is that our app has multiple different appId's depending which build it is, so we cannot hard code the appId in the test files, but have instead defined the appId with environment variables like so: `appId: ${APP_ID}`, and then we launch the tests e.g. like this: `APP_ID=com.our.app.debug maestro test`. This used to work with older Maestro versions but I guess it broke in the 1.26 version as stated in this issue (not exactly sure which version it was). This in practice prevents us from running the tests in the CI since the builds there are using different appId than the debug builds.

**Comment by soutua** [comment]
Coming back to this, just now realised there this documentation: https://maestro.mobile.dev/advanced/parameters-and-constants#accessing-variables-from-the-shell
That all the environment variables coming from outside, need to be prefixed with `MAESTRO_`, the change happened in this PR: https://github.com/mobile-dev-inc/maestro/pull/894, so in practice was released in the version 1.26. So this is actually not broken, but just need to use the `MAESTRO_` prefix in the environment variables (although the change was kind-of a breaking change as far as using Maestro goes).

**Comment by Fishbowler** [comment]
Looking at this for the first time.

There's a bunch of fields for a bunch of commands that take JS interpolated values. Alas, this doesn't include most file paths or booleans.

Yet.
