### ISSUE TITLE
Caused by: java.io.IOException: Command failed (host:transport:emulator-5554): device offline

### ISSUE THREAD

**Issue by JeasonWong** [mobile-dev-inc/maestro#1022]
![image](https://user-images.githubusercontent.com/8034315/234806555-cc568d02-c270-4c3c-ab8e-9e92274010ca.png)

Exception in thread "Thread-1" java.io.IOException: pm list packages --user 0 dev.mobile.maestro.test
	at maestro.drivers.AndroidDriver.shell(AndroidDriver.kt:773)
	at maestro.drivers.AndroidDriver.isPackageInstalled(AndroidDriver.kt:761)
	at maestro.drivers.AndroidDriver.uninstallMaestroApks(AndroidDriver.kt:736)
	at maestro.drivers.AndroidDriver.close(AndroidDriver.kt:148)
	at maestro.Maestro.close(Maestro.kt:431)
	at maestro.cli.session.MaestroSessionManager$MaestroSession.close(MaestroSessionManager.kt:347)
	at maestro.cli.session.MaestroSessionManager$newSession$1$1.invoke(MaestroSessionManager.kt:93)
	at maestro.cli.session.MaestroSessionManager$newSession$1$1.invoke(MaestroSessionManager.kt:88)
	at maestro.cli.db.KeyValueStore.withExclusiveLock(KeyValueStore.kt:37)
	at maestro.cli.session.SessionStore.withExclusiveLock(SessionStore.kt:74)
	at maestro.cli.session.MaestroSessionManager$newSession$1.invoke(MaestroSessionManager.kt:88)
	at maestro.cli.session.MaestroSessionManager$newSession$1.invoke(MaestroSessionManager.kt:87)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: java.io.IOException: Command failed (host:transport:emulator-5554): device offline
	at dadb.adbserver.AdbServer.send$dadb(AdbServer.kt:99)
	at dadb.adbserver.AdbServerDadb.open(AdbServer.kt:137)
	at dadb.Dadb$DefaultImpls.openShell(Dadb.kt:43)
	at dadb.adbserver.AdbServerDadb.openShell(AdbServer.kt:118)
	at dadb.Dadb$DefaultImpls.shell(Dadb.kt:36)
	at dadb.adbserver.AdbServerDadb.shell(AdbServer.kt:118)
	at maestro.drivers.AndroidDriver.shell(AndroidDriver.kt:771)
	... 12 more

**Comment by JeasonWong** [comment]
kill the App process is OK, but it's strange...
