### ISSUE TITLE
[v1.28.0] Maestro is crashing during tests io.grpc.StatusRuntimeException: UNKNOWN            

### ISSUE THREAD

**Issue by mjaworski-bsg** [mobile-dev-inc/Maestro#1112]
**Describe the bug**
A few of our tests are crashing randomly (around 1 out of 10 tries ends up with the crash).

It happens on TV emulator (API 33), we are testing our player activity (it has some player controls and ExoPlayer is playing a video)

io.grpc.StatusRuntimeException: UNKNOWN                           
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
        at maestro_android.MaestroDriverGrpc$MaestroDriverBlockingStub.viewHierarchy(MaestroDriverGrpc.java:588)
        at maestro.drivers.AndroidDriver.contentDescriptor(AndroidDriver.kt:263)
        at maestro.ViewHierarchy$Companion.from-c1iYVAs(ViewHierarchy.kt:29)
        at maestro.Maestro.viewHierarchy-prqvCes(Maestro.kt:381)  
        at maestro.orchestra.Orchestra.findElement(Orchestra.kt:745)
        at maestro.orchestra.Orchestra.access$findElement(Orchestra.kt:46)
        at maestro.orchestra.Orchestra$evaluateCondition$3$result$1.invoke(Orchestra.kt:465)
        at maestro.orchestra.Orchestra$evaluateCondition$3$result$1.invoke(Orchestra.kt:463)
        at maestro.utils.MaestroTimer.withTimeout(MaestroTimer.kt:16)
        at maestro.orchestra.Orchestra.evaluateCondition(Orchestra.kt:463)
        at maestro.orchestra.Orchestra.assertConditionCommand(Orchestra.kt:246)
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:191)
        at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:525)
        at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:434)
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:202)
        at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:150)
        at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:93)
        at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:179)
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:45)
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:42)
        at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:138)
        at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:42)
        at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:166)
        at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:126)
        at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:99)
        at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:57)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:126)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:44)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at maestro.cli.AppKt.main(App.kt:136)

**Flow**
Part of the flow file, "Assert that id: .*player_loading is not visible" is passing, however the next step does not.

- extendedWaitUntil:
        notVisible:
              id: .*player_loading
        timeout: 20000
- extendedWaitUntil:
        notVisible:
              id: .*player_play_pause  # wait until controls are gone
        timeout: 20000
- tapOn: # now bring them back up again
      id: .*player_frame
- assertVisible:
      id: .*player_play_pause

**Bugreport output (if applicable)**
[2023-05-29_121049.zip](https://github.com/mobile-dev-inc/maestro/files/11590840/2023-05-29_121049.zip)

**Comment by felipevolpone** [comment]
@mjaworski-bsg Is your app native?

**Comment by mjaworski-bsg** [comment]
@felipevolpone yes, this is a native Android app

**Comment by felipevolpone** [comment]
@mjaworski-bsg Would you send the app binary to me so we can debug it? I'm Felipe in our public Slack (get the link here https://mobile.dev)

**Comment by Fishbowler** [comment]
Given this one went quiet, I'm gonna assume it's fixed or otherwise a dead issue.
