### ISSUE TITLE
[v1.28.0] [FlyingFox] <::1> error: SocketError. Read(54): Connection reset by peer

### ISSUE THREAD

**Issue by wangfenjin** [mobile-dev-inc/maestro#1115]
**Describe the bug**

I'm experiment to use maestro to test TikTok app, the video will hang there without any response and the testing flow failed with error. I change the appid to tiktok in the log

maestro log
```log
[INFO ] MAESTRO - ---- System Info ----
[INFO ] MAESTRO - Maestro Version: 1.28.0
[INFO ] MAESTRO - OS Name: Mac OS X
[INFO ] MAESTRO - OS Version: 13.3.1
[INFO ] MAESTRO - Architecture: x86_64
[INFO ] MAESTRO - ---------------------
[INFO ] maestro.LocalIdbRunner - startIDBCompanion on 032BD811-4ACB-49D3-A5EB-101D6605CB46
[WARN ] maestro.LocalIdbRunner - Waiting for idb service to start..
[WARN ] maestro.LocalIdbRunner - Waiting for Simulator to boot..
[WARN ] maestro.LocalIdbRunner - Waiting for successful taps
[WARN ] maestro.LocalIdbRunner - Simulator ready
[INFO ] xcuitest.XCTestDriverClient - [Start] Uninstalling xctest ui runner app
[INFO ] x.installer.LocalXCTestInstaller - [Start] Uninstall XCUITest runner
[INFO ] util.CommandLineUtils - Running command line operation: [xcrun, simctl, uninstall, 032BD811-4ACB-49D3-A5EB-101D6605CB46, dev.mobile.maestro-driver-iosUITests.xctrunner]
[INFO ] x.installer.LocalXCTestInstaller - [Done] Uninstall XCUITest runner
[INFO ] xcuitest.XCTestDriverClient - [Done] Uninstalling xctest ui runner app
[INFO ] x.installer.LocalXCTestInstaller - [Start] Install XCUITest runner on 032BD811-4ACB-49D3-A5EB-101D6605CB46
[INFO ] x.installer.LocalXCTestInstaller - Not able to find ui test runner app, going to install now
[INFO ] x.installer.LocalXCTestInstaller - [Start] Writing xctest run file
[INFO ] x.installer.LocalXCTestInstaller - [Done] Writing xctest run file
[INFO ] x.installer.LocalXCTestInstaller - [Start] Writing maestro-driver-iosUITests-Runner app
[INFO ] x.installer.LocalXCTestInstaller - [Done] Writing maestro-driver-iosUITests-Runner app
[INFO ] x.installer.LocalXCTestInstaller - [Start] Writing maestro-driver-ios app
[INFO ] x.installer.LocalXCTestInstaller - [Done] Writing maestro-driver-ios app
[INFO ] x.installer.LocalXCTestInstaller - [Start] Running XcUITest with xcode build command
[INFO ] util.CommandLineUtils - Running command line operation: [xcodebuild, test-without-building, -xctestrun, /var/folders/rf/d2cc2hj112n9vkm3g0l7t3s00000gn/T/maestro-driver-ios-config.xctestrun, -destination, id=032BD811-4ACB-49D3-A5EB-101D6605CB46]
[INFO ] x.installer.LocalXCTestInstaller - [Done] Running XcUITest with xcode build command
[INFO ] x.installer.LocalXCTestInstaller - [Done] Install XCUITest runner on 032BD811-4ACB-49D3-A5EB-101D6605CB46
[INFO ] x.installer.LocalXCTestInstaller - [Start] Ensure XCUITest runner is running on 032BD811-4ACB-49D3-A5EB-101D6605CB46
[INFO ] x.installer.LocalXCTestInstaller - [Done] Ensure XCUITest runner is running on 032BD811-4ACB-49D3-A5EB-101D6605CB46
[INFO ] m.cli.runner.MaestroCommandRunner - Apply configuration RUNNING
[INFO ] m.cli.runner.MaestroCommandRunner - Apply configuration metadata CommandMetadata(numberOfRuns=null, evaluatedCommand=MaestroCommand(tapOnElement=null, tapOnPoint=null, tapOnPointV2Command=null, scrollCommand=null, swipeCommand=null, backPressCommand=null, assertCommand=null, assertConditionCommand=null, inputTextCommand=null, inputRandomTextCommand=null, launchAppCommand=null, applyConfigurationCommand=ApplyConfigurationCommand(config=MaestroConfig(appId=tiktok, name=null, tags=[], initFlow=null, ext={})), openLinkCommand=null, pressKeyCommand=null, eraseTextCommand=null, hideKeyboardCommand=null, takeScreenshotCommand=null, stopAppCommand=null, clearStateCommand=null, clearKeychainCommand=null, runFlowCommand=null, setLocationCommand=null, repeatCommand=null, copyTextCommand=null, pasteTextCommand=null, defineVariablesCommand=null, runScriptCommand=null, waitForAnimationToEndCommand=null, evalScriptCommand=null, mockNetworkCommand=null, scrollUntilVisible=null, travelCommand=null, assertOutgoingRequestsCommand=null), logMessages=[])
[INFO ] m.cli.runner.MaestroCommandRunner - Apply configuration COMPLETED
[INFO ] m.cli.runner.MaestroCommandRunner - Launch app "tiktok" RUNNING
[INFO ] m.cli.runner.MaestroCommandRunner - Launch app "tiktok" metadata CommandMetadata(numberOfRuns=null, evaluatedCommand=MaestroCommand(tapOnElement=null, tapOnPoint=null, tapOnPointV2Command=null, scrollCommand=null, swipeCommand=null, backPressCommand=null, assertCommand=null, assertConditionCommand=null, inputTextCommand=null, inputRandomTextCommand=null, launchAppCommand=LaunchAppCommand(appId=tiktok, clearState=null, clearKeychain=null, stopApp=null, permissions=null, launchArguments=null), applyConfigurationCommand=null, openLinkCommand=null, pressKeyCommand=null, eraseTextCommand=null, hideKeyboardCommand=null, takeScreenshotCommand=null, stopAppCommand=null, clearStateCommand=null, clearKeychainCommand=null, runFlowCommand=null, setLocationCommand=null, repeatCommand=null, copyTextCommand=null, pasteTextCommand=null, defineVariablesCommand=null, runScriptCommand=null, waitForAnimationToEndCommand=null, evalScriptCommand=null, mockNetworkCommand=null, scrollUntilVisible=null, travelCommand=null, assertOutgoingRequestsCommand=null), logMessages=[])
[INFO ] util.CommandLineUtils - Running command line operation: [/Users/bytedance/.maestro/deps/applesimutils, --byId, 032BD811-4ACB-49D3-A5EB-101D6605CB46, --bundle, tiktok, --setPermissions, calendar=YES,camera=YES,contacts=YES,faceid=YES,homekit=YES,location=always,medialibrary=YES,microphone=YES,motion=YES,photos=YES,reminders=YES,siri=YES,speech=YES,userTracking=YES]
[INFO ] maestro.Maestro - Launching app tiktok
[INFO ] util.CommandLineUtils - Running command line operation: [xcrun, simctl, spawn, 032BD811-4ACB-49D3-A5EB-101D6605CB46, launchctl, setenv, MAESTRO_SESSION_ID, 5254665a-3157-407d-bd62-05229fba993a]
[INFO ] util.CommandLineUtils - Running command line operation: [xcrun, simctl, launch, 032BD811-4ACB-49D3-A5EB-101D6605CB46, tiktok]
[INFO ] m.cli.runner.MaestroCommandRunner - Launch app "tiktok" COMPLETED
[INFO ] m.cli.runner.MaestroCommandRunner - Swipe from (50%, 70%) to (50%, 10%) in 500 ms RUNNING
[INFO ] m.cli.runner.MaestroCommandRunner - Swipe from (50%, 70%) to (50%, 10%) in 500 ms metadata CommandMetadata(numberOfRuns=null, evaluatedCommand=MaestroCommand(tapOnElement=null, tapOnPoint=null, tapOnPointV2Command=null, scrollCommand=null, swipeCommand=SwipeCommand(direction=null, startPoint=null, endPoint=null, elementSelector=null, startRelative=50%, 70%, endRelative=50%, 10%, duration=500), backPressCommand=null, assertCommand=null, assertConditionCommand=null, inputTextCommand=null, inputRandomTextCommand=null, launchAppCommand=null, applyConfigurationCommand=null, openLinkCommand=null, pressKeyCommand=null, eraseTextCommand=null, hideKeyboardCommand=null, takeScreenshotCommand=null, stopAppCommand=null, clearStateCommand=null, clearKeychainCommand=null, runFlowCommand=null, setLocationCommand=null, repeatCommand=null, copyTextCommand=null, pasteTextCommand=null, defineVariablesCommand=null, runScriptCommand=null, waitForAnimationToEndCommand=null, evalScriptCommand=null, mockNetworkCommand=null, scrollUntilVisible=null, travelCommand=null, assertOutgoingRequestsCommand=null), logMessages=[])
[INFO ] maestro.Maestro - Getting device info
[INFO ] ios.xctest.XCTestIOSDevice - Device info DeviceInfo(widthPixels=1290, heightPixels=2796, widthPoints=430, heightPoints=932)
[INFO ] ios.IOSDevice - Waiting for animation to end with timeout 3000
[INFO ] ios.xctest.XCTestIOSDevice - Screen diff request finished with isScreenStatic = false
[INFO ] ios.IOSDevice - screen static = false
[INFO ] ios.xctest.XCTestIOSDevice - Screen diff request finished with isScreenStatic = false
[INFO ] ios.IOSDevice - screen static = false
[INFO ] ios.xctest.XCTestIOSDevice - Screen diff request finished with isScreenStatic = true
[INFO ] ios.IOSDevice - screen static = true
[INFO ] ios.xctest.XCTestIOSDevice - installed apps: [com.apple.Passbook, com.apple.dt.XcodePreviews, com.apple.MobileAddressBook, com.apple.DocumentsApp, com.apple.MobileSMS, dev.mobile.maestro-driver-iosUITests.xctrunner, com.apple.Maps, tiktok, com.apple.mobilecal, com.apple.Bridge, com.apple.Preferences, com.apple.reminders, com.apple.freeform, com.apple.Health, com.apple.news, com.apple.webapp, com.apple.mobilesafari, com.apple.mobileslideshow, com.apple.shortcuts, org.wikimedia.wikipedia]
[INFO ] ios.xctest.XCTestIOSDevice - Running app id response received tiktok
[INFO ] ios.xctest.XCTestIOSDevice - found running app id tiktok
[INFO ] ios.IOSDevice - Waiting for animation to end with timeout 3000
[INFO ] ios.xctest.XCTestIOSDevice - Screen diff request finished with isScreenStatic = false
[INFO ] ios.IOSDevice - screen static = false
[INFO ] ios.xctest.XCTestIOSDevice - Screen diff request finished with isScreenStatic = true
[INFO ] ios.IOSDevice - screen static = true
[INFO ] m.cli.runner.MaestroCommandRunner - Swipe from (50%, 70%) to (50%, 10%) in 500 ms COMPLETED
[INFO ] m.cli.runner.MaestroCommandRunner - Swipe from (50%, 70%) to (50%, 10%) in 500 ms RUNNING
[INFO ] m.cli.runner.MaestroCommandRunner - Swipe from (50%, 70%) to (50%, 10%) in 500 ms metadata CommandMetadata(numberOfRuns=null, evaluatedCommand=MaestroCommand(tapOnElement=null, tapOnPoint=null, tapOnPointV2Command=null, scrollCommand=null, swipeCommand=SwipeCommand(direction=null, startPoint=null, endPoint=null, elementSelector=null, startRelative=50%, 70%, endRelative=50%, 10%, duration=500), backPressCommand=null, assertCommand=null, assertConditionCommand=null, inputTextCommand=null, inputRandomTextCommand=null, launchAppCommand=null, applyConfigurationCommand=null, openLinkCommand=null, pressKeyCommand=null, eraseTextCommand=null, hideKeyboardCommand=null, takeScreenshotCommand=null, stopAppCommand=null, clearStateCommand=null, clearKeychainCommand=null, runFlowCommand=null, setLocationCommand=null, repeatCommand=null, copyTextCommand=null, pasteTextCommand=null, defineVariablesCommand=null, runScriptCommand=null, waitForAnimationToEndCommand=null, evalScriptCommand=null, mockNetworkCommand=null, scrollUntilVisible=null, travelCommand=null, assertOutgoingRequestsCommand=null), logMessages=[])
[INFO ] ios.IOSDevice - Waiting for animation to end with timeout 3000
[INFO ] ios.xctest.XCTestIOSDevice - Screen diff request finished with isScreenStatic = true
[INFO ] ios.IOSDevice - screen static = true
[INFO ] ios.xctest.XCTestIOSDevice - installed apps: [com.apple.Passbook, com.apple.dt.XcodePreviews, com.apple.MobileAddressBook, com.apple.DocumentsApp, com.apple.MobileSMS, dev.mobile.maestro-driver-iosUITests.xctrunner, com.apple.Maps, tiktok, com.apple.mobilecal, com.apple.Bridge, com.apple.Preferences, com.apple.reminders, com.apple.freeform, com.apple.Health, com.apple.news, com.apple.webapp, com.apple.mobilesafari, com.apple.mobileslideshow, com.apple.shortcuts, org.wikimedia.wikipedia]
[INFO ] ios.xctest.XCTestIOSDevice - Running app id response received tiktok
[INFO ] ios.xctest.XCTestIOSDevice - found running app id tiktok
[INFO ] ios.IOSDevice - Waiting for animation to end with timeout 3000
[INFO ] ios.xctest.XCTestIOSDevice - Screen diff request failed with error = { "message" : "Failed request for XCTest server" }
[INFO ] ios.xctest.XCTestIOSDevice - installed apps: [com.apple.Passbook, com.apple.dt.XcodePreviews, com.apple.MobileAddressBook, com.apple.DocumentsApp, com.apple.MobileSMS, dev.mobile.maestro-driver-iosUITests.xctrunner, com.apple.Maps, tiktok, com.apple.mobilecal, com.apple.Bridge, com.apple.Preferences, com.apple.reminders, com.apple.freeform, com.apple.Health, com.apple.news, com.apple.webapp, com.apple.mobilesafari, com.apple.mobileslideshow, com.apple.shortcuts, org.wikimedia.wikipedia]
[INFO ] ios.xctest.XCTestIOSDevice - request to resolve running app id failed with exception - Code: 400 Body: { "message" : "Failed request for XCTest server" }
[INFO ] maestro.Maestro - Taking screenshot: /var/folders/rf/d2cc2hj112n9vkm3g0l7t3s00000gn/T/screenshot-168542375148315257587238204176079.png
[INFO ] maestro.utils.ScreenshotUtils - Taking screenshot to output sink
[ERROR] maestro.cli.runner.TestRunner - Failed to run flow
java.lang.IllegalStateException: Unable to obtain active app id
	at ios.xctest.XCTestIOSDevice.contentDescriptor(XCTestIOSDevice.kt:57)
	at ios.LocalIOSDevice.contentDescriptor(LocalIOSDevice.kt:35)
	at maestro.drivers.IOSDriver.contentDescriptor(IOSDriver.kt:184)
	at maestro.ViewHierarchy$Companion.from-c1iYVAs(ViewHierarchy.kt:29)
	at maestro.utils.ScreenshotUtils$Companion.viewHierarchy-c1iYVAs(ScreenshotUtils.kt:79)
	at maestro.utils.ScreenshotUtils$Companion.waitForAppToSettle-d60svg8(ScreenshotUtils.kt:39)
	at maestro.drivers.IOSDriver.waitForAppToSettle-FTAEaK0(IOSDriver.kt:500)
	at maestro.Maestro.waitForAppToSettle-FTAEaK0(Maestro.kt:422)
	at maestro.Maestro.waitForAppToSettle-FTAEaK0$default(Maestro.kt:421)
	at maestro.Maestro.swipe(Maestro.kt:148)
	at maestro.Maestro.swipe$default(Maestro.kt:120)
	at maestro.orchestra.Orchestra.swipeCommand(Orchestra.kt:905)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:189)
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:150)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:93)
	at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:179)
	at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2$1.invoke(TestRunner.kt:102)
	at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2$1.invoke(TestRunner.kt:101)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:138)
	at maestro.cli.runner.TestRunner.access$runCatching(TestRunner.kt:28)
	at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2.invoke(TestRunner.kt:101)
	at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2.invoke(TestRunner.kt:89)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
[INFO ] x.installer.LocalXCTestInstaller - [Start] Cleaning up the ui test runner files
[INFO ] x.installer.LocalXCTestInstaller - [Start] Stop XCUITest runner
[INFO ] x.installer.LocalXCTestInstaller - [Done] Stop XCUITest runner
[INFO ] x.installer.LocalXCTestInstaller - [Start] Uninstall XCUITest runner
[INFO ] util.CommandLineUtils - Running command line operation: [xcrun, simctl, uninstall, 032BD811-4ACB-49D3-A5EB-101D6605CB46, dev.mobile.maestro-driver-iosUITests.xctrunner]
[INFO ] x.installer.LocalXCTestInstaller - [Done] Uninstall XCUITest runner
[INFO ] x.installer.LocalXCTestInstaller - [Done] Cleaning up the ui test runner files
```

xctest_runner.log
```
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild test-without-building -xctestrun /var/folders/rf/d2cc2hj112n9vkm3g0l7t3s00000gn/T/maestro-driver-ios-config.xctestrun -destination id=032BD811-4ACB-49D3-A5EB-101D6605CB46

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

2023-05-30 13:14:09.725808+0800 maestro-driver-iosUITests-Runner[27953:12056223] Running tests...
Test Suite 'All tests' started at 2023-05-30 13:14:10.200
Test Suite 'maestro-driver-iosUITests.xctest' started at 2023-05-30 13:14:10.201
Test Suite 'maestro_driver_iosUITests' started at 2023-05-30 13:14:10.201
Test Case '-[maestro_driver_iosUITests.maestro_driver_iosUITests testHttpServer]' started.
    t =     0.00s Start Test at 2023-05-30 13:14:10.203
    t =     0.05s Set Up
2023-05-30 13:14:10.272727+0800 maestro-driver-iosUITests-Runner[27953:12056430] [FlyingFox] starting server ::1:22087
2023-05-30 13:14:10.380365+0800 maestro-driver-iosUITests-Runner[27953:12056439] [FlyingFox] <::1> open connection
2023-05-30 13:14:10.383920+0800 maestro-driver-iosUITests-Runner[27953:12056434] [FlyingFox] <::1> request: GET /subTree
2023-05-30 13:14:10.385328+0800 maestro-driver-iosUITests-Runner[27953:12056223] [SubTreeRouteHandler] Trying to capture hierarchy snapshot for com.apple.springboard
2023-05-30 13:14:10.391678+0800 maestro-driver-iosUITests-Runner[27953:12056223] [SubTreeRouteHandler] [Start] Now trying hierarchy for: com.apple.springboard
    t =     0.19s Find the Application 'com.apple.springboard'
    t =     0.24s Ignoring failure to get hierarchy for remote element in process 94729 (Error getting main window kAXErrorServerNotFound)
2023-05-30 13:14:10.511192+0800 maestro-driver-iosUITests-Runner[27953:12056223] [SubTreeRouteHandler] [Done] Now trying hierarchy for: com.apple.springboard
2023-05-30 13:14:10.511301+0800 maestro-driver-iosUITests-Runner[27953:12056223] [SubTreeRouteHandler] [Start] Now trying hierarchy for: com.apple.springboard
    t =     0.31s Find the Application 'com.apple.springboard'
    t =     0.34s Ignoring failure to get hierarchy for remote element in process 94729 (Error getting main window kAXErrorServerNotFound)
2023-05-30 13:14:10.615644+0800 maestro-driver-iosUITests-Runner[27953:12056223] [SubTreeRouteHandler] [Done] Now trying hierarchy for: com.apple.springboard
2023-05-30 13:14:10.616318+0800 maestro-driver-iosUITests-Runner[27953:12056223] [SubTreeRouteHandler] Successfully got view hierarchy for com.apple.springboard in 230.845215
2023-05-30 13:14:12.048956+0800 maestro-driver-iosUITests-Runner[27953:12056439] [FlyingFox] <::1> open connection
2023-05-30 13:14:12.051086+0800 maestro-driver-iosUITests-Runner[27953:12056439] [FlyingFox] <::1> request: POST /setPermissions
2023-05-30 13:14:13.179077+0800 maestro-driver-iosUITests-Runner[27953:12056470] [FlyingFox] <::1> request: POST /deviceInfo
    t =     2.98s Find the Application 'com.apple.springboard'
    t =     3.08s Ignoring failure to get hierarchy for remote element in process 94729 (Error getting main window kAXErrorServerNotFound)
2023-05-30 13:14:13.381716+0800 maestro-driver-iosUITests-Runner[27953:12056470] [FlyingFox] <::1> request: GET /isScreenStatic
2023-05-30 13:14:13.697883+0800 maestro-driver-iosUITests-Runner[27953:12056430] [FlyingFox] <::1> request: GET /isScreenStatic
2023-05-30 13:14:14.008322+0800 maestro-driver-iosUITests-Runner[27953:12056434] [FlyingFox] <::1> request: GET /isScreenStatic
2023-05-30 13:14:14.627212+0800 maestro-driver-iosUITests-Runner[27953:12056430] [FlyingFox] <::1> request: POST /runningApp
2023-05-30 13:14:14.729771+0800 maestro-driver-iosUITests-Runner[27953:12056434] [FlyingFox] <::1> request: POST /swipeV2
2023-05-30 13:14:14.730721+0800 maestro-driver-iosUITests-Runner[27953:12056223] [SwipeRouteHandler] Swipe from (215.0, 652.0) to (215.0, 93.0) with 0.5 duration
    t =     4.53s Swipe from (215.0, 652.0) to (215.0, 93.0) with 0.5 duration
    t =     4.53s     Find the Application 'tiktok'
    t =     7.73s     Check for interrupting elements affecting "tiktok" Application
    t =     7.90s     Synthesize event
2023-05-30 13:14:19.186779+0800 maestro-driver-iosUITests-Runner[27953:12056438] [FlyingFox] <::1> request: GET /isScreenStatic
2023-05-30 13:14:19.703747+0800 maestro-driver-iosUITests-Runner[27953:12056432] [FlyingFox] <::1> request: GET /isScreenStatic
2023-05-30 13:14:20.222267+0800 maestro-driver-iosUITests-Runner[27953:12056434] [FlyingFox] <::1> request: GET /isScreenStatic
2023-05-30 13:14:21.060449+0800 maestro-driver-iosUITests-Runner[27953:12056430] [FlyingFox] <::1> request: POST /runningApp
2023-05-30 13:14:21.166433+0800 maestro-driver-iosUITests-Runner[27953:12056432] [FlyingFox] <::1> request: POST /swipeV2
2023-05-30 13:14:21.166872+0800 maestro-driver-iosUITests-Runner[27953:12056223] [SwipeRouteHandler] Swipe from (215.0, 652.0) to (215.0, 93.0) with 0.5 duration
    t =    10.97s Swipe from (215.0, 652.0) to (215.0, 93.0) with 0.5 duration
    t =    10.97s     Find the Application 'tiktok'
2023-05-30 13:14:51.127005+0800 maestro-driver-iosUITests-Runner[27953:12056438] [FlyingFox] <::1> open connection
2023-05-30 13:14:51.128470+0800 maestro-driver-iosUITests-Runner[27953:12056438] [FlyingFox] <::1> request: GET /isScreenStatic
    t =    41.97s         Find the Application 'tiktok' (retry 1)
2023-05-30 13:15:21.585427+0800 maestro-driver-iosUITests-Runner[27953:12056434] [FlyingFox] <::1> open connection
2023-05-30 13:15:21.587933+0800 maestro-driver-iosUITests-Runner[27953:12056434] [FlyingFox] <::1> request: POST /runningApp
    t =    72.98s         Find the Application 'tiktok' (retry 2)
2023-05-30 13:15:51.549575+0800 maestro-driver-iosUITests-Runner[27953:12056427] [FlyingFox] <::1> open connection
2023-05-30 13:15:51.550877+0800 maestro-driver-iosUITests-Runner[27953:12056427] [FlyingFox] <::1> request: GET /screenshot
2023-05-30 13:15:53.186663+0800 maestro-driver-iosUITests-Runner[27953:12056435] [FlyingFox] handler error: Timed out before completion
2023-05-30 13:15:53.188052+0800 maestro-driver-iosUITests-Runner[27953:12056435] [FlyingFox] <::1> error: SocketError. Read(54): Connection reset by peer
2023-05-30 13:15:53.188216+0800 maestro-driver-iosUITests-Runner[27953:12056435] [FlyingFox] <::1> close connection
2023-05-30 13:15:53.741211+0800 maestro-driver-iosUITests-Runner[27953:12056427] [FlyingFox] handler error: Timed out before completion
2023-05-30 13:15:53.741502+0800 maestro-driver-iosUITests-Runner[27953:12056427] [FlyingFox] <::1> error: SocketError. Read(54): Connection reset by peer
2023-05-30 13:15:53.741611+0800 maestro-driver-iosUITests-Runner[27953:12056427] [FlyingFox] <::1> close connection
2023-05-30 13:15:53.744961+0800 maestro-driver-iosUITests-Runner[27953:12056439] [FlyingFox] handler error: Timed out before completion

```

**To Reproduce**

```yaml
- launchApp
- swipe:
    start: 50%, 70%
    end: 50%, 10%
- swipe:
    start: 50%, 70%
    end: 50%, 10%
```

Happy to contribute if you can help to give me some clue

**Comment by bartekpacia** [comment]
hey, sorry but this is not reproducible, + there hasn't been any recent activity. feel free to create a new bug report with more info if the issue still persists.
