### ISSUE TITLE
Maestro hierarchy : Channel ManagedChannelImpl was not shutdown properly!!!

### ISSUE THREAD

**Issue by g123k** [mobile-dev-inc/maestro#114]
Hello,

On iOS, when running `maestro hierarchy`, the command ends with:

```bash
Sep 03, 2022 9:59:57 AM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=1, target=localhost:7001} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:630)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:297)
	at maestro.drivers.AndroidDriver.<init>(AndroidDriver.kt:55)
	at maestro.Maestro$Companion.android(Maestro.kt:297)
	at maestro.Maestro$Companion.android$default(Maestro.kt:296)
	at maestro.cli.util.MaestroFactory.createAndroid(MaestroFactory.kt:54)
	at maestro.cli.util.MaestroFactory.autoDetectPlatform(MaestroFactory.kt:63)
	at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:33)
	at maestro.cli.command.PrintHierarchyCommand.run(PrintHierarchyCommand.kt:36)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:74)
```

**Comment by dmitry-zaitsev** [comment]
Thank you for spotting this. It is not a severe issue but is indeed worth fixing 👍
