### ISSUE TITLE
[v1.28.0] - Does not execute actions on an Xiaomi Mi 9 phone (Android OS 10), errors with io.grpc.StatusRuntimeException: UNKNOWN   

### ISSUE THREAD

**Issue by SuperRoach** [mobile-dev-inc/maestro#1140]
**Describe the bug**
It seems on an particular brand of device, there is additional blocking being done that prevents Maestro from running.

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Start on an Xiaomi Mi 9
2. Run maestro test on any file 
3. The phone will launch the app, but any actions will not happen, and error out.

**Expected behavior**
For the actions to run

**Screenshots**
Each  time Maestro studio runs, this is seen. Even clicking on "accept" makes no difference.
![image](https://github.com/mobile-dev-inc/maestro/assets/63333/c02f115c-7653-461a-b61e-f448ae117132)

**Environment information (please complete the following information):**

- Maestro version [e.g. v1.2.3]: CLI 1.28.0
- Platform: [e.g. iOS 16.4.1, Android 11.0, Chrome]. Mac OS 13.1
- Framework: [Native iOS/Android, Flutter, React Native, etc]. Native Phone
- Device model and OS version: [e.g. iPhone6] Xiaomi Mi 9, Android 10
- Simulator, emulator or physical device. Physical
- Host [e.g. Mac M1, Windows, Linux, etc]  Mac OS M1

**Workspace (if applicable)**
It's for any kind of test, ie click on a google search bar on the home screen.

**Bugreport output (if applicable)**
```
Running on 706e87de


io.grpc.StatusRuntimeException: UNKNOWN   
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)                                        
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
        at maestro_android.MaestroDriverGrpc$MaestroDriverBlockingStub.tap(MaestroDriverGrpc.java:602)                    
        at maestro.drivers.AndroidDriver.tap(AndroidDriver.kt:217)
        at maestro.Maestro.hierarchyBasedTap-9V-jo0g(Maestro.kt:310)
        at maestro.Maestro.performTap-9V-jo0g(Maestro.kt:260)
	at maestro.Maestro.tap-vUA2mXM(Maestro.kt:192)
	at maestro.orchestra.Orchestra.tapOnElement(Orchestra.kt:651)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:173)
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:150)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:93)
	at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:179)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:45)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:42)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:138)
	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:42)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:166)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:126)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:99)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:57)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:126)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:44)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:136)


==== Debug output (logs & screenshots) ====
```

**Additional context**
This is interesting because I tested it on an Android emulator for version 10 as well - and it seemed to work. I'd be interested in what kind of permission Maestro is asking for, to see what would need to be "allowed" on that phone to have it work.

**Comment by felipevolpone** [comment]
Real devices aren't yet fully supported by Maestro
