### ISSUE TITLE
[v1.29.0] Flow syntax errors lead to unclear error messages

### ISSUE THREAD

**Issue by zolbooo** [mobile-dev-inc/maestro#1190]
Hi there 👋
Giving a shot to Maestro, so far great experience, thank y'all!

**Describe the bug**
Running `maestro test` command with flow file with incorrect syntax prints strange exception:
```
java.lang.IllegalArgumentException: Cannot deserialize value of type `maestro.orchestra.yaml.YamlElementSelector` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: java.util.ArrayList[5]->maestro.orchestra.yaml.YamlFluentCommand["assertVisible"])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4393)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4334)
        at maestro.orchestra.yaml.YamlCommandReader.readConfigAndCommands(YamlCommandReader.kt:106)
        at maestro.orchestra.yaml.YamlCommandReader.readConfig(YamlCommandReader.kt:63)
        at maestro.cli.command.TestCommand.isWebFlow(TestCommand.kt:101)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:121)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:44)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at maestro.cli.AppKt.main(App.kt:136)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Cannot deserialize value of type `maestro.orchestra.yaml.YamlElementSelector` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: java.util.ArrayList[5]->maestro.orchestra.yaml.YamlFluentCommand["assertVisible"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:392)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1821)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:316)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4388)
        ... 15 more
Caused by: java.lang.IllegalArgumentException: Cannot deserialize value of type `maestro.orchestra.yaml.YamlElementSelector` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4393)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4324)
        at maestro.orchestra.yaml.YamlElementSelectorDeserializer.deserialize(YamlElementSelectorUnion.kt:45)
        at maestro.orchestra.yaml.YamlElementSelectorDeserializer.deserialize(YamlElementSelectorUnion.kt:36)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        ... 20 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `maestro.orchestra.yaml.YamlElementSelector` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1462)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeFromArray(BeanDeserializer.java:648)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:211)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4388)
        ... 25 more
```

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Start the simulator
2. Run `maestro test ...` with following file provided below

**Expected behavior**
A clear and concise description of syntax error should be printed.

**Screenshots**
None

**Environment information (please complete the following information):**

- Maestro version v1.29.0
- Platform: macOS
- Framework: React Native
- Device model and OS version: iPhone 14
- Simulator
- Mac M1

**Workspace (if applicable)**
```
```yaml
appId: ${APP_ID}
---
- launchApp:
    clearState: true
- assertVisible:
    id: slide-1
- tapOn:
    id: next
- assertVisible:
    id: slide-2
- tapOn:
    id: next
- assertVisible:
    - slide-3 # This line is incorrect, it should be an id property
- tapOn:
    id: next
- assertVisible:
    id: login
```

**Bugreport output (if applicable)**
N/A

**Additional context**
N/A

**Comment by felipevolpone** [comment]
Can you try again with newer maestro version and report back if that still an issue?
