### ISSUE TITLE
Troubleshooting steps when an active emulator is not found are not clear

### ISSUE THREAD

**Issue by neonfink** [mobile-dev-inc/maestro#123]
Looking at the documentation, I understand that there is a way to explicitly connect to a specific physical Android device over WiFi pairing, whereas in case with emulators Maestro is expected to always automatically connect to any emulator that is currently running.

That is unfortunately does not work for me and I'm not entirely sure where to look for troubleshooting steps 🤔 

When I execute `adb devices` I get the following output, which is what I expect - got one single Android emulator currently running on my machine:
```
List of devices attached
emulator-5554	device`
```
However, when I try to obtain the hierarchy or execute a flow (e.g. `maestro -p android hierarchy`), I get the following error
```
java.lang.IllegalStateException: No android devices found.
	at maestro.cli.util.MaestroFactory.createAndroid(MaestroFactory.kt:51)
	at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:35)
	at maestro.cli.command.PrintHierarchyCommand.run(PrintHierarchyCommand.kt:36)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:74)
```

What would you suggest to try to make it work? Are there perhaps any troubleshooting steps that could be added to the documentation for cases like this?

**Comment by dmitry-zaitsev** [comment]
Could you confirm that you have the following files in your `~/..android` folder?

- `adbkey`
- `adbkey.pub`

**Comment by neonfink** [comment]
@dmitry-zaitsev I got `adbkey` in my `~/.android`, but not `adbkey.pub` 🤔 

Unfortunately I'm not aware how / when the `.pub` one is expected to be generate though?

**Comment by dmitry-zaitsev** [comment]
@neonfink I see, it appears that `adbkey.pub` is not actually needed, but we are still checking for it. While we are fixing it on our side, what should unblock you is this command:

```
touch ~/.android/adbkey.pub
```

**Comment by neonfink** [comment]
@dmitry-zaitsev it worked, thank you!

**Comment by ColtonIdle** [comment]
Came to the issue tracker to complain about the same issue.

`adb devices` shows my emulator. while trying to run a sample test with maestro `maestro test sample_from_readme.yaml` shows 

```
java.lang.IllegalStateException: No devices found. Select a platform by passing --platform <android|ios> for more details
```

On a whim I tried `touch ~/.android/adbkey.pub` and re-ran the command and now it works. 

magic!

**Comment by dmitry-zaitsev** [comment]
Maestro 1.4.2 was released that addresses this issue

**Comment by astutesoftware** [comment]
Not resolved on windows at least even after installing 1.4.2

D:\data\maestro\maestro-1.4.2\bin>adb devices
List of devices attached
emulator-5554   device

D:\data\maestro\maestro-1.4.2\bin>maestro test twitter.yaml
java.lang.IllegalStateException: No devices found. Select a platform by passing --platform <android|ios> for more details
        at maestro.cli.util.MaestroFactory.autoDetectPlatform(MaestroFactory.kt:68)
        at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:33)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:58)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:30)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at maestro.cli.AppKt.main(App.kt:74)

**Comment by brookmg** [comment]
I am experiencing a similar issue with maestro version 1.7.0. `adb devices` returns the active device
```

**Comment by aakash1313** [comment]
I still get this error on MAC :(

**Comment by Bournegit** [comment]
It worked for the first time but later got this error 
`java.lang.IllegalStateException: No devices found. Select a platform by passing --platform <android|ios> for more details
	at maestro.cli.util.MaestroFactory.autoDetectPlatform(MaestroFactory.kt:78)
	at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:34)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:58)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:30)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:94)`
