### ISSUE TITLE
`java.lang.IllegalStateException` happening on starting a mock server. [Maestro v1.29.0]

### ISSUE THREAD

**Issue by denil-ct** [mobile-dev-inc/maestro#1235]
**Describe the bug**
While writing a test for an iOS app, I encountered an issue, where on starting a mock server on any port, makes maestro emit an exception. After stopping the mock server, maestro resumes working.

```log
java.lang.IllegalStateException: Unable to obtain active app id                 
        at ios.xctest.XCTestIOSDevice.contentDescriptor(XCTestIOSDevice.kt:57)  
        at ios.LocalIOSDevice.contentDescriptor(LocalIOSDevice.kt:35)           
        at maestro.drivers.IOSDriver.contentDescriptor(IOSDriver.kt:184)        
        at maestro.ViewHierarchy$Companion.from-c1iYVAs(ViewHierarchy.kt:29)    
        at maestro.Maestro.viewHierarchy-prqvCes(Maestro.kt:416)                
        at maestro.orchestra.Orchestra.findElement(Orchestra.kt:770)            
        at maestro.orchestra.Orchestra.evaluateCondition(Orchestra.kt:463)      
        at maestro.orchestra.Orchestra.assertConditionCommand(Orchestra.kt:253) 
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:196)         
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:155)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:98)
	at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:179)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:45)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:42)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:138)
	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:42)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:166)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:126)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:99)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:57)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:126)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:44)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:136)
```

**To Reproduce**

1) Start mock server. I used both mockoon and wiremock and both had the same issue. I had the port at 8080, 3000, 23456 and all had the same issue.
2) Run this maestro flow using `maestro test explore.yaml`, assuming the app is already installed in a simulator and simulator is booted.
```yaml
appId: com.apple.app
---
- launchApp:
#have tried with these options removed as well and it doesn't make any difference
    stopApp: false 
    permissions: { all: allow }

- assertVisible:
    id: "tab_bar_item_explore"
```
3) After launching the app, the app tends to become unresponsive and maestro crashes with the above exception.
4) Once the mock server is stopped, the test works as expected and there are no exceptions.

**Expected behavior**
Test should pass

**Environment information (please complete the following information):**

- Maestro version - 1.29.0
- Platform: iOS 16.4, iOS 16.2, iOS 17.0
- Framework: Native iOS with react native for some pages.
- Device model and OS version: iPhone 14 Pro, iOS 16.4, iOS 16.2, iOS 17.0
- Simulator, emulator or physical device: Simulator
- Host:
        - Processors tested: M1 Pro, M1
        - OS tested: MacOS 13.4
        - Xcode tested: 14.3, 14.2, 15 beta 

**Bugreport output (if applicable)**
[2023-07-11_192616.zip](https://github.com/mobile-dev-inc/maestro/files/12015555/2023-07-11_192616.zip)

**Additional context**
XCTestRunnerLogs - [xctest_runner_2023-07-11_192627.log](https://github.com/mobile-dev-inc/maestro/files/12015563/xctest_runner_2023-07-11_192627.log)

**Comment by denil-ct** [comment]
Not an issue. There was an issue with our app related to tableviews.

**Comment by amanjeetsingh150** [comment]
Hey, @denil-ct it seems like you are trying network mocking. Would love to know what tool you are using and how you are approaching?

**Comment by denil-ct** [comment]
@amanjeetsingh150  I started out with Wiremock as I was more familiar with it. Then upon discovering this issue, thought wiremock might not be working well with maestro, some port conflicts of sorts, so started to look at alternatives. Ultimately landed with mockoon, as it had a clean, simple UI and enough functionality for us. Plus with the UI, its easier for new people to pick it up.
