### ISSUE TITLE
[1.30.4] java.net.ConnectException: Failed to connect to maestro-record.ngrok.io

### ISSUE THREAD

**Issue by Amurmurmur** [mobile-dev-inc/Maestro#1281]
**Describe the bug**

```
Rendering your video. This usually takes a couple minutes...                                                
                                                                                                            
Uploading raw files for render...                                                                           
█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░[java.net.SocketException: Broken pipe (Write failed), java.net.SocketException: Broken pipe (Write failed), java.net.SocketException: Broken pipe (Write failed), java.net.SocketException: Broken pipe (Write failed), java.net.SocketException: Broken pipe (Write failed), java.net.SocketException: Broken pipe (Write failed), java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2a05:d014:21b:8e01:0:0:6e:4:443, java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2a05:d014:21b:8e01:0:0:6e:1:443, java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2a05:d014:21b:8e02:0:0:6e:5:443, java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2a05:d014:21b:8e02:0:0:6e:2:443, java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2a05:d014:21b:8e00:0:0:6e:0:443]

java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2a05:d014:21b:8e00:0:0:6e:3:443
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at maestro.cli.api.SystemInformationInterceptor.intercept(ApiClient.kt:470)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at maestro.cli.api.ApiClient.render(ApiClient.kt:192)
        at maestro.cli.command.RecordCommand$call$1.invoke(RecordCommand.kt:100)
        at maestro.cli.command.RecordCommand$call$1.invoke(RecordCommand.kt:72)
        at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:100)
        at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:58)
        at maestro.cli.command.RecordCommand.call(RecordCommand.kt:72)
        at maestro.cli.command.RecordCommand.call(RecordCommand.kt:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
```

On android I get the fllowing error during the upload step:
```
Render request failed (500): {"message":"ENOSPC: no space left on device, open '/var/folders/wn/svd1m4gn1977w0xdlyh81mlm0000gn/T/clki9hu9b00crs5pu9lbr0f19'"}
```

It all worked fine literally yesterday Im pretty sure its on your side guys :)

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Start the simulator
2. Run `maestro record anyflow.yml`
3. The Flow fails at upload step

**Expected behavior**

**Screenshots**

**Environment information (please complete the following information):**

- Maestro version [e.g. v1.2.3]
- Platform: [e.g. iOS 16.4.1, Android 11.0, Chrome]
- Framework: [React Native]
- Device model and OS version: [iPhone. 14 Pro Max]
- Simulator
- Host [Mac M1 Pro]

**Workspace (if applicable)**
Please share your workspace with Flow files and application binary if you are able to do so as that greatly helps in reproduction efforts.

**Bugreport output (if applicable)**
The zip files created when `maestro bugreport` can be uploaded here as well if applicable.

**Additional context**

**Comment by Yash-Garg** [comment]
Facing the same here on WSL and Windows 11.
Maestro Version - v1.30.4

### Stacktrace

```java
Rendering your video. This usually takes a couple minutes...

[java.net.SocketException: Connection reset by peer (Write failed), java.net.SocketException: Connection reset by peer (Write failed), java.net.SocketException: Connection reset by peer (Write failed), java.net.SocketException: Connection reset by peer (Write failed), java.net.SocketException: Connection reset by peer (Write failed), java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2406:da1a:e91:9300:0:0:6e:3:443, java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2406:da1a:e91:9300:0:0:6e:0:443, java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2406:da1a:e91:9301:0:0:6e:1:443, java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2406:da1a:e91:9302:0:0:6e:2:443]

java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2406:da1a:e91:9301:0:0:6e:4:443
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at maestro.cli.api.SystemInformationInterceptor.intercept(ApiClient.kt:470)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at maestro.cli.api.ApiClient.render(ApiClient.kt:192)
        at maestro.cli.command.RecordCommand$call$1.invoke(RecordCommand.kt:100)
        at maestro.cli.command.RecordCommand$call$1.invoke(RecordCommand.kt:72)
        at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:100)
        at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:58)
        at maestro.cli.command.RecordCommand.call(RecordCommand.kt:72)
        at maestro.cli.command.RecordCommand.call(RecordCommand.kt:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at maestro.cli.AppKt.main(App.kt:131)
        Suppressed: java.net.SocketException: Connection reset by peer (Write failed)
                at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
                at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
                at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
                at java.base/sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:345)
                at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1305)
                at okio.OutputStreamSink.write(JvmOkio.kt:57)
                at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
                at okhttp3.internal.http1.Http1ExchangeCodec$KnownLengthSink.write(Http1ExchangeCodec.kt:271)
                at okio.ForwardingSink.write(ForwardingSink.kt:29)
                at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
                at okio.ForwardingSink.write(ForwardingSink.kt:29)
                at maestro.cli.api.ApiClient$observable$1$writeTo$forwardingSink$1.write(ApiClient.kt:367)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:194)
                at okhttp3.RequestBody$Companion$asRequestBody$1.writeTo(RequestBody.kt:167)
                at maestro.cli.api.ApiClient$observable$1.writeTo(ApiClient.kt:373)
                at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
                at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
                at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
                ... 27 more
        Suppressed: java.net.SocketException: Connection reset by peer (Write failed)
                at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
                at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
                at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
                at java.base/sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:345)
                at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1305)
                at okio.OutputStreamSink.write(JvmOkio.kt:57)
                at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
                at okhttp3.internal.http1.Http1ExchangeCodec$KnownLengthSink.write(Http1ExchangeCodec.kt:271)
                at okio.ForwardingSink.write(ForwardingSink.kt:29)
                at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
                at okio.ForwardingSink.write(ForwardingSink.kt:29)
                at maestro.cli.api.ApiClient$observable$1$writeTo$forwardingSink$1.write(ApiClient.kt:367)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:194)
                at okhttp3.RequestBody$Companion$asRequestBody$1.writeTo(RequestBody.kt:167)
                at maestro.cli.api.ApiClient$observable$1.writeTo(ApiClient.kt:373)
                at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
                at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
                at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
                ... 27 more
        Suppressed: java.net.SocketException: Connection reset by peer (Write failed)
                at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
                at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
                at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
                at java.base/sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:345)
                at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1305)
                at okio.OutputStreamSink.write(JvmOkio.kt:57)
                at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
                at okhttp3.internal.http1.Http1ExchangeCodec$KnownLengthSink.write(Http1ExchangeCodec.kt:271)
                at okio.ForwardingSink.write(ForwardingSink.kt:29)
                at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
                at okio.ForwardingSink.write(ForwardingSink.kt:29)
                at maestro.cli.api.ApiClient$observable$1$writeTo$forwardingSink$1.write(ApiClient.kt:367)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:194)
                at okhttp3.RequestBody$Companion$asRequestBody$1.writeTo(RequestBody.kt:167)
                at maestro.cli.api.ApiClient$observable$1.writeTo(ApiClient.kt:373)
                at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
                at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
                at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
                ... 27 more
        Suppressed: java.net.SocketException: Connection reset by peer (Write failed)
                at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
                at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
                at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
                at java.base/sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:345)
                at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1305)
                at okio.OutputStreamSink.write(JvmOkio.kt:57)
                at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
                at okhttp3.internal.http1.Http1ExchangeCodec$KnownLengthSink.write(Http1ExchangeCodec.kt:271)
                at okio.ForwardingSink.write(ForwardingSink.kt:29)
                at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
                at okio.ForwardingSink.write(ForwardingSink.kt:29)
                at maestro.cli.api.ApiClient$observable$1$writeTo$forwardingSink$1.write(ApiClient.kt:367)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:194)
                at okhttp3.RequestBody$Companion$asRequestBody$1.writeTo(RequestBody.kt:167)
                at maestro.cli.api.ApiClient$observable$1.writeTo(ApiClient.kt:373)
                at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
                at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
                at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
                ... 27 more
        Suppressed: java.net.SocketException: Connection reset by peer (Write failed)
                at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
                at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
                at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
                at java.base/sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:345)
                at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1305)
                at okio.OutputStreamSink.write(JvmOkio.kt:57)
                at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
                at okhttp3.internal.http1.Http1ExchangeCodec$KnownLengthSink.write(Http1ExchangeCodec.kt:271)
                at okio.ForwardingSink.write(ForwardingSink.kt:29)
                at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
                at okio.ForwardingSink.write(ForwardingSink.kt:29)
                at maestro.cli.api.ApiClient$observable$1$writeTo$forwardingSink$1.write(ApiClient.kt:367)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:194)
                at okhttp3.RequestBody$Companion$asRequestBody$1.writeTo(RequestBody.kt:167)
                at maestro.cli.api.ApiClient$observable$1.writeTo(ApiClient.kt:373)
                at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
                at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
                at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
                ... 27 more
        Suppressed: java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2406:da1a:e91:9300:0:0:6e:3:443
                ... 34 more
        Caused by: java.net.ConnectException: Network is unreachable (connect failed)
                at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
                at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
                at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
                at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
                at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
                at java.base/java.net.Socket.connect(Socket.java:609)
                at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
                at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
                ... 33 more
        Suppressed: java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2406:da1a:e91:9300:0:0:6e:0:443
                ... 34 more
        Caused by: java.net.ConnectException: Network is unreachable (connect failed)
                at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
                at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
                at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
                at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
                at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
                at java.base/java.net.Socket.connect(Socket.java:609)
                at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
                at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
                ... 33 more
        Suppressed: java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2406:da1a:e91:9301:0:0:6e:1:443
                ... 34 more
        Caused by: java.net.ConnectException: Network is unreachable (connect failed)
                at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
                at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
                at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
                at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
                at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
                at java.base/java.net.Socket.connect(Socket.java:609)
                at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
                at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
                ... 33 more
        Suppressed: java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2406:da1a:e91:9302:0:0:6e:2:443
                ... 34 more
        Caused by: java.net.ConnectException: Network is unreachable (connect failed)
                at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
                at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
                at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
                at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
                at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
                at java.base/java.net.Socket.connect(Socket.java:609)
                at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
                at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
                ... 33 more
Caused by: java.net.ConnectException: Network is unreachable (connect failed)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        ... 33 more
        
```

**Comment by amanjeetsingh150** [comment]
Can you try following before running this command:

* A healthy internet connection
* There is space on the local device you are running maestro on
* There is space on emulator device if you are trying with Android.

Also is it happening everytime or only sometimes?

**Comment by amanjeetsingh150** [comment]
Hey @Amurmurmur @Yash-Garg Can you try following before running this command:

* A healthy internet connection
* There is space on the local device you are running maestro on
* There is space on emulator device if you are trying with Android.

Also is it happening everytime or only sometimes?

**Comment by Yash-Garg** [comment]
@amanjeetsingh150 it was happening yesterday, but I tried today and it's working fine now!

**Comment by amanjeetsingh150** [comment]
@Yash-Garg ohh ok glad it got fixed, do you remember what changed with your environment from yesterday. Just trying to see if we can better surface any error 🤔

**Comment by roshani-prajapati-us** [comment]
it was work fine  yesterday, but I tried today and it's not working..!!
Rendering your video. This usually takes a couple minutes...

Uploading raw files for render...
█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░[java.net.SocketException: Broken pipe (Write failed), java.net.SocketException: Broken pipe (Write failed), java.net.SocketException: Broken pipe (Write failed), java.net.SocketException: Broken pipe (Write failed), java.net.SocketException: Broken pipe (Write failed), java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2406:da1a:e91:9301:0:0:6e:4:443, java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2406:da1a:e91:9300:0:0:6e:0:443, java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2406:da1a:e91:9300:0:0:6e:3:443, java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2406:da1a:e91:9301:0:0:6e:1:443]

java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2406:da1a:e91:9302:0:0:6e:2:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at maestro.cli.api.SystemInformationInterceptor.intercept(ApiClient.kt:516)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at maestro.cli.api.ApiClient.render(ApiClient.kt:202)
	at maestro.cli.command.RecordCommand$call$1.invoke(RecordCommand.kt:111)
	at maestro.cli.command.RecordCommand$call$1.invoke(RecordCommand.kt:83)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:101)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:58)
	at maestro.cli.command.RecordCommand.call(RecordCommand.kt:83)
	at maestro.cli.command.RecordCommand.call(RecordCommand.kt:38)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:117)

**Comment by Fishbowler** [comment]
Unsure what was causing the network instability back then.

Maybe it was a server issue that's since been fixed.

There's now a `maestro record --local` for network environments that throttle or block ngrok.io.
