### ISSUE TITLE
[BUG] - Exception in thread "pool-4-thread-1" java.io.IOException: Command failed (host:transport:emulator-5554): device offline

### ISSUE THREAD

**Issue by athosoli** [mobile-dev-inc/maestro#1289]
When running multiple tests at once with "maestro test ./android/.maestro/" command
using the Pixel 2 API 31 emulator, from android studio, this error is displayed during execution:
Exception in thread "pool-4-thread-1" java.io.IOException: Command failed (host:transport:emulator-5554): device offline
         at dadb.adbserver.AdbServer.send$dadb(AdbServer.kt:99)
         at dadb.adbserver.AdbServerDadb.open(AdbServer.kt:137)
         at dadb.forwarding.TcpForwarder.handleForwarding$lambda-1(TcpForwarder.kt:64)
         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
         at java.base/java.lang.Thread.run(Thread.java:1623)

The problem does not occur when I run a few features, uams 4 for example, but when there are more than 5 the error occurs on Android.
In tests with IOS, I can run all 50 test files without showing this error, see that this is only happening on android.
![image](https://github.com/mobile-dev-inc/maestro/assets/64941377/cb33cb64-06e9-44ba-8254-5d0abe8cf977)

**Comment by kojofosu** [comment]
Having same issue

**Comment by athosoli** [comment]
hello, I identified that it was the google api version, I downloaded version 31, it solved the problem, in versions 30 and 33 this problem is happening

**Comment by didyk** [comment]
@athosoli hi! I see the same error in the 31

**Comment by Ademsk1** [comment]
Seeing this in 33 too, but just for running a single flow (with recording), in GH actions. Didn't have this for 16core ubuntu, but 4core is definitely a problem

**Comment by DannyCork** [comment]
I see this in an emulator using google API version 31 :(

**Comment by tiagodread** [comment]
This is happening on API 29 on CI as well

**Comment by dtirackers** [comment]
Any updates on this?

**Comment by talhaoz** [comment]
Any updates on this? How to solve this issue? This is still exist on API 30

**Comment by tajchert** [comment]
I'm facing same issue (emulator is live and adb is reporting it live) but maestro fails with logs:

`Exception in thread "pool-4-thread-1" java.io.IOException: Command failed (host:transport:emulator-5554): device offline
	at dadb.adbserver.AdbServer.send$dadb(AdbServer.kt:99)
	at dadb.adbserver.AdbServerDadb.open(AdbServer.kt:137)
	at dadb.forwarding.TcpForwarder.handleForwarding$lambda-1(TcpForwarder.kt:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)`
	
This is Google google_apis_playstore arm64-v8a, API level 32 image. Fresh boot.

**Comment by DavidREntwistle** [comment]
I've raised the same issue here: 
https://github.com/mobile-dev-inc/maestro/issues/1525
Also looks similar to:
https://github.com/mobile-dev-inc/maestro/issues/1495
https://github.com/mobile-dev-inc/maestro/issues/1304
https://github.com/mobile-dev-inc/maestro/issues/1570
