### ISSUE TITLE
[1.30.4] `xcuitest.XCTestDriverClient$XCTestDriverUnreachable`

### ISSUE THREAD

**Issue by denil-ct** [mobile-dev-inc/maestro#1299]
**Describe the bug**
When running maestro test, I'm getting an exception
```
xcuitest.XCTestDriverClient$XCTestDriverUnreachable: Failed to reach XCUITest Server in restart
	at xcuitest.XCTestDriverClient.restartXCTestRunnerService(XCTestDriverClient.kt:52)
	at ios.xctest.XCTestIOSDevice.open(XCTestIOSDevice.kt:33)
	at ios.LocalIOSDevice.open(LocalIOSDevice.kt:25)
	at maestro.drivers.IOSDriver.open(IOSDriver.kt:84)
	at maestro.Maestro$Companion.ios(Maestro.kt:579)
	at maestro.cli.session.MaestroSessionManager.createIOS(MaestroSessionManager.kt:329)
	at maestro.cli.session.MaestroSessionManager.createMaestro(MaestroSessionManager.kt:157)
	at maestro.cli.session.MaestroSessionManager.access$createMaestro(MaestroSessionManager.kt:50)
	at maestro.cli.session.MaestroSessionManager$newSession$session$1.invoke(MaestroSessionManager.kt:82)
	at maestro.cli.session.MaestroSessionManager$newSession$session$1.invoke(MaestroSessionManager.kt:81)
	at maestro.cli.db.KeyValueStore.withExclusiveLock(KeyValueStore.kt:37)
	at maestro.cli.session.SessionStore.withExclusiveLock(SessionStore.kt:74)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:81)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:58)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:126)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:44)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:131)
```
Also, you can see the maestro-driver app getting installed after maestro exit from command line.

**To Reproduce**
- Clone a new simulator from existing simulator (iOS 16.4, iPhone 14 Pro)
- Run this command. Using and operator for convenience. You could remove the and operator and put into a script, and it will still produce the same result.
```
xcrun simctl boot <device uuid> && xcrun simctl install <device uuid> ABC.app && maestro --device=<device uuid> test flow.yaml
```
- Adding explicit sleep command for 30 seconds, didn't have much effect. I got it to run once out of five attempts.

**Expected behavior**
Launch the app and execute the tests.

**Screenshots**
NA

**Environment information (please complete the following information):**

- Maestro version - 1.30.4
- Platform - iOS 16.4.1
- Framework - Native
- Device model and OS version - iPhone 14 Pro, iOS 16.4
- Simulator, emulator or physical device - Simulator
- Host - Macbook Pro M1, 16 GB

**Workspace (if applicable)**
NA

**Bugreport output (if applicable)**
[Archive.zip](https://github.com/mobile-dev-inc/maestro/files/12214140/Archive.zip)

**Additional context**
NA

**Comment by hackdie** [comment]
https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1689668746779869

im having same issue, hope they can fix it soon 🙏🏼

**Comment by denil-ct** [comment]
Issue still exists on 1.31.0

**Comment by raulriera** [comment]
Having this issue only when upgrading to the latests macOS Venture https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1693599067865679

**Comment by denil-ct** [comment]
@larryng it seems maestro's connection keeps getting reset, every time it sends a SYN packet, whereas in the curl it gets the ack and establishes a TCP connection and proceeds to communicate data.
If the localhost is pointed to ipv4, is the curl request working?

**Comment by larryng** [comment]
>  If the localhost is pointed to ipv4, is the curl request working?

Originally my /etc/hosts only had `127.0.0.1 localhost` and the curl request did work, although it still uses IPv6 (maybe curl has special support for `localhost`?). However, the curl request fails if using the `-4, --ipv4` flag to force IPv4.

**Comment by denil-ct** [comment]
I seem to have mixed results with the workaround.
It started to work fine at first, but after opening a tcpdump session, it stopped working :(

Will have to check how it behaves in CI.

**Comment by amanjeetsingh150** [comment]
> but after opening a tcpdump session, it stopped working :(

Can you check if that doesn't reset your /etc/hosts file. You should have ::1 localhost to ensure localhost ipv6 gets resolved

**Comment by denil-ct** [comment]
Yup, it still had it. This was the state it was in.
```
::1            localhost
127.0.0.1	localhost
255.255.255.255	broadcasthost
```

**Comment by Fishbowler** [comment]
Fixed in #1439 a long time ago. Oops!
