### ISSUE TITLE
[Maestro version, e.g. v1.30.4] -  Exception in thread while running ui test

### ISSUE THREAD

**Issue by 02gaurav** [mobile-dev-inc/maestro#1304]
**Describe the bug**
Exception while clicking on some button, its asserting visibility correctly. Also, navigation is fine on tapping button. But after tapping on the button got this exception and remaining test cases got stuck.
Exception in thread "pool-4-thread-1" java.io.IOException: Command failed (tcp:7001): closed
	at dadb.adbserver.AdbServer.send$dadb(AdbServer.kt:99)
	at dadb.adbserver.AdbServerDadb.open(AdbServer.kt:138)
	at dadb.forwarding.TcpForwarder.handleForwarding$lambda-1(TcpForwarder.kt:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Expected behavior**
There should not be any exceptions and test cases should not stuck.

Environment information (please complete the following information):

  - Maestro version: [1.30.4]
  - Platform: [Android 11]
  - Framework: [Native Android]
  - Device model and OS version: Android Redmi based on Android 11
  - Host: Mac M1 chip

**Comment by kojofosu** [comment]
Experiencing this as well

**Comment by 02gaurav** [comment]
@kojofosu If you will try Android 12 it is working fine.

**Comment by kojofosu** [comment]
@02gaurav Thank you so much ..i did not get that error after trying with android 12 ....but hopefully we get to know why it failed with android 10 in the future..thanks for your response

**Comment by FilipMaslovaric** [comment]
Still occurring on 1.32.0

**Comment by grpicanco** [comment]
![2023-11-08_11-18](https://github.com/mobile-dev-inc/maestro/assets/51059789/755a570a-ddf8-4115-9283-0e21163deefb)

**Environment information:**

Maestro version: 1.34.0
Platform: Android Orion [8.0]
Device model and OS version: Nexus one api26
Host: Dell G15 i7-11800H - Linux 22.04
