### ISSUE TITLE
I can't run  " maestro test {path of file yaml} " after install Java for iOS Developer

### ISSUE THREAD

**Issue by JARNBOY** [mobile-dev-inc/maestro#135]
I download java because when run `maestro test /Users/paponsupamongkonchai/MaestroYAML/flow_ios_test.yaml` first time log of terminal introduce downlod Java for run command of `maestro` 

Then download and install Java so I run again in terminal  `maestro test /Users/paponsupamongkonchai/MaestroYAML/flow_ios_test.yaml`  it's show this message about version Java not support in Java version 55.0

=======See Log Below=======
```
paponsupamongkonchai@Papons-MacBook-Pro ~ % maestro test /Users/paponsupamongkonchai/MaestroYAML/flow_ios_test.yaml
Exception in thread "main" java.lang.UnsupportedClassVersionError: idb/CompanionServiceGrpc has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at ios.idb.IdbIOSDevice.<init>(IdbIOSDevice.kt:58)
	at maestro.Maestro$Companion.ios(Maestro.kt:291)
	at maestro.Maestro$Companion.ios(Maestro.kt:287)
	at maestro.cli.util.MaestroFactory.createIos(MaestroFactory.kt:58)
	at maestro.cli.util.MaestroFactory.autoDetectPlatform(MaestroFactory.kt:66)
	at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:33)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:58)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:30)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:74)
```

**Comment by JARNBOY** [comment]
I try follow  install it by running `brew install openjdk@11` and try running `brew reinstall openjdk@11` but is show same Exception
`
Exception in thread "main" java.lang.UnsupportedClassVersionError: idb/CompanionServiceGrpc has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

<img width="515" alt="Screen Shot 2565-09-06 at 22 48 32" src="https://user-images.githubusercontent.com/51109993/188679603-898337db-ffda-445a-a909-de1fed895eee.png">

**Comment by dmitry-zaitsev** [comment]
Interesting, could you try `brew install java`?

**Comment by JARNBOY** [comment]
I running `brew install java` is not help me.  result when run  `maestro test /Users/paponsupamongkonchai/MaestroYAML/flow_ios_test.yaml`  show same issue about `version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

<img width="524" alt="Screen Shot 2565-09-06 at 23 10 46" src="https://user-images.githubusercontent.com/51109993/188684314-aaa25da7-4ec1-4f4a-8904-3a836cadd9e9.png">

thank you for support  tomorrow I will try fix again and I will update if I can fix this problem in this issue , But if you have another solution you post in issue I will try it sir haha.

Best regrad.
Papon Supamongkonckonchai (JARNBOY)

**Comment by maciejkrolik** [comment]
I had the same issue and after Java update it worked :) As I can see in the screenshot you are still using Java 8. After executing all the commands above you probably have multiple Java versions installed in the system. Changing the default one should help.

**Comment by JARNBOY** [comment]
@maciejkrolik  You can share step by step to change version java I try follow in stackoverflow but not change default java version.

**Comment by dmitry-zaitsev** [comment]
@JARNBOY happy that it worked for you!
