### ISSUE TITLE
maestro download-samples fails if ~/.maestro/tests directory doesn't exist

### ISSUE THREAD

**Issue by DannyCork** [mobile-dev-inc/maestro#1359]
**Describe the bug**
Following the instructions here https://maestro.mobile.dev/getting-started/run-a-sample-flow
download-samples fails if ~/.maestro/tests directory doesn't already exist

**To Reproduce**
1. Delete the ~/.maestro/tests folder if it already exists.
2. Exectute maestro download-samples
command fails
```
$ maestro download-samples
████████████████████
✅ Samples downloaded to samples/
14:04:10.595 [main] WARN maestro.cli.report.TestDebugReporter - Failed to delete older files
java.nio.file.NoSuchFileException: /Users/x/.maestro/tests
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
	at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base/java.nio.file.Files.walk(Files.java:3918)
	at java.base/java.nio.file.Files.walk(Files.java:3973)
	at maestro.cli.report.TestDebugReporter.deleteOldFiles(TestDebugReporter.kt:76)
	at maestro.cli.report.TestDebugReporter.deleteOldFiles$default(TestDebugReporter.kt:71)
	at maestro.cli.AppKt.main(App.kt:128)
```
It fails as the ~/.maestro/tests directory directory doesn't exist.
```
Directory doesn't exist 
ls -al /Users/x/.maestro/tests
ls: /Users/x/.maestro/tests: No such file or directory
```
**Expected behavior**
1. Check if directory exists first, if not the ~/.maestro/tests directory should be created
2. 'Samples downloaded to samples/' should only be output if no error. Currently this is displayed even if it fails.
3. The text 'Failed to delete older files' is misleading and incorrect.

**Environment information **

- Maestro version: 1.31.0
- Platform: Mac
- Framework: n/a
- Device model and OS version: macbook pro
- Simulator, emulator or physical device: n/a
- Host  Mac M1

**Comment by jemshit** [comment]
Same output after installing and running command `maestro` first time.

**Comment by andre-bahia** [comment]
Same issue here

![Screen Shot 2023-08-21 at 11 30 59](https://github.com/mobile-dev-inc/maestro/assets/25235659/8a4a56b6-2021-4238-a076-67fc34cfc7ca)

Environment:
- Mac OS Monterey
- Version 12.6.8

*Work around*
`cd /Users/your_user/.maestro`

`mkdir tests`

![Screen Shot 2023-08-21 at 11 34 55](https://github.com/mobile-dev-inc/maestro/assets/25235659/0eb8ffc0-09cd-4e4b-8ce4-6ffc469ce6d3)

**Comment by kausikMR** [comment]
works fine after creating a tests directory at home/your_user/.maestro

```
cd home/your_user/.maestro
mkdir tests
```

**Comment by bartekpacia** [comment]
I tried to reproduce this problem now and I failed to do it. Does it still occur to you?

```
$ maestro --version
1.36.0
$ rm -rf ~/.maestro/tests
bartek at Barteks-MacBook in discover_rudy on master
$ maestro download-samples
███████████████████░
✅ Samples downloaded to samples/
```

All good.
