### ISSUE TITLE
[Maestro v1.31.0] Failure when selecting tvOS simulator

### ISSUE THREAD

**Issue by alexmanarpies-dpg** [mobile-dev-inc/maestro#1399]
When I select a tvOS simulator to run with Maestro, the CLI waits for an extended period of time and errors.

**To Reproduce**

1. Start the simulator
2. Run `maestro test`
3. Error is returned after some waiting period:

```
maestro test Profile.yaml

iOS

[1] Apple TV - tvOS 16.4 - E116439E-C0FC-4757-9CD0-27859B2D74C2
[2] iPhone 11 - iOS 16.4 - ABAA80FF-69D2-4442-B53F-7423F0EFE024
[3] iPad Air - iOS 16.4 - A8915E1E-BC26-4279-97C2-FBE505E79DA0
[4] Apple TV 17 - tvOS 17.0 - 3BD01F42-4D5E-433E-997C-33E605B7B977

Web

[5] Chromium Desktop Browser (Experimental)

No running devices detected. Choose a device to boot and run on.

Enter a number from the list above:

1

xcuitest.XCTestDriverClient$XCTestDriverUnreachable: Failed to reach XCUITest Server in restart
	at xcuitest.XCTestDriverClient.restartXCTestRunnerService(XCTestDriverClient.kt:51)
	at ios.xctest.XCTestIOSDevice.open(XCTestIOSDevice.kt:31)
	at ios.LocalIOSDevice.open(LocalIOSDevice.kt:25)
	at maestro.drivers.IOSDriver.open(IOSDriver.kt:76)
	at maestro.Maestro$Companion.ios(Maestro.kt:567)
	at maestro.cli.session.MaestroSessionManager.createIOS(MaestroSessionManager.kt:308)
	at maestro.cli.session.MaestroSessionManager.createMaestro(MaestroSessionManager.kt:153)
	at maestro.cli.session.MaestroSessionManager.access$createMaestro(MaestroSessionManager.kt:49)
	at maestro.cli.session.MaestroSessionManager$newSession$session$1.invoke(MaestroSessionManager.kt:81)
	at maestro.cli.session.MaestroSessionManager$newSession$session$1.invoke(MaestroSessionManager.kt:80)
	at maestro.cli.db.KeyValueStore.withExclusiveLock(KeyValueStore.kt:37)
	at maestro.cli.session.SessionStore.withExclusiveLock(SessionStore.kt:74)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:80)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:57)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:137)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:46)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:126)
```

**Expected behavior**
Maestro test should start.

**Environment information (please complete the following information):**

- Maestro version v1.31.0
- Platform: Apple TV - tvOS 16.4
- Framework: Native tvOS
- Device model and OS version: Apple TV OS 16
- Simulator
- Host Mac M1

**Additional context**

- `maestro studio` exhibits the same behavior.
- I have tried both the tvOS 16 and tvOS 17 beta simulator

**Comment by leandross2** [comment]
Me same behavior

**Comment by felipevolpone** [comment]
@alexmanarpies-dpg the same happens for iPhone simulator?

**Comment by alexmanarpies-dpg** [comment]
> @alexmanarpies-dpg the same happens for iPhone simulator?

No, the iPhone simulator is fine.

**Comment by felipevolpone** [comment]
Good to know, thanks. So I'll close this one as maestro, at least for now, doesn't have plans to support tv or other kind of devices
