### ISSUE TITLE
Exception in thread "pool-4-thread-1, v1.31.0

### ISSUE THREAD

**Issue by itsrahulsah** [mobile-dev-inc/maestro#1412]
I tied to run a long flow, after half of test run I get this :- 
```
Exception in thread "pool-4-thread-1" java.io.IOException: Command failed (host:transport:emulator-5554): device 'emulator-5554' not found
        at dadb.adbserver.AdbServer.send$dadb(AdbServer.kt:99)
        at dadb.adbserver.AdbServerDadb.open(AdbServer.kt:137)
        at dadb.forwarding.TcpForwarder.handleForwarding$lambda-1(TcpForwarder.kt:64)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

host : - Ubuntu 20.04.4 LTS
device:- emulator-5554
verison :- v1.31.0

**Comment by felipevolpone** [comment]
There isn't enough information reported, so can you provide the following?
How long is the flow? Is your app native or it's using RN/Flutter? Which platform (android/ios)? Can you share your app binary and the flow? What's the adb-server status after this error? 
This doesn't seem related to maestro, but with adb connection.

**Comment by didyk** [comment]
@felipevolpone hi! We have react native application and run tests on Android. We have the similar issue on the CI. We have Maestro and Detox and we use Genymotion and only Maestro's tests have next error:

`Exception in thread "pool-4-thread-1" java.io.IOException: Command failed (host:transport:localhost:40001): device 'localhost:40001' not found`


More important, we always have this error when try to do Scroll vertically after Scroll vertically:
<img width="831" alt="image" src="https://github.com/mobile-dev-inc/maestro/assets/15054981/d673ec55-1d40-4fff-93c8-7ed842e71b1d">

**Comment by itsrahulsah** [comment]
@felipevolpone 
app on the native android
[app-binary.zip](https://github.com/mobile-dev-inc/maestro/files/12572624/app-binary.zip)
[readOnly.zip](https://github.com/mobile-dev-inc/maestro/files/12572609/readOnly.zip)

**Comment by kojofosu** [comment]
Having similar issue for lengthy tests



![image](https://github.com/mobile-dev-inc/maestro/assets/20203694/f3501e67-f31c-4de5-9612-57f6a8b66666)

**Comment by bartekpacia** [comment]
I'm having a very similar issue. All I do is run `maestro studio` and leave it running for a few minutes. During that few minutes, I kill and re-run my Flutter app (a few times) and the this exception is thrown.

I'm not sure if it warrants its own issue since the stacktrace is pretty similar.

<details><summary>Crash logs</summary>

```
$ maestro studio
Running on emulator-5554

╭────────────────────────────────────────────────────────╮
│                                                        │
│   Maestro Studio is running at http://localhost:9999   │
│                                                        │
╰────────────────────────────────────────────────────────╯


Tip: Maestro Studio can now run simultaneously alongside other Maestro CLI commands!

Navigate to http://localhost:9999 in your browser to open Maestro Studio. Ctrl-C to exit.

Exception in thread "pool-4-thread-1" java.io.IOException: Command failed (host:transport:emulator-5554): device offline
	at dadb.adbserver.AdbServer.send$dadb(AdbServer.kt:99)
	at dadb.adbserver.AdbServerDadb.open(AdbServer.kt:137)
	at dadb.forwarding.TcpForwarder.handleForwarding$lambda-1(TcpForwarder.kt:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
maestro.MaestroException$DriverTimeout: Android driver unreachable
	at maestro.drivers.AndroidDriver.runDeviceCall(AndroidDriver.kt:933)
	at maestro.drivers.AndroidDriver.deviceInfo(AndroidDriver.kt:154)
	at maestro.ViewHierarchy$Companion.from-c1iYVAs(ViewHierarchy.kt:28)
	at maestro.Maestro.viewHierarchy-prqvCes(Maestro.kt:412)
	at maestro.studio.DeviceService.getDeviceScreen(DeviceService.kt:172)
	at maestro.studio.DeviceService.access$getDeviceScreen(DeviceService.kt:43)
	at maestro.studio.DeviceService$routes$3$1.invokeSuspend(DeviceService.kt:82)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

</details> 

<details><summary>Environment</summary>

MacBook Air M1, macOS Sonoma
Android emulator version 33.1.13.0 (build_id 10332831)
OS image: `system-images;android-31;google_apis;arm64-v8a`, revision 11
Maestro 1.34.1
</details>

**Comment by DavidREntwistle** [comment]
A bit of an [update](https://github.com/mobile-dev-inc/Maestro/issues/1525#issuecomment-2624398250) on this issue, I can manually reproduce this issue.
It would be really good if Maestro CLI could attempt to Restart ADB Server and then recover the Android device connection, rather than attempting to run every flow with the same error for ~6 minutes each.
