### ISSUE TITLE
How to run the adb shell command 

### ISSUE THREAD

**Issue by kuldeep04** [mobile-dev-inc/maestro#1507]
trying to run the shell command with javascript but its failing.

js Code: 

```
import exec from 'child_process';
exec('adb shell input text "123456"');
```

yaml file:
```

appId: "com.test.stock.debug"
---
- launchApp
- tapOn: "Continue with gmail"
- tapOn: "0000000000"
- inputText: "mobileNumber"
- tapOn: "PROCEED"
- runScript: scripts/shell.js
```

exception which i'm getting:

```
org.mozilla.javascript.EvaluatorException: missing ; before statement (scripts/shell.js#1)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:79)
	at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:66)
	at org.mozilla.javascript.Parser.addError(Parser.java:257)
	at org.mozilla.javascript.Parser.reportError(Parser.java:336)
	at org.mozilla.javascript.Parser.reportError(Parser.java:327)
	at org.mozilla.javascript.Parser.reportError(Parser.java:320)
	at org.mozilla.javascript.Parser.autoInsertSemicolon(Parser.java:1279)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1254)
	at org.mozilla.javascript.Parser.statement(Parser.java:1104)
	at org.mozilla.javascript.Parser.parse(Parser.java:632)
	at org.mozilla.javascript.Parser.parse(Parser.java:562)
	at org.mozilla.javascript.Context.parse(Context.java:2470)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2401)
	at org.mozilla.javascript.Context.compileString(Context.java:1369)
	at org.mozilla.javascript.Context.compileString(Context.java:1357)
	at org.mozilla.javascript.Context.evaluateString(Context.java:1135)
	at maestro.js.RhinoJsEngine.evaluateScript(RhinoJsEngine.kt:109)
	at maestro.orchestra.Orchestra.runScriptCommand(Orchestra.kt:340)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:279)
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:209)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:119)
	at maestro.orchestra.Orchestra.runFlow$default(Orchestra.kt:83)
	at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:185)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:54)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:51)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:145)
	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:51)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:177)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:136)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:101)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:58)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:136)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:46)
	at picocli.CommandLine.execute
[2023-10-04_144042.zip](https://github.com/mobile-dev-inc/maestro/files/12802614/2023-10-04_144042.zip)
[2023-10-04_163255.zip](https://github.com/mobile-dev-inc/maestro/files/12802615/2023-10-04_163255.zip)
[2023-10-04_163453.zip](https://github.com/mobile-dev-inc/maestro/files/12802616/2023-10-04_163453.zip)
[2023-10-04_163827.zip](https://github.com/mobile-dev-inc/maestro/files/12802617/2023-10-04_163827.zip)
[2023-10-04_164025.zip](https://github.com/mobile-dev-inc/maestro/files/12802618/2023-10-04_164025.zip)
[2023-10-04_164245.zip](https://github.com/mobile-dev-inc/maestro/files/12802619/2023-10-04_164245.zip)
UserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:117)


==== Debug output (logs & screenshots) ====
```

**Comment by igorsmotto** [comment]
Hi @kuldeep04 

Right now our JS engine does not allow import of any library. As such, you won't be able to use the `exec` function.

Mind sharing why are you trying to use adb to input text if Maestro already has the inputText command?

**Comment by kuldeep04** [comment]
@igorsmotto want to input in a edit text field that dont have id, content-desc etc. does maestro supports xpath if yes please share syntax how I can do that.

**Comment by kuldeep04** [comment]
@igorsmotto is there any way to open keyBoard in maestro, that will also help me.

Was tried this but its failing:

test code:

```
appId: "com.text.stock.debug"
---
- launchApp
- tapOn: "Continue with gmail"
- tapOn: "0000000000"
- inputText: "mobileNumber"
- tapOn: "PROCEED"
- runFlow: "inputOtp.yaml"
```

inputOtp.yaml code:

```
appId: "com.google.android.inputmethod.latin"

---
- launchApp
- tapOn: "com.google.android.inputmethod.latin:id/key_pos_number_line1_1"
- tapOn: "com.google.android.inputmethod.latin:id/key_pos_number_line1_1"
- tapOn: "com.google.android.inputmethod.latin:id/key_pos_number_line1_1"
- tapOn: "com.google.android.inputmethod.latin:id/key_pos_number_line1_1"
- tapOn: "com.google.android.inputmethod.latin:id/key_pos_number_line1_1"
```

**Comment by igorsmotto** [comment]
> want to input text in a edit text field that don't have id, content-desc etc. does maestro supports xpath if yes please share syntax.

You could try tapping to a specific coordinate:
https://maestro.mobile.dev/api-reference/commands/tapon#tapping-on-a-specific-point-on-the-screen

> is there any way to open keyBoard in maestro, that will also help me.

No, only hiding the keyBoard.

**Comment by igorsmotto** [comment]
If you use relative position no, for example:
"90%,50%"

**Comment by ram95krishh** [comment]
Hi Igor. I need extensive use of imports to do some background checks in the middle of my tests, like check for a account verification email in a 1secmail inbox, and pick a link from it using libraries like JSdom. Is Maestro gonna support imports anytime soon? @igorsmotto

**Comment by felipevolpone** [comment]
We don't have plans for that yet @ram95krishh

**Comment by Pierre-Monier** [comment]
I would like to test my app's deep linking by running a command like `xcrun simctl openurl booted myApp://my.app/myScreen`. But since it looks like we can't run bash command out of the box, and we can't run bash command with js because the js engine does not handle imports, the only solution I see is launching a web server to execute my bash commands, like [this example ](https://gist.github.com/dansimau/6657920a51c83212ebff929f85b5d309). But this is not ideal.

So I wonder if there is another way ? Or if maybe my use case highlight some needs to be able to run bash commands.
