### ISSUE TITLE
[v1.33.1] Exception in thread "main" java.nio.file.NoSuchFileException - Debug output

### ISSUE THREAD

**Issue by DavidREntwistle** [mobile-dev-inc/maestro#1522]
**Describe the bug**
After a successful flow run of 72 flows on Android, the following exception displayed:
`Exception in thread "main" java.nio.file.NoSuchFileException: /Users/myuser/Library/Logs/maestro/2023-10-11_101531`

**To Reproduce**
1. Complete a 72 flows on Android emulator
2. Observe the exception display below the Debug output (logs & screenshots)

**Expected behavior**
No exception to be thrown in the debug output.

**Screenshots**
![Screenshot 2023-10-11 at 11 12 01](https://github.com/mobile-dev-inc/maestro/assets/17282021/f620c663-ccc7-4a88-9e73-194adf18ae0c)

**Environment information (please complete the following information):**
- Maestro version [v1.33.1]
- Android 13.0
- Framework: [Android]
- Google Pixel 4 - Google Play services 
- Android Emulator 
- Host [Apple MacBook Pro M2 Max]

**Additional context**
```
==== Debug output (logs & screenshots) ====

/Users/myuser/.maestro/tests/2023-10-11_101531
Exception in thread "main" java.nio.file.NoSuchFileException: /Users/myuser/Library/Logs/maestro/2023-10-11_101531
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
	at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base/java.nio.file.Files.walk(Files.java:3918)
	at java.base/java.nio.file.Files.walk(Files.java:3973)
	at maestro.utils.FileUtils.zipDir(FileUtils.kt:26)
	at maestro.debuglog.DebugLogStore.finalizeRun(DebugLogStore.kt:91)
	at maestro.cli.AppKt.main(App.kt:119)
```

**Comment by yonaskolb** [comment]
Not sure if it's at all related, but I ran into this myself and found it was because I had changed the timezone on my mac to test the flows in different timezones. Reseting my timezone to auto fixed this.

**Comment by ice-cap0** [comment]
encountering this as well
