### ISSUE TITLE
[v1.33.1] maestro.drivers.AndroidDriver - Failed to get view hierarchy

### ISSUE THREAD

**Issue by ARESBAN** [mobile-dev-inc/maestro#1537]
**Describe the bug**
When testing a web page (developed with Next.js) on the Android Chrome browser, I often encounter the following error message in maestro.log file.

**To Reproduce**

1. Start the AVD emulator
2. Run flow on Maestro CLI
3. check  maestro.log 

**Screenshots**
```
[ERROR] maestro.drivers.AndroidDriver - Failed to get view hierarchy
io.grpc.StatusRuntimeException: UNKNOWN
    at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
    at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
    at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
    at maestro_android.MaestroDriverGrpc$MaestroDriverBlockingStub.viewHierarchy(MaestroDriverGrpc.java:641)
    at maestro.drivers.AndroidDriver.contentDescriptor(AndroidDriver.kt:237)
    at maestro.ViewHierarchy$Companion.from-c1iYVAs(ViewHierarchy.kt:29)
    at maestro.Maestro.viewHierarchy-prqvCes(Maestro.kt:405)
    at maestro.Maestro$findElementWithTimeout$element$1.invoke(Maestro.kt:430)
    at maestro.Maestro$findElementWithTimeout$element$1.invoke(Maestro.kt:429)
    at maestro.utils.MaestroTimer.withTimeout(MaestroTimer.kt:16)
    at maestro.Maestro.findElementWithTimeout(Maestro.kt:429)
    at maestro.orchestra.Orchestra.findElement(Orchestra.kt:836)
    at maestro.orchestra.Orchestra.access$findElement(Orchestra.kt:52)
    at maestro.orchestra.Orchestra$evaluateCondition$3$result$1.invoke(Orchestra.kt:515)
    at maestro.orchestra.Orchestra$evaluateCondition$3$result$1.invoke(Orchestra.kt:513)
    at maestro.utils.MaestroTimer.withTimeout(MaestroTimer.kt:16)
    at maestro.orchestra.Orchestra.evaluateCondition(Orchestra.kt:513)
    at maestro.orchestra.Orchestra.evaluateCondition$default(Orchestra.kt:490)
    at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:483)
    at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:275)
    at maestro.orchestra.Orchestra.executeSubflowCommands(Orchestra.kt:575)
    at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:612)
    at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:484)
    at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:275)
    at maestro.orchestra.Orchestra.executeSubflowCommands(Orchestra.kt:575)
    at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:612)
    at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:484)
    at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:275)
    at maestro.orchestra.Orchestra.executeSubflowCommands(Orchestra.kt:575)
    at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:612)
    at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:484)
    at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:275)
    at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:209)
    at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:119)
    at maestro.orchestra.Orchestra.runFlow$default(Orchestra.kt:83)
    at maestro.cli.runner.TestSuiteInteractor.runFlow(TestSuiteInteractor.kt:210)
    at maestro.cli.runner.TestSuiteInteractor.runTestSuite(TestSuiteInteractor.kt:69)
    at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:152)
    at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:136)
    at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:101)
    at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:58)
    at maestro.cli.command.TestCommand.call(TestCommand.kt:136)
    at maestro.cli.command.TestCommand.call(TestCommand.kt:46)
    at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
    at picocli.CommandLine.access$1200(CommandLine.java:145)
    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
    at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
    at picocli.CommandLine.execute(CommandLine.java:2058)
    at maestro.cli.AppKt.main(App.kt:117)
```

**Environment information (please complete the following information):**

- Maestro version : v1.33.1
- Platform: Android 13, Chrome
- Framework: Webview(Next.js)
- Emulator
- Host MacBookPro M1pro

**Comment by bartekpacia** [comment]
Hey, thanks for creating this issue! Unfortunately, it's not reproducible to us.

Please provide a [minimal, reproducible example] that clearly explains how to reproduce the problem with the detailed, step-by-step instructions (that can be easily run by me or other maintainers).

This issue does not contain such an example, therefore I'm going to reluctantly close it.

If you don't have time right now, that's totally OK. Feel free to open a new issue in the future with all the required information provided.

[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
