### ISSUE TITLE
[BUG] - Exception in thread "pool-4-thread-1" java.io.IOException: Command failed (host:transport:emulator-5554): device offline [Maestro version, e.g. v1.34.0]

### ISSUE THREAD

**Issue by talhaoz** [mobile-dev-inc/maestro#1573]
When running short operations maestro is running fine. Even I run all the commands seperately its working without an issue. But once I combine the tests it always fails with this exception : 

```
Exception in thread "pool-4-thread-1" java.io.IOException: Command failed (host:transport:emulator-5554): device offline
        at dadb.adbserver.AdbServer.send$dadb(AdbServer.kt:99)
        at dadb.adbserver.AdbServerDadb.open(AdbServer.kt:137)
        at dadb.forwarding.TcpForwarder.handleForwarding$lambda-1(TcpForwarder.kt:64)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```

It somehow mentions the current emulator offline and not moving forward. I check if the emulator is still online and connected and it was there. 

After throwing this adb disconnected exception it also throws this one : 

![image](https://github.com/mobile-dev-inc/maestro/assets/21693899/0944faac-8c7d-42bd-b6f6-caa10016ded6)

**To Reproduce**

1. Start the simulator
2. Run `maestro test ...`
3. The Flow fails after running like 4 min. 

**Expected behavior**
Working as expected and not fails. 

**Screenshots**

**Environment information (please complete the following information):**

- Maestro version: v1.34.0
- Platform: Android API 30
- Framework: Native Android
- Device model and OS version: Pixel
- Emulator
- Host: Mac M1

**Workspace (if applicable)**
Please share your workspace with Flow files and application binary if you are able to do so as that greatly helps in reproduction efforts.

**Bugreport output (if applicable)**
The zip files created when `maestro bugreport` can be uploaded here as well if applicable.

**Additional context**

**Comment by talhaoz** [comment]
Sometime It throws this error : `Android driver unreachable`

**Comment by snitsaruk** [comment]
@talhaoz have you found a solution for this?

**Comment by DavidREntwistle** [comment]
I have been able to reproduce steps for this here: https://github.com/mobile-dev-inc/maestro/issues/1525#issuecomment-1889192728

**Comment by yuseiatlas** [comment]
A temporary fix that worked for me was to set the emulator's API level to 32. We had it set to 30 when the issue started showing. I tried 31, 33, and 34; however, none worked. Nonetheless, this issue has been surfacing on different threads since August with no fix or temporary workaround from the Maestro team 😞

**Comment by ubuntudroid** [comment]
> A temporary fix that worked for me was to set the emulator's API level to 32. We had it set to 30 when the issue started showing. I tried 31, 33, and 34; however, none worked. Nonetheless, this issue has been surfacing on different threads since August with no fix or temporary workaround from the Maestro team 😞

Interestingly, 32 is explicitly included from supported API levels when running `maestro start-device`. I'm wondering why. 🤔

**Comment by ubuntudroid** [comment]
Shot in the dark: Maybe those issues are related to running maestro on arm hardware (e.g., M* Macs)?

**Comment by exodus98** [comment]
Hello,
I'm running maestro on i9 Macbook Pro 2019 and api-32 emulator, but this happens very often. 😞

**Comment by dsolerli** [comment]
Hello, has anyone managed to resolve this issue? I'm encountering the same error when running Maestro in a CI pipeline. The environment is a Kubernetes pod running Ubuntu, and the error only occurs during Maestro test execution. We've attempted to increase both the RAM and CPU cores allocated to the emulated devices, but it hasn't made a difference. Interestingly, it seems to work exclusively with API level 32, while failing for other API levels.

**Comment by ecorreyu** [comment]
Same issue here, any idea?

**Comment by DavidREntwistle** [comment]
A bit of an [update](https://github.com/mobile-dev-inc/Maestro/issues/1525#issuecomment-2624398250) on this issue, I can manually reproduce this issue.
It would be really good if Maestro CLI could attempt to Restart ADB Server and then recover the Android device connection, rather than attempting to run every flow with the same error for ~6 minutes each.
