### ISSUE TITLE
[Maestro version, e.g. v2.1.0]

### ISSUE THREAD

**Issue by vishalsaini26** [mobile-dev-inc/maestro#1764]
**Describe the bug**
While clicking on a button there is a loader after which success screen should appear. Screen is getting stuck on loader with error

Error: Request for viewHierarchy failed, because of unknown reason, body: {"errorMessage":"XCTPerformOnMainRunLoop work timed out after 60.0s","code":"internal"}
Exception in thread "main" UnknownFailure(errorResponse=Request for viewHierarchy failed, code: 500, body: {"errorMessage":"XCTPerformOnMainRunLoop work timed out after 60.0s","code":"internal"})
        at xcuitest.XCTestDriverClient.handleExceptions(XCTestDriverClient.kt:310)
        at xcuitest.XCTestDriverClient.processResponse(XCTestDriverClient.kt:258)
        at xcuitest.XCTestDriverClient.executeJsonRequest(XCTestDriverClient.kt:240)
        at xcuitest.XCTestDriverClient.viewHierarchy(XCTestDriverClient.kt:72)
        at ios.xctest.XCTestIOSDevice$viewHierarchy$1.invoke(XCTestIOSDevice.kt:40)
        at ios.xctest.XCTestIOSDevice$viewHierarchy$1.invoke(XCTestIOSDevice.kt:38)
        at ios.xctest.XCTestIOSDevice.execute(XCTestIOSDevice.kt:227)
        at ios.xctest.XCTestIOSDevice.viewHierarchy(XCTestIOSDevice.kt:38)
        at ios.LocalIOSDevice.viewHierarchy(LocalIOSDevice.kt:47)
        at maestro.drivers.IOSDriver.viewHierarchy(IOSDriver.kt:147)
        at maestro.drivers.IOSDriver.access$viewHierarchy(IOSDriver.kt:41)
        at maestro.drivers.IOSDriver$contentDescriptor$1.invoke(IOSDriver.kt:142)
        at maestro.drivers.IOSDriver$contentDescriptor$1.invoke(IOSDriver.kt:142)
        at maestro.drivers.IOSDriver.runDeviceCall(IOSDriver.kt:485)
        at maestro.drivers.IOSDriver.contentDescriptor(IOSDriver.kt:142)
        at maestro.ViewHierarchy$Companion.from-8JJjmZI(ViewHierarchy.kt:29)
        at maestro.utils.ScreenshotUtils$Companion.viewHierarchy-c1iYVAs(ScreenshotUtils.kt:99)
        at maestro.utils.ScreenshotUtils$Companion.waitForAppToSettle-OpTFbEc(ScreenshotUtils.kt:58)
        at maestro.drivers.IOSDriver.waitForAppToSettle-5RpGHs4(IOSDriver.kt:424)
        at maestro.Maestro.waitForAppToSettle-5RpGHs4(Maestro.kt:468)
        at maestro.Maestro.waitForAppToSettle-5RpGHs4$default(Maestro.kt:463)
        at maestro.Maestro.screenshotBasedTap-hbl3e4M(Maestro.kt:308)
        at maestro.Maestro.performTap-hbl3e4M(Maestro.kt:277)
        at maestro.Maestro.tap-BUbHBYE(Maestro.kt:189)
        at maestro.orchestra.Orchestra.tapOnElement(Orchestra.kt:753)
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:239)
        at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:201)
        at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:111)
        at maestro.orchestra.Orchestra.runFlow$default(Orchestra.kt:75)
        at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:185)
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:54)
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:51)
        at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:145)
        at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:51)
        at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:177)
        at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:136)
        at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:101)
        at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:58)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:136)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:46)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at maestro.cli.AppKt.main(App.kt:117)

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Start the simulator
2. Run `maestro test ...`
3. The Flow fails at ...

**Expected behavior**

**Screenshots**

**Environment information (please complete the following information):**

- Maestro version [e.g. v1.2.3]
- Platform: [e.g. iOS 16.4.1, Android 11.0, Chrome]
- Framework: [Native iOS/Android, Flutter, React Native, etc]
- Device model and OS version: [e.g. iPhone6]
- Simulator, emulator or physical device
- Host [e.g. Mac M1, Windows, Linux, etc]

**Workspace (if applicable)**
Please share your workspace with Flow files and application binary if you are able to do so as that greatly helps in reproduction efforts.

**Bugreport output (if applicable)**
The zip files created when `maestro bugreport` can be uploaded here as well if applicable.

**Additional context**

**Comment by bartekpacia** [comment]
Closing as not reproducible.
