### ISSUE TITLE
Maestro iOS/Android driver startup failures

### ISSUE THREAD

**Issue by prasanta-biswas** [mobile-dev-inc/maestro#1776]
**Describe the bug**
Maestri iOS driver fails to start when flows are run in parallel using the shards parameter. This is happening very frequently.

**To Reproduce**
Run multiple flows in parallels using shards param > 3 and having more than 3 simulator running

1. Start three simulators/emulators
2. Run `maestro test flows/ --shards=3`
3. The Flow fails during maestro iOS/Android driver startup

**Expected behavior**
It should successfully start tests on all three simulators/emulators

**Environment information (please complete the following information):**

- Maestro version : Running from main branch
- Platform: iOS17.2/Android 13
- Framework: Native iOS/ Native Android
- Device model and OS version:  iPhone simulators and Android Emulators
- Host: Mac M1

**Stacktrace**
`
kotlinx.coroutines.JobCancellationException: BlockingCoroutine is cancelling; job=BlockingCoroutine{Cancelling}@16391dcb
Caused by: maestro.MaestroDriverStartupException$IOSDriverTimeoutException: Maestro iOS driver did not start up in time
	at maestro.drivers.IOSDriver.awaitLaunch(IOSDriver.kt:494)
	at maestro.drivers.IOSDriver.open(IOSDriver.kt:64)
	at maestro.Maestro$Companion.ios(Maestro.kt:610)
	at maestro.cli.session.MaestroSessionManager.createIOS(MaestroSessionManager.kt:329)
	at maestro.cli.session.MaestroSessionManager.createMaestro(MaestroSessionManager.kt:162)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:87)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:58)
	at maestro.cli.command.TestCommand$handleSessions$1$1$results$1$1.invokeSuspend(TestCommand.kt:245)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
`

**Comment by prasanta-biswas** [comment]
@sdfgsdfgd please take a look at this

**Comment by prasanta-biswas** [comment]
iOS driver failure got resolved after building the maestro-driver-ios.xcodeproj separately. Android issue is still reproducible.

**Comment by sdfgsdfgd** [comment]
just wait for the next release, you're probably doing something wrong with the server or CLI rebuild on your codebase. 

there is nothing wrong with sharding lol

**Comment by prasanta-biswas** [comment]
You might be right 😁

**Comment by bartekpacia** [comment]
Hey guys, thanks for taking time to create the issue and share knowledge.

From what I understand, rebuilding the binaries (both for Android and iOS) fixed the issue, right? If yes then can we close it?

**Comment by prasanta-biswas** [comment]
@bartekpacia yes it is fixed. You can close the issue.
