### ISSUE TITLE
gRPC UNKNOWN exception when running Maestro on Android

### ISSUE THREAD

**Issue by dmitry-zaitsev** [mobile-dev-inc/maestro#179]
```
io.grpc.StatusRuntimeException: UNKNOWN                 
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)                                                      
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at maestro_android.MaestroDriverGrpc$MaestroDriverBlockingStub.viewHierarchy(MaestroDriverGrpc.java:270)                        
        at maestro.drivers.AndroidDriver.contentDescriptor(AndroidDriver.kt:205)
        at maestro.ViewHierarchy$Companion.from-c1iYVAs(ViewHierarchy.kt:28)
        at maestro.Maestro.viewHierarchy-prqvCes(Maestro.kt:228)
        at maestro.orchestra.Orchestra.findElement(Orchestra.kt:257)
        at maestro.orchestra.Orchestra.findElement$default(Orchestra.kt:243)
        at maestro.orchestra.Orchestra.tapOnElement(Orchestra.kt:216)
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:120)
        at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:107)
        at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:69)
        at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:98)                                              
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:32)                                                    
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:29)                                                    
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:116)
	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:29)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:60)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:30)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:74)
```

**Comment by dmitry-zaitsev** [comment]
Same issue as #178
