### ISSUE TITLE
`addMedia` causes crash on Android API 28

### ISSUE THREAD

**Issue by bartekpacia** [mobile-dev-inc/maestro#1821]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

1. Clone [example app](https://github.com/bartekpacia/demo_app)
2. Create Android emulator with API 28
3. 

### Actual results

`addMedia` causes a crash and the flow fails.

### Expected results

`addMedia` works and doesn't crash.

### About app

n/a (does not matter in this context)

### About environment

M1 MacBook Air, macOS 14.5 Sonoma

### Logs

<details>
<summary>Logs</summary>

```
$ maestro test .maestro/issue1706.yaml
Running on emulator-5554
io.grpc.StatusRuntimeException: UNKNOWN
    at io.grpc.Status.asRuntimeException(Status.java:539)
    at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
    at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
    at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)


==== Debug output (logs & screenshots) ====

/Users/bartek/.maestro/tests/2024-07-23_123419
```

</details>

### Maestro version

1.36.0

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

**Comment by ABogdanovas** [comment]
The same issue occurs with Android API levels below 29.
