### ISSUE TITLE
Unable to start maestro on latest CLI

### ISSUE THREAD

**Issue by radiodario** [mobile-dev-inc/maestro#1842]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

1. install maestro via `curl -Ls https://get.maestro.mobile.dev/`
2. Run maestro suite
3. Tests fail to start due to missing `sessions` folder 

### Actual results

Tests fail to start, a java error reporting that `~/.maestro/sessions` doesn't exist is thrown

### Expected results

Tests were being run correctly on CI until 1.37.2 was released two hours ago.

### About app

- App is closed source React Native 0.73.4 (unrelated) - cannot provide binary

### About environment

Bitrise CI M1

### Logs

<details>
<summary>Logs</summary>

```
+ maestro -v
Maestro CLI would like to collect anonymous usage data to improve the product.
Enable analytics? [Y/n] Usage data collection disabled.
1.37.2
+ xcrun simctl install booted /var/folders/7l/XXXXX/T/_artifact_pull301532640/XXXX.app
+ '[' 1 ']'
+ maestro test e2e/experimental --format junit --output /Users/vagrant/deploy/test_report.xml -e APP_ID=APPID --debug-output /Users/vagrant/deploy
+ xcrun simctl io booted recordVideo --codec=h264 -f /Users/vagrant/deploy/ui_tests.mp4
IOServiceMatchingfailed for: AppleM2ScalerCSCDriver
Recording started
❌ Error: BlockingCoroutine is cancelling
kotlinx.coroutines.JobCancellationException: BlockingCoroutine is cancelling; job=BlockingCoroutine{Cancelling}@162a1d67
Caused by: java.io.FileNotFoundException: /Users/vagrant/.maestro/sessions (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at kotlin.io.FilesKt__FileReadWriteKt.forEachLine(FileReadWrite.kt:190)
	at kotlin.io.FilesKt__FileReadWriteKt.readLines(FileReadWrite.kt:219)
	at kotlin.io.FilesKt__FileReadWriteKt.readLines$default(FileReadWrite.kt:217)
	at maestro.cli.db.KeyValueStore.getCurrentDB(KeyValueStore.kt:29)
	at maestro.cli.db.KeyValueStore.keys(KeyValueStore.kt:25)
	at maestro.cli.session.SessionStore.activeSessions(SessionStore.kt:55)
	at maestro.cli.session.SessionStore.hasActiveSessions(SessionStore.kt:68)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:89)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:58)
	at maestro.cli.command.TestCommand$handleSessions$1$1$results$1$1.invokeSuspend(TestCommand.kt:249)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
exit status 1
```

</details>

### Maestro version

1.32.7

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

### Anything else?

Thank you

**Comment by radiodario** [comment]
Workaround, set `export MAESTRO_VERSION=1.37.1` on your environment

**Comment by amanjeetsingh150** [comment]
Hey @radiodario 1.37.1 is the latest version, not sure how is setting that version is workaround 🤔 ?

**Comment by radiodario** [comment]
> Hey @radiodario 1.37.1 is the latest version, not sure how is setting that version is workaround 🤔 ?

latest is [1.37.2](https://github.com/mobile-dev-inc/maestro/releases/tag/cli-1.37.2) but actually had to revert back to 1.36.0

**Comment by bartekpacia** [comment]
Thanks for the report. We're on it, hotfix coming today.

**Comment by radiodario** [comment]
this works:

```
  mkdir -p ~/.maestro
  rm -f ~/.maestro/sessions ; touch ~/.maestro/sessions
  # install maestro from CLI
```
