### ISSUE TITLE
Unable to find compatible `cmdline-tools` for java version 21

### ISSUE THREAD

**Issue by 7maucdn** [mobile-dev-inc/maestro#1852]
After upgrade to 1.37.4 from 1.36.0, i can't run my test, it's raise error : 

```
------------------ Shard 1 ------------------

Please specify a device platform [android, ios, web]:
android

Please specify Android version [34, 33, 31, 30, 29, 28]: Press ENTER for default (30)
34

❌ Error: BlockingCoroutine is cancelling
kotlinx.coroutines.JobCancellationException: BlockingCoroutine is cancelling; job=BlockingCoroutine{Cancelling}@5cf84f7e
Caused by: maestro.cli.CliError: Unable to find compatible cmdline-tools (/root/Android/cmdline-tools/<version>) for java version 21.

Try to install a different cmdline-tools version:
1) Open Android Studio SDK manager
2) Check "Show package details" to show all versions
3) Install Android SDK Command-Line Tools. Recommended version: latest
* https://developer.android.com/studio/intro/update#sdk-manager
        at maestro.cli.util.AndroidEnvUtils.requireCommandLineTools(AndroidEnvUtils.kt:74)
        at maestro.cli.device.DeviceService.requireAvdManagerBinary(DeviceService.kt:465)
        at maestro.cli.device.DeviceService.getAvailablePixelDevices(DeviceService.kt:348)
        at maestro.cli.device.DeviceCreateUtil.getOrCreateAndroidDevice(DeviceCreateUtil.kt:99)
        at maestro.cli.device.DeviceCreateUtil.getOrCreateDevice(DeviceCreateUtil.kt:16)
        at maestro.cli.command.TestCommand$handleSessions$1$1$results$1$1.invokeSuspend(TestCommand.kt:228)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by Ekt0s** [comment]
Same here, I can't run the test anymore with the last update

**Comment by bartekpacia** [comment]
Hey @7maucdn, sorry for the problems. Before we can resolve this issue we need more info though. Could you run these and share output with us?

```
java -version
```

and

```
$ANDROID_HOME/cmdline-tools/latest/source.properties
```

(in your case that'll be `/root/Android/cmdline-tools/latest/source.properties`

**Comment by bartekpacia** [comment]
@7maucdn, did you try the suggestion that is in the error message you posted? That is, update to latest Android command-line tools?

**Comment by tutanjamon2020** [comment]
Hello. I'm having the same issue:

❌ Error: BlockingCoroutine is cancelling
kotlinx.coroutines.JobCancellationException: BlockingCoroutine is cancelling; job=BlockingCoroutine{Cancelling}@9966508
Caused by: maestro.cli.CliError: Unable to find compatible cmdline-tools (/home/XXXXX/Android/cmdline-tools/<version>) for java version 21.

~/samples$ java -version
openjdk version "21.0.4" 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu222.04, mixed mode, sharing)

~/samples$ $ANDROID_HOME/cmdline-tools/latest/source.properties
/home/XXX/Android/cmdline-tools/latest/source.properties: line 1: Pkg.Revision=12.0: command not found
/home/XXX/Android/cmdline-tools/latest/source.properties: line 2: Pkg.Path=cmdline-tools: command not found
/home/XXX/Android/cmdline-tools/latest/source.properties: line 2: 12.0: command not found
/home/XXX/Android/cmdline-tools/latest/source.properties: line 3: Pkg.Desc=Android: command not found

**Comment by Ekt0s** [comment]
@7maucdn @bartekpacia the problem was coming from the file tree on my part. 

I solved it by just updating the `cmdline-tools` package using the SDK wizard in Android Studio.
**The latest version "16.0.0-rc1" fixes the issue** 😃

**Comment by tutanjamon2020** [comment]
Hi team. I have spent 4 days trying to do the initial configuration of Maestro. Quite frustrating experience.

I have not been able to solve it with any version of Java, nor with any version of cmd-line tool.

I currently have installed:
Java Version: openjdk version "21.0.4" 2024-07-16.
Command-Line Tool: Latest (16.0.0 rc1)

Error:
kotlinx.coroutines.JobCancellationException: BlockingCoroutine is canceling; job=BlockingCoroutine{Cancelling}@3fa0c421
Caused by: maestro.cli.CliError: Unable to find compatible cmdline-tools (/home/damianaz/Android/cmdline-tools/<version>) for java version 21.

Try to install a different cmdline-tools version:
1) Open Android Studio SDK manager
2) Check "Show package details" to show all versions
3) Install Android SDK Command-Line Tools. Recommended version: latest
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

I don't know what else to do.

**Comment by HAL9000Thomas** [comment]
Experienced the same issue after upgrading to the latest version. Installing cmdline-tools seems to be not enough to fix the issue. My colleague also had this issue on his machine. Downgrading to CLI 1.34.1 worked for me.

**Comment by ggetorres** [comment]
Can anyone help with this error?


❌ Error: BlockingCoroutine is cancelling
kotlinx.coroutines.JobCancellationException: BlockingCoroutine is cancelling; job=BlockingCoroutine{Cancelling}@2973afa0
Caused by: maestro.cli.CliError: Unable to start device: Maestro_Pixel_6_API_31_1
        at maestro.cli.device.DeviceService.startDevice(DeviceService.kt:74)
        at maestro.cli.command.TestCommand$handleSessions$1$1$results$1$1.invokeSuspend(TestCommand.kt:237)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by bartekpacia** [comment]
Hey all – could you update your comments with more information?

The following will help debug:

```
cat $ANDROID_HOME/cmdline-tools/latest/source.properties
```

(Make sure you have $ANDROID_HOME env var properly set up)

And attach output of `java -version`.
