### ISSUE TITLE
Unable to run parallel/sharded tests on Android

### ISSUE THREAD

**Issue by simon-gilmurray** [mobile-dev-inc/maestro#1853]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

It always fail except for on one device when running Android in parallel. Things I've tried:
- Creating devices from Maestro CLI and using them
- Using Android Studio created devices
- Calling a basic command `maestro test --shards 3 maestro/`
- Passing in explicit device names `maestro --device 'emulator-5554,emulator-5556,emulator-5558' test -s 3 maestro/ `

### Actual results

Only one device seems to run, 2/3 of the tests appear to fail straight away with 0s:

<img width="929" alt="Screenshot 2024-07-30 at 11 57 37" src="https://github.com/user-attachments/assets/9aecd386-1e6f-4752-a180-51e4dbd8c3b2">

Logs:

```
[ERROR] m.cli.runner.TestSuiteInteractor - Failed to complete flow
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
    at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
    at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
    at maestro_android.MaestroDriverGrpc$MaestroDriverBlockingStub.deviceInfo(MaestroDriverGrpc.java:634)
...
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:7006
Caused by: java.net.ConnectException: Connection refused
```
[maestro.log](https://github.com/user-attachments/files/16430851/maestro.log)

### Expected results

Tests should run in parallel, as they do on iOS which is working fine

### About app

React Native

### About environment

macOS Sonoma 14.4.1 M2 Pro

### Logs

<details>
<summary>Logs</summary>

```
[maestro.log](https://github.com/user-attachments/files/16430871/maestro.log)
```

</details>

### Maestro version

1.37.4

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

### Anything else?

Slack thread:

https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1722341761341199

**Comment by bartekpacia** [comment]
I did reproduce this problem. I started 2 emulators (API33 and API34), tests on one of them immediately failed, and the rest of flows (=the second half) ran normally on the second emulator.

Weird and definitely a bug.

**Comment by bartekpacia** [comment]
Should be mitigated by #1867, but the root cause (which is unknown at this moment) still persists.

**Comment by RaphJustPark** [comment]
Hi, is there any update on this bug issue?

**Comment by omnarayan** [comment]
I've built on @avinash-bharti's work from #2339 and created an unofficial release with `--driver-host-port` support as a stopgap while [PR #2821](https://github.com/mobile-dev-inc/maestro/pull/2821) is under review.

  **Upgrade:**
```bash
  curl -fsSL https://raw.githubusercontent.com/omnarayan/Maestro/feature/driver-host-port-distribution/upgrade-maestro-ports.sh | sh
```

  **Usage:**
```bash
  maestro --driver-host-port 7005 --device device1 test flow.yaml
  maestro --driver-host-port 7006 --device device2 test flow.yaml
```
  **Restore:**  `bash ~/.maestro-backups/backup/restore.sh`

  📦 https://github.com/omnarayan/Maestro/releases/tag/fork-2.0.9-ports

**Comment by benmarten** [comment]
@omnarayan Does this actually split the tests like `--shards 3` does?

**Comment by omnarayan** [comment]
@benmarten  - No, they work differently:
- This approach: runs different flows/test files on different devices
- `--shards 3`: splits the same test suite across 3 devices to parallelize execution
