### ISSUE TITLE
Runner crashes under Xcode 16

### ISSUE THREAD

**Issue by freak4pc** [mobile-dev-inc/maestro#1894]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

For me simply having any kind of project with a text input and `inputText` command reproduces the issue

### Actual results

When getting to an input field and trying to use inputText to type, the runner retries a few times and then crashes. This reproduces constantly for us. 

![image](https://github.com/user-attachments/assets/31f023c2-ce3c-47f7-80f2-7c00d11d9e25)

### Expected results

Simply type as it used to in Xcode 15.x

### About app

Native. Mix of UIKit and SwiftUI. iOS 16 deployment target.

### About environment

Xcode 16.x on any MacBook (macOS Sequoia)

### Logs

<details>
<summary>Logs</summary>

```
Running on iPhone 15 Pro - iOS 17.5 - A5D1F2DB-FE3F-430F-AC14-EB3883AA8A7F

 ║
 ║  > Flow
 ║
 ║    ✅  Launch app "com.monday.monday"
 ║    ⏳  Run ../../actions/login/login.yaml when "Log in" is visible
 ║      ✅  Launch app "com.monday.monday" without stopping app
 ║      ✅  Tap on "Log in"
 ║      ✅  Tap on "Enter your email address"
 ║      ⏳  Input text mobile.e2e@monday.com
 ║      🔲 Tap on "Continue with email"
 ║      🔲 Tap on ".*More login options"
 ║      🔲 Tap on "Log in with your password"
 ║      🔲 Tap on "Enter your password"
 ║      🔲 Input text ${MAESTRO_E2E_PASSWORD}
 ║      🔲 Tap on "Log in"
 ║    🔲 Run ../../actions/home/create_new_board.yaml
 ║    🔲 Run ../../actions/board/rename_board.yaml
 ║    🔲 Tap on "item 1"
 ║    🔲 Tap on id: itemMenuButton
 ║    🔲 Tap on "Duplicate.*"
 ║    🔲 Assert that "Item 1 (copy)" is visible
 ║    🔲 Tap on "close"
 ║    🔲 Assert that "Item 1 (copy)" is visible
 ║    🔲 Tap on "item 1"
 ║    🔲 Tap on "item 1"
 ║    🔲 Input text  renamed
 ║    🔲 Tap on "done"
 ║    🔲 Assert that "item 1 renamed" is visible
 ║    🔲 Tap on "close"
 ║    🔲 Assert that "item 1 renamed" is visible
 ║    🔲 Tap on "item 1 renamed"
 ║    🔲 Tap on id: itemMenuButton
 ║    🔲 Tap on "Edit name"
 ║    🔲 Input text  again
 ║    🔲 Tap on "done"
 ║    🔲 Assert that "item 1 renamed again" is visible
 ║    🔲 Tap on "close"
 ║    🔲 Assert that "item 1 renamed again" is visible
 ║    🔲 Tap on id: boardGridActionButton
 ║    🔲 Tap on "New Group"
 ║    🔲 Input text Target group
 ║    🔲 Tap on "Add group"
 ║    🔲 Tap on "item 1 renamed again"
 ║    🔲 Tap on id: itemMenuButton
 ║    🔲 Tap on "Move to group"
 ║    🔲 Tap on "Target group"
 ║    🔲 Tap on "close"
 ║    🔲 Assert that "item 1 renamed again", Below "Target group" is visible
 ║    🔲 Tap on id: navigationAction.back
 ║    🔲 Tap on id: navigationAction.search
 ║    🔲 Input text ${output.boardName.random}
 ║    🔲 Tap on "${output.boardName.random}", Below "${output.boardName.random}"
 ║    🔲 Assert that "item 1 renamed again", Below "Target group" is visible
 ║
ℹ️ Retrying connection to the XCUITest server for 1...
ℹ️ Retrying connection to the XCUITest server for 2...
ℹ️ Retrying connection to the XCUITest server for 3...
ℹ️ Retrying connection to the XCUITest server for 4...
ℹ️ Retrying connection to the XCUITest server for 5...
Error: ⚠️ Error: An unknown network error occurred while communicating with the XCUITest server. If the issue persists, consider raising a GitHub issue with the error message and any available logs for further assistance.
⚠️ Error: An unknown network error occurred while communicating with the XCUITest server. If the issue persists, consider raising a GitHub issue with the error message and any available logs for further assistance.
Error: Request for inputText failed, because of XCUITest server got crashed/exit, body: {"errorMessage":"An unknown network error occurred while communicating with the XCUITest server. If the issue persists, consider raising a GitHub issue with the error message and any available logs for further assistance.","code":"network-error"}
ℹ️ Retrying connection to the XCUITest server for 1...

❌ Error: BlockingCoroutine is cancelling
kotlinx.coroutines.JobCancellationException: BlockingCoroutine is cancelling; job=BlockingCoroutine{Cancelling}@7c0692f4
Caused by: NetworkError(errorResponse=Request for inputText failed, because of XCUITest server got crashed/exit, body: {"errorMessage":"An unknown network error occurred while communicating with the XCUITest server. If the issue persists, consider raising a GitHub issue with the error message and any available logs for further assistance.","code":"network-error"})
	at xcuitest.XCTestDriverClient.handleExceptions(XCTestDriverClient.kt:280)
	at xcuitest.XCTestDriverClient.processResponse(XCTestDriverClient.kt:258)
	at xcuitest.XCTestDriverClient.executeJsonRequest(XCTestDriverClient.kt:240)
	at xcuitest.XCTestDriverClient.inputText(XCTestDriverClient.kt:152)
	at ios.xctest.XCTestIOSDevice$input$1.invoke(XCTestIOSDevice.kt:119)
	at ios.xctest.XCTestIOSDevice$input$1.invoke(XCTestIOSDevice.kt:117)
	at ios.xctest.XCTestIOSDevice.execute(XCTestIOSDevice.kt:227)
	at ios.xctest.XCTestIOSDevice.input(XCTestIOSDevice.kt:117)
	at ios.LocalIOSDevice.input(LocalIOSDevice.kt:82)
	at maestro.drivers.IOSDriver$inputText$1.invoke(IOSDriver.kt:388)
	at maestro.drivers.IOSDriver$inputText$1.invoke(IOSDriver.kt:388)
	at maestro.drivers.IOSDriver.runDeviceCall(IOSDriver.kt:499)
	at maestro.drivers.IOSDriver.inputText(IOSDriver.kt:388)
	at maestro.Maestro.inputText(Maestro.kt:480)
	at maestro.orchestra.Orchestra.inputTextCommand(Orchestra.kt:752)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:259)
	at maestro.orchestra.Orchestra.executeSubflowCommands(Orchestra.kt:605)
	at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:646)
	at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:514)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:270)
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:201)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:111)
	at maestro.orchestra.Orchestra.runFlow$default(Orchestra.kt:75)
	at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:185)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:54)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:51)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:145)
	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:51)
	at maestro.cli.command.TestCommand$handleSessions$1$1$results$1$1$1.invoke(TestCommand.kt:291)
	at maestro.cli.command.TestCommand$handleSessions$1$1$results$1$1$1.invoke(TestCommand.kt:249)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:106)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:58)
	at maestro.cli.command.TestCommand$handleSessions$1$1$results$1$1.invokeSuspend(TestCommand.kt:249)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

</details>

### Maestro version

1.37.7

### How did you install Maestro?

other (please specify in the text area below)

### Anything else?

Installed using asdf / mise

**Comment by yobelioekaharja** [comment]
I also got the exactly the same error using Xcode 13.x

**Comment by bartekpacia** [comment]
Hey, I tried to reproduce this on Xcode 16 Beta 6 and iOS simulator with iOS 18, and didn't manage to.

I ran: `maestro test e2e/workspaces/demo_app/fill_form.yaml`.

Please share more information so we can reproduce the issue.

**Comment by freak4pc** [comment]
This seems solved for us in beta 6.
Thanks !

**Comment by bartekpacia** [comment]
That's great to hear, thanks!
