### ISSUE TITLE
UNKNOWN: Unexpected error in RPC handling

### ISSUE THREAD

**Issue by jschisler** [mobile-dev-inc/maestro#192]
```
com.github.michaelbull.result.UnwrapException: kotlin.Unit io.grpc.StatusRuntimeException: UNKNOWN: Unexpected error in RPC handling
        at maestro.drivers.IOSDriver.contentDescriptor(IOSDriver.kt:149)
        at maestro.ViewHierarchy$Companion.from-c1iYVAs(ViewHierarchy.kt:28)
        at maestro.Maestro.viewHierarchy-prqvCes(Maestro.kt:228)
        at maestro.orchestra.Orchestra.findElement(Orchestra.kt:257)
        at maestro.orchestra.Orchestra.findElement$default(Orchestra.kt:243)
        at maestro.orchestra.Orchestra.tapOnElement(Orchestra.kt:216)
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:120)
        at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:107)
        at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:69)
        at maestro.orchestra.Orchestra.runInitFlow(Orchestra.kt:79)
        at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:91)
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:32)
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:29)
        at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:116)
        at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:29)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:60)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:30)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:74)
```
```
appId: com.test.app
---
- launchApp
- hideKeyboard

# Initial choice screen (sign-in/subscribe)
- tapOn:
    id: "initialscreen_signin_button"

# Login screen
# dies here 
- tapOn:
    id: "username_textfield"
- inputText: me@here.com"
- tapOn:
    id: "password_textfield"
- inputText: "p@$$w0rd"
- tapOn:
    id: "login_continue_button"
```

**Comment by dmitry-zaitsev** [comment]
Do you have `idb_companion` running?

**Comment by jschisler** [comment]
Yes I do. It works through 1 screen before I navigate to the login screen and then I see that exception.

**Comment by dmitry-zaitsev** [comment]
Could you please share your:

- Xcode version
- idb version

**Comment by jschisler** [comment]
Looks like idb 3.10 if the return from the "which idb" command is right:
`idb is /Library/Frameworks/Python.framework/Versions/3.10/bin/idb`

Xcode Version 14.0 (14A309)

**Comment by jschisler** [comment]
Using mobile-dev-inc/tap/idb-companion 1.1.7 if that helps.

**Comment by jschisler** [comment]
Also, if I navigate manually to the screen in question and run `maestro hierarchy` I get the same error stack trace

**Comment by dmitry-zaitsev** [comment]
@jschisler thanks, that is useful context. What if you run `idb ui describe-all` instead of `maestro hierarchy` on the said screen?

**Comment by jschisler** [comment]
I did `idb --companion localhost:10882 ui describe-all` and it returned `Unexpected error in RPC handling`

**Comment by dmitry-zaitsev** [comment]
Could you share logs that you see from `idb_companion`?

It appears that there is some issue in the `idb` which is what causes that. Possibly due to some particular state of your application. Is there perhaps anything even remotely unusual on the screen that is causing the issue? I.e. some particular system APIs being used?

**Comment by jschisler** [comment]
The screen in question contains a WKWebView and is loaded with a EULA from a URL. However, I see the same error on different screens that make no such call. However, I have noticed problems with screens that have attributed strings in them, but that was from a different build of idb_companion and I no longer see this.

idb_companion log:
[IDB Companion.txt](https://github.com/mobile-dev-inc/maestro/files/9607994/IDB.Companion.txt)

**Comment by jschisler** [comment]
Further, if I debug idb_companion in Xcode, it dies here:

![image](https://user-images.githubusercontent.com/742546/191566243-b5b9b93e-3958-44e9-8b4d-cfdbc5005920.png)

**Comment by aakash1313** [comment]
Getting the same exception on my side too while trying on the iOS app 

`com.github.michaelbull.result.UnwrapException: kotlin.Unit io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason  
        at maestro.drivers.IOSDriver.contentDescriptor(IOSDriver.kt:154)
        at maestro.Maestro$findElementWithTimeout$1.invoke(Maestro.kt:287)
        at maestro.Maestro$findElementWithTimeout$1.invoke(Maestro.kt:286)
        at maestro.MaestroTimer.withTimeout(MaestroTimer.kt:16)
        at maestro.Maestro.findElementWithTimeout(Maestro.kt:286)
        at maestro.orchestra.Orchestra.findElement(Orchestra.kt:278)
        at maestro.orchestra.Orchestra.findElement$default(Orchestra.kt:261)
        at maestro.orchestra.Orchestra.tapOnElement(Orchestra.kt:234)
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:121)
        at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:108)
        at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:70)
        at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:98)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:32)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:29)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:116)
	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:29)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:60)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:30)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:88)`

**Comment by MarcoCadei** [comment]
Having this same problem on Xcode14. Do you have news @dmitry-zaitsev?

**Comment by Gruppio** [comment]
+1 Same

**Comment by dmitry-zaitsev** [comment]
Hey folks, this is still on our radar. The fact that the issue is on `idb_companion` side makes it hard to come up with a fix so we are exploring options where we provide some sort of alternative to work around this problem

cc @berikv

**Comment by AlessandroSteri** [comment]
+1 on the same problem 🥶

**Comment by Leland-Takamine** [comment]
@jschisler @MarcoCadei @Gruppio @AlessandroSteri We've made a lot of improvements on this front especially with the release of the new iOS driver. Can you please try again on the latest and reopen if you are still running into issues? Thanks!
