### ISSUE TITLE
LaunchApp no longer work while Maestro Studio is open since update 1.37.9

### ISSUE THREAD

**Issue by pplourde** [mobile-dev-inc/maestro#1927]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

1. Ensure that Maestro Studio is running and Maestro CLI was updated to version 1.37.9
2. Run any flow that includes the '- launchApp' command

### Actual results

- App closes and doesn't relaunch.
- Test fails as the app does not launch while Maestro Studio is open.

### Expected results

- App closes and relaunches.
- Test passes and continues as normal.

### About app

- Issue is encountered regardless of the app used to test. The command is broken and does not work if Maestro Studio is running even when attempting to launch well known app such as Youtube or others.

### About environment

- Issue was reproduced across multiple Android devices (found on S22 Ultra Android 14, reproduced on S20 Android 12, Pixel 7 Pro Android 14)
- We did not attempt to reproduce on iOS so issue might or might not occur with iOS.

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. *DO NOT* remove the backticks! -->
```

</details>

### Maestro version

1.37.9

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

### Anything else?

- Closing Maestro Studio and running the same flow again works no problem.
- Flow will always fail while attempting to do - launchApp while Maestro Studio is running.
- We had no issue at all prior to updating to the 1.37.9 version of Maestro CLI.

**Comment by bartekpacia** [comment]
Hey @pplourde, can you show exact commands you used, and also the flow file?


### My repro

I reproduce this issue, but with different logs/errors. This is my flow:

```yaml
# file: samples/android-flow.yaml
appId: org.wikipedia
---
- launchApp:
    clearState: true
- tapOn: CONTINUE
```

and wikipedia app is of course installed on my Android emulator.

First I run:

```console
maestro studio
```

Then in a new terminal tab:

```
maestro test samples/android-flow.yaml
```

Terminal logs:

```
$ maestro test samples/android-flow.yaml
\
Running on emulator-5554

 ║
 ║  > Flow
 ║
 ║    ❌  Launch app "org.wikipedia" with clear state
 ║    🔲 Tap on "CONTINUE"
 ║

Unable to launch app org.wikipedia: null

==== Debug output (logs & screenshots) ====

/Users/bartek/.maestro/tests/2024-08-21_113614
```

<details><summary>maestro.log</summary>

```
[INFO ] MAESTRO - ---- System Info ----
[INFO ] MAESTRO - Maestro Version: 1.37.9
[INFO ] MAESTRO - CI: Undefined
[INFO ] MAESTRO - OS Name: Mac OS X
[INFO ] MAESTRO - OS Version: 14.5
[INFO ] MAESTRO - Architecture: aarch64
[INFO ] MAESTRO - Java Version: 17
[INFO ] MAESTRO - Xcode Version: 15.4
[INFO ] MAESTRO - Flutter Version: 3.22.0
[INFO ] MAESTRO - Flutter Channel: stable
[INFO ] MAESTRO - ---------------------
[INFO ] maestro.Maestro - Getting device info
[INFO ] m.cli.runner.MaestroCommandRunner - Apply configuration RUNNING
[INFO ] m.cli.runner.MaestroCommandRunner - Apply configuration metadata CommandMetadata(numberOfRuns=null, evaluatedCommand=MaestroCommand(tapOnElement=null, tapOnPoint=null, tapOnPointV2Command=null, scrollCommand=null, swipeCommand=null, backPressCommand=null, assertCommand=null, assertConditionCommand=null, inputTextCommand=null, inputRandomTextCommand=null, launchAppCommand=null, applyConfigurationCommand=ApplyConfigurationCommand(config=MaestroConfig(appId=org.wikipedia, name=null, tags=[], initFlow=null, ext={}, onFlowStart=null, onFlowComplete=null), label=null), openLinkCommand=null, pressKeyCommand=null, eraseTextCommand=null, hideKeyboardCommand=null, takeScreenshotCommand=null, stopAppCommand=null, killAppCommand=null, clearStateCommand=null, clearKeychainCommand=null, runFlowCommand=null, setLocationCommand=null, repeatCommand=null, copyTextCommand=null, pasteTextCommand=null, defineVariablesCommand=null, runScriptCommand=null, waitForAnimationToEndCommand=null, evalScriptCommand=null, scrollUntilVisible=null, travelCommand=null, startRecordingCommand=null, stopRecordingCommand=null, addMediaCommand=null, setAirplaneModeCommand=null, toggleAirplaneModeCommand=null), logMessages=[], insight=Insight(message=, level=NONE))
[INFO ] m.cli.runner.MaestroCommandRunner - Apply configuration COMPLETED
[INFO ] m.cli.runner.MaestroCommandRunner - Launch app "org.wikipedia" with clear state RUNNING
[INFO ] m.cli.runner.MaestroCommandRunner - Launch app "org.wikipedia" with clear state metadata CommandMetadata(numberOfRuns=null, evaluatedCommand=MaestroCommand(tapOnElement=null, tapOnPoint=null, tapOnPointV2Command=null, scrollCommand=null, swipeCommand=null, backPressCommand=null, assertCommand=null, assertConditionCommand=null, inputTextCommand=null, inputRandomTextCommand=null, launchAppCommand=LaunchAppCommand(appId=org.wikipedia, clearState=true, clearKeychain=null, stopApp=null, permissions=null, launchArguments=null, label=null), applyConfigurationCommand=null, openLinkCommand=null, pressKeyCommand=null, eraseTextCommand=null, hideKeyboardCommand=null, takeScreenshotCommand=null, stopAppCommand=null, killAppCommand=null, clearStateCommand=null, clearKeychainCommand=null, runFlowCommand=null, setLocationCommand=null, repeatCommand=null, copyTextCommand=null, pasteTextCommand=null, defineVariablesCommand=null, runScriptCommand=null, waitForAnimationToEndCommand=null, evalScriptCommand=null, scrollUntilVisible=null, travelCommand=null, startRecordingCommand=null, stopRecordingCommand=null, addMediaCommand=null, setAirplaneModeCommand=null, toggleAirplaneModeCommand=null), logMessages=[], insight=Insight(message=, level=NONE))
[INFO ] maestro.Maestro - Clearing app state org.wikipedia
[INFO ] maestro.Maestro - Launching app org.wikipedia
[INFO ] maestro.Maestro - Taking screenshot: /var/folders/r6/5z0bypqn4cb8p369zlrfhw3c0000gn/T/screenshot-1724236584313799714500118837704.png
[INFO ] maestro.utils.ScreenshotUtils - Taking screenshot to output sink
[INFO ] m.cli.runner.MaestroCommandRunner - Launch app "org.wikipedia" with clear state FAILED
```

</details>

**Comment by bartekpacia** [comment]
Additionally, I also tested on iOS and there's a different bug – Maestro Studio stops working, i.e. the emulator screenshot stops refreshing.

repro:
0. Run iOS simulator (I used iOS 17.5)
0. `maestro download-samples`
1. `maestro studio`
2. in a new tab `maestro test samples/ios-flow.yaml`

<details><summary>studio logs</summary>

```
$ maestro studio
Running on iPhone 15 - iOS 17.5 - BCFE83EE-F9A2-4612-B7B4-4CB05CE2406B

╭────────────────────────────────────────────────────────╮
│                                                        │
│   Maestro Studio is running at http://localhost:9999   │
│                                                        │
╰────────────────────────────────────────────────────────╯


Tip: Maestro Studio can now run simultaneously alongside other Maestro CLI commands!

Navigate to http://localhost:9999 in your browser to open Maestro Studio. Ctrl-C to exit.
java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
	at org.apache.commons.compress.archivers.zip.InflaterInputStreamWithStatistics.fill(InflaterInputStreamWithStatistics.java:52)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at org.apache.commons.compress.archivers.zip.InflaterInputStreamWithStatistics.read(InflaterInputStreamWithStatistics.java:67)
	at org.rauschig.jarchivelib.ZipFileArchiver$ZipFileArchiveInputStream.read(ZipFileArchiver.java:72)
	at java.base/java.io.InputStream.read(InputStream.java:218)
	at org.rauschig.jarchivelib.IOUtils.copy(IOUtils.java:82)
	at org.rauschig.jarchivelib.IOUtils.copy(IOUtils.java:66)
	at org.rauschig.jarchivelib.IOUtils.copy(IOUtils.java:51)
	at org.rauschig.jarchivelib.CommonsArchiver.extract(CommonsArchiver.java:104)
	at org.rauschig.jarchivelib.CommonsArchiver.extract(CommonsArchiver.java:82)
	at xcuitest.installer.LocalXCTestInstaller.extractZipToApp(LocalXCTestInstaller.kt:196)
	at xcuitest.installer.LocalXCTestInstaller.startXCTestRunner(LocalXCTestInstaller.kt:161)
	at xcuitest.installer.LocalXCTestInstaller.start(LocalXCTestInstaller.kt:82)
	at xcuitest.api.NetworkErrorHandler.retryConnection(NetworkErrorHandler.kt:70)
	at xcuitest.XCTestDriverClient.addRetryInterceptor$lambda$8(XCTestDriverClient.kt:329)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at xcuitest.XCTestDriverClient.executeJsonRequest(XCTestDriverClient.kt:240)
	at xcuitest.XCTestDriverClient.viewHierarchy(XCTestDriverClient.kt:72)
	at ios.xctest.XCTestIOSDevice$viewHierarchy$1.invoke(XCTestIOSDevice.kt:40)
	at ios.xctest.XCTestIOSDevice$viewHierarchy$1.invoke(XCTestIOSDevice.kt:38)
	at ios.xctest.XCTestIOSDevice.execute(XCTestIOSDevice.kt:227)
	at ios.xctest.XCTestIOSDevice.viewHierarchy(XCTestIOSDevice.kt:38)
	at ios.LocalIOSDevice.viewHierarchy(LocalIOSDevice.kt:47)
	at maestro.drivers.IOSDriver.viewHierarchy(IOSDriver.kt:152)
	at maestro.drivers.IOSDriver.access$viewHierarchy(IOSDriver.kt:41)
	at maestro.drivers.IOSDriver$contentDescriptor$1.invoke(IOSDriver.kt:147)
	at maestro.drivers.IOSDriver$contentDescriptor$1.invoke(IOSDriver.kt:147)
	at maestro.drivers.IOSDriver.runDeviceCall(IOSDriver.kt:499)
	at maestro.drivers.IOSDriver.contentDescriptor(IOSDriver.kt:147)
	at maestro.ViewHierarchy$Companion.from-8JJjmZI(ViewHierarchy.kt:29)
	at maestro.Maestro.viewHierarchy-c1iYVAs(Maestro.kt:422)
	at maestro.Maestro.viewHierarchy-c1iYVAs$default(Maestro.kt:421)
	at maestro.studio.DeviceService.getDeviceScreen(DeviceService.kt:172)
	at maestro.studio.DeviceService.access$getDeviceScreen(DeviceService.kt:43)
	at maestro.studio.DeviceService$routes$3$1.invokeSuspend(DeviceService.kt:82)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
ℹ️ Retrying connection to the XCUITest server for 1...
Aug 21, 2024 11:47:03 AM okhttp3.internal.platform.Platform log
WARNING: A connection to http://[::1]:22087/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
ℹ️ Retrying connection to the XCUITest server for 1...
Aug 21, 2024 11:47:25 AM okhttp3.internal.platform.Platform log
WARNING: A connection to http://[::1]:22087/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
ℹ️ Retrying connection to the XCUITest server for 2...
ℹ️ Retrying connection to the XCUITest server for 2...
Aug 21, 2024 11:47:46 AM okhttp3.internal.platform.Platform log
WARNING: A connection to http://[::1]:22087/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Aug 21, 2024 11:47:46 AM okhttp3.internal.platform.Platform log
WARNING: A connection to http://[::1]:22087/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```

</details>

**Comment by ahervieuxgirard** [comment]
@bartekpacia  Hello i'm the other guy that is working with @pplourde

I simply ran maestro studio first then my script using simple command : `maestro test flowb.yml`

The flow : 
```
---
appId: com.google.android.youtube

tags:
  - batman
  - robin

---

- launchApp:
    appId: "com.google.android.youtube"
```

**Comment by zubairehman** [comment]
any update on this? facing the same issue

**Comment by theapache64** [comment]
happening to me as well

**Comment by suma-ranjan** [comment]
Any solution to launchApp??

**Comment by C0dingBee** [comment]
me too

**Comment by guillempuche** [comment]
Same in v1.39.1

**Comment by SmartProjetos** [comment]
Still happening in v1.39.9

**Comment by jerone** [comment]
Duplicate #2188

**Comment by owens-ben** [comment]
Still happening in 1.41.0

**Comment by oserrabassa** [comment]
Issue also happens in Maestro 2.0.1.
Temporary solution is to basically kill `maestro studio` process before running any test flow.

**Comment by Fishbowler** [comment]
Gonna merge this into another issue.
This is the earlier issue, but I think the other is more descriptive of the complete problem.
