### ISSUE TITLE
WebDriver: IllegalStateException: Could not retrieve hierarchy through maestro.getContentDescription()

### ISSUE THREAD

**Issue by pocmo** [mobile-dev-inc/maestro#1936]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

In our case the crash happens after pressing a login button after entering username/password. I'll debug the issue and either try to provide a patch or a public reproducible test case.

### Actual results

We started to see a crash in `WebDriver`, but so far we haven't found the root cause yet.

```
java.lang.IllegalStateException: Could not retrieve hierarchy through maestro.getContentDescription()
```

### Expected results

No crash

### About app

(not public website)

### About environment

* macOS 14.5
* Chrome Version 128.0.6613.85 (Official Build) (x86_64)

### Logs

<details>
<summary>Logs</summary>

```
java.lang.IllegalStateException: Could not retrieve hierarchy through maestro.getContentDescription()
        at maestro.drivers.WebDriver.contentDescriptor(WebDriver.kt:175)
        at maestro.ViewHierarchy$Companion.from-8JJjmZI(ViewHierarchy.kt:29)
        at maestro.utils.ScreenshotUtils$Companion.viewHierarchy-c1iYVAs(ScreenshotUtils.kt:99)
        at maestro.utils.ScreenshotUtils$Companion.waitForAppToSettle-OpTFbEc(ScreenshotUtils.kt:58)
        at maestro.utils.ScreenshotUtils$Companion.waitForAppToSettle-OpTFbEc$default(ScreenshotUtils.kt:38)
        at maestro.drivers.WebDriver.waitForAppToSettle-5RpGHs4(WebDriver.kt:366)
        at maestro.Maestro.waitForAppToSettle-5RpGHs4(Maestro.kt:474)
        at maestro.Maestro.waitForAppToSettle-5RpGHs4$default(Maestro.kt:469)
        at maestro.Maestro.hierarchyBasedTap-hbl3e4M(Maestro.kt:353)
        at maestro.Maestro.performTap-hbl3e4M(Maestro.kt:281)
        at maestro.Maestro.tap-BUbHBYE(Maestro.kt:195)
        at maestro.orchestra.Orchestra.tapOnElement(Orchestra.kt:777)
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:240)
        at maestro.orchestra.Orchestra.executeSubflowCommands(Orchestra.kt:605)
        at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:646)
        at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:514)
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:270)
        at maestro.orchestra.Orchestra.executeSubflowCommands(Orchestra.kt:605)
        at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:646)
        at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:514)
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:270)
        at maestro.orchestra.Orchestra.executeSubflowCommands(Orchestra.kt:605)
        at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:646)
        at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:514)
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:270)
        at maestro.orchestra.Orchestra.executeSubflowCommands(Orchestra.kt:605)
        at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:646)
        at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:514)
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:270)
        at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:201)
        at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:111)
        at maestro.orchestra.Orchestra.runFlow$default(Orchestra.kt:75)
        at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:185)
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:54)
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:51)
        at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:145)
        at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:51)
        at maestro.cli.command.TestCommand$handleSessions$1$1$results$1$1$1.invoke(TestCommand.kt:291)
        at maestro.cli.command.TestCommand$handleSessions$1$1$results$1$1$1.invoke(TestCommand.kt:249)
        at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:107)
        at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:58)
        at maestro.cli.command.TestCommand$handleSessions$1$1$results$1$1.invokeSuspend(TestCommand.kt:249)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)```

</details>


### Maestro version

1.37.9

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

### Anything else?

_No response_

**Comment by pocmo** [comment]
In this specific situation `executeJS()` returns `null`. There's already a `sleep(100)`. In this case it seems like more time is needed. If I add a retry loop then this will work after ~500ms.

https://github.com/mobile-dev-inc/maestro/blob/872508459457d6569d790ede0f6287bfe077d881/maestro-client/src/main/java/maestro/drivers/WebDriver.kt#L86-L99

**Comment by bartekpacia** [comment]
Hey, thanks for the report. Waiting for reproducible example.
