### ISSUE TITLE
dadb.AdbStreamClosed Exception after first test run

### ISSUE THREAD

**Issue by F-Goncalves** [mobile-dev-inc/maestro#208]
Hi, 
whenever I run maestro test I can only run it once successfully. Every consecutive run fails with a dadb.AdbStreamClosed Exception. Only restarting the Android Emulator solves this. But every second time I run the test the same exception occurs.

Exception in thread "pool-2-thread-1" dadb.AdbStreamClosed: ADB stream is closed for localId: 543f194d
	at dadb.MessageQueue.poll(MessageQueue.kt:76)
	at dadb.MessageQueue.take(MessageQueue.kt:37)
	at dadb.AdbConnection.open(AdbConnection.kt:48)
	at dadb.DadbImpl.open(DadbImpl.kt:31)
	at dadb.forwarding.TcpForwarder.handleForwarding$lambda-1(TcpForwarder.kt:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Any advice on how to solve this?

**Comment by dmitry-zaitsev** [comment]
This is just a guess, but do you perhaps run `maestro hierarchy` during the test?

**Comment by F-Goncalves** [comment]
No I didn't. I didn't even know about that command when I encountered this exception.

**Comment by dmitry-zaitsev** [comment]
What kind of emulator are you using? API version, with/without Google Play, what "device" model, etc.

**Comment by F-Goncalves** [comment]
Pixel 3a
API 32 arm64-v8a
with Google Play

Could an IDE that was previously debugging on the same emulator be an issue?

**Comment by dmitry-zaitsev** [comment]
Unlikely, but it could be related to the fact that this is an ARM emulator _or_ the fact that this is API 32. If you could try the following, it would be a great help:

- Check if a new emulator with the same exact configuration works
- If not, does API 30 work?

**Comment by alucardeht** [comment]
the same problem here, i'm using Pixel 3a API 33 arm64-v8a

**Comment by alucardeht** [comment]
> Unlikely, but it could be related to the fact that this is an ARM emulator _or_ the fact that this is API 32. If you could try the following, it would be a great help:
> 
> * Check if a new emulator with the same exact configuration works
> * If not, does API 30 work?

i created one using API 30 and it works
