### ISSUE TITLE
Compatibility Issue with GraalJS Engine and OpenJDK 23

### ISSUE THREAD

**Issue by FelixLisczyk** [mobile-dev-inc/maestro#2120]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

I have encountered an issue while using Maestro version 1.39.0 on macOS 15.0.1 (24A348). The problem arises when running any script using the GraalJS engine, resulting in an immediate exception. It appears that the version of GraalJS used by Maestro might be incompatible with OpenJDK 23, which is installed automatically as a dependency via Homebrew.

**Steps to Reproduce:**

1. Install Maestro version 1.39.0 on macOS 15.0.1 using Homebrew.
2. Ensure OpenJDK 23 is installed (default via Homebrew).
3. Run any script using the GraalJS engine.

### Actual results

The following exception is thrown immediately:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.ensureClassInitialized(java.lang.Class)'
	at com.oracle.truffle.api.library.LibraryFactory.ensureLibraryInitialized(LibraryFactory.java:384)
	at com.oracle.truffle.api.library.LibraryFactory.getUncached(LibraryFactory.java:364)
	at com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:210)
	at com.oracle.truffle.api.interop.InteropLibraryGen.<init>(InteropLibraryGen.java:170)
	at com.oracle.truffle.api.interop.InteropLibraryGen.<clinit>(InteropLibraryGen.java:161)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:578)
	at java.base/java.lang.Class.forName(Class.java:557)
	at com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:777)
	at com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:740)
	at com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:733)
	at com.oracle.truffle.api.interop.InteropLibrary.<clinit>(InteropLibrary.java:2843)
	at com.oracle.truffle.polyglot.PolyglotValueDispatch.<clinit>(PolyglotValueDispatch.java:155)
	at com.oracle.truffle.polyglot.PolyglotImpl.initialize(PolyglotImpl.java:163)
	at org.graalvm.polyglot.impl.AbstractPolyglotImpl.setConstructors(AbstractPolyglotImpl.java:266)
	at org.graalvm.polyglot.Engine$1.loadAndValidateProviders(Engine.java:917)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:890)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:864)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:864)
	at org.graalvm.polyglot.Engine.access$000(Engine.java:110)
	at org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:136)
	at org.graalvm.polyglot.Engine.getImpl(Engine.java:360)
	at org.graalvm.polyglot.Source.getImpl(Source.java:140)
	at org.graalvm.polyglot.Source$Builder.build(Source.java:920)
	at maestro.js.GraalJsEngine.evaluateScript(GraalJsEngine.kt:69)
	at maestro.js.GraalJsEngine.evaluateScript(GraalJsEngine.kt:22)
	at maestro.orchestra.Orchestra.runScriptCommand(Orchestra.kt:418)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:288)
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:193)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:127)
	at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:177)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:62)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:53)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:160)
	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:53)
	at maestro.cli.command.TestCommand.runSingleFlow(TestCommand.kt:352)
	at maestro.cli.command.TestCommand.access$runSingleFlow(TestCommand.kt:63)
	at maestro.cli.command.TestCommand$runShardSuite$2.invoke(TestCommand.kt:326)
	at maestro.cli.command.TestCommand$runShardSuite$2.invoke(TestCommand.kt:297)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:102)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:52)
	at maestro.cli.command.TestCommand.runShardSuite(TestCommand.kt:297)
	at maestro.cli.command.TestCommand.access$runShardSuite(TestCommand.kt:63)
	at maestro.cli.command.TestCommand$handleSessions$1$results$1$1.invokeSuspend(TestCommand.kt:265)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
```

### Expected results

Scripts should execute without throwing exceptions.

### About app

I'm using Maestro to create UI tests for native iOS apps. This detail shouldn't impact the issue at hand.

### About environment

Maestro Version: 1.39.0
Operating System: macOS 15.0.1 (24A348)
Device: MacBook Pro (14-inch, 2021)
Java Version: OpenJDK 23 (installed via Homebrew)

### Maestro version

1.39.0

### How did you install Maestro?

Homebrew

### Anything else?

Related issues:

- https://github.com/mobile-dev-inc/maestro/issues/2049
- https://github.com/mobile-dev-inc/maestro/issues/1388

**Comment by corrosive4354** [comment]
It is recommended to check Maestro's documentation or community support to confirm whether it supports OpenJDK 23. You may need to use an older JDK version, such as OpenJDK 21.

Seeing that you are using homebrew, I would like to recommend [Servbay](servbay.com) to you, which is more professional and easy to use than docker and homebrew on Mac.

**Comment by FelixLisczyk** [comment]
Thank you for your feedback.

According to the [Maestro documentation](https://maestro.mobile.dev/getting-started/installing-maestro), the recommended installation method for macOS is through Homebrew. This installation process automatically installs the latest version of OpenJDK, which is currently OpenJDK 23. To ensure a seamless user experience, either Maestro needs to be fully compatible with OpenJDK 23 or the Homebrew formula should specify a dependency on an earlier version of OpenJDK, such as OpenJDK 21.

**Comment by philipfong** [comment]
I'm running into this problem as well. Openjdk 23 is installed on our mac os runner, but I happen to have openjdk 17 running locally, and all js scripts were run just fine locally. It would be unfortunate to have to go back to rhino js.

**Comment by yolpsoftware** [comment]
Still present in 1.40.3

This might be important: I began using Maestro a month ago and I first set it up on my Macbook M4, where I never encountered this exception, even though I'm using GraalJS in all scripts. Then I set it up, using the same commands, on my older Mac Mini M1, where I'm currently stuck with this exception (removing GraalJS helps).

So I have the same setup, same OS, same scripts, and they run just fine on the M4, but not on the M1 machine.

One idea:

This Mac Mini was first set up at a time when the migration from Intel x64 to Apple Silicon arm64 was still in progress. For example, Homebrew was still running as an Intel binary through Rosetta when I bought it. Today, Homebrew and Java and Maestro are installed as arm64 binaries.

But maybe there is some dependency on the system that's still an Intel binary? For example, last week I had problems when I tried to build my app on the M1. It had Cocoapods (and Ruby) still installed as an Intel binary, and the problems went away when I installed Cocoapods as arm64.

Maybe a similar difference is causing this bug. Just speculating.

**Comment by yolpsoftware** [comment]
Any update on this? Makes using GraalJS impossible.

**Comment by Fishbowler** [comment]
You're already in the correct place to see updates.

**Comment by Fishbowler** [comment]
How's this looking in Maestro 2?
I _think_ the Graal version bump fixed this.

**Comment by FelixLisczyk** [comment]
I've upgraded to Maestro 2 and OpenJDK 24. My flow scripts are running without any errors. 👍

**Comment by yolpsoftware** [comment]
Thank you @Fishbowler .
