### ISSUE TITLE
Upon running 10 flows at once Issue in 1.39.0 and 1.39.1

### ISSUE THREAD

**Issue by mskhan18** [mobile-dev-inc/maestro#2141]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

`1. I tried to run all the follows one after the other but after executing 5 tests i get the following error`

### Actual results

```
Exception in thread "pool-4-thread-1" java.io.IOException: Command failed (host:transport:emulator-5554): device offline
        at dadb.adbserver.AdbServer.send$dadb(AdbServer.kt:99)
        at dadb.adbserver.AdbServerDadb.open(AdbServer.kt:137)
        at dadb.forwarding.TcpForwarder.handleForwarding$lambda-1(TcpForwarder.kt:64)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1623)
```

### Expected results

All Flows should run one after the other

### About app

Closed Source
Cross Platform
Flutter 3.22.5

### About environment

<img width="253" alt="ios" src="https://github.com/user-attachments/assets/e31e5f04-332b-437b-9a19-37c0553f246f">

X code Version 16.0 (16A242d)

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. *DO NOT* remove the backticks! -->
```

</details>

### Maestro version

1.39.0

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

**Comment by mskhan18** [comment]
Duplicated
