### ISSUE TITLE
`initFlow` doesn't work in android release build

### ISSUE THREAD

**Issue by pafry7** [mobile-dev-inc/maestro#215]
We are building the app with `npx expo build:android --variant release`.

`login.yml`
```
appId: com.test.android
---
- launchApp:
    clearState: true
- tapOn: "e-mail address"
- inputText: "test@test.com"
- tapOn: "Submit"
- assertVisible: "Logged in"
```
`feature.yml`

```
appId: com.test.android
initFlow: login.yaml
---
- launchApp
- ...
```
Error message at the end of running `initFlow`:
```
java.io.IOException: Shell command failed (run-as com.test.android find -type d):
run-as: package not debuggable: com.test.android            
                                                                 
        at maestro.android.AndroidAppFiles.shell(AndroidAppFiles.kt:66)
        at maestro.android.AndroidAppFiles.listRemoteFiles(AndroidAppFiles.kt:57)
        at maestro.android.AndroidAppFiles.pull(AndroidAppFiles.kt:19)
        at maestro.drivers.AndroidDriver.pullAppState(AndroidDriver.kt:160)
        at maestro.Maestro.pullAppState(Maestro.kt:81)           
        at maestro.orchestra.Orchestra.runInitFlow(Orchestra.kt:93)
        at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:91)
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:32)
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:29)
        at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:116)
        at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:29)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:60)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:30)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145) 
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)                                                  
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)    
        at maestro.cli.AppKt.main(App.kt:88)
```
We are using `expo-dev-client`, so testing debug build is not the thing we want to do. Running the same test on debug build, results in main flow not being started.

**Comment by simon-gilmurray** [comment]
Watching this as it's also causing issues when testing my release variants using the initFlow command

**Comment by Leland-Takamine** [comment]
@pafry7 @simon-gilmurray We just release the `runFlow` command which is likely what you want instead. `runFlow` runs the commands in another Flow file and works with debuggable + release builds: https://maestro.mobile.dev/reference/nested-flows

Please let us know if this works for you!
