### ISSUE TITLE
Exception while running flows 

### ISSUE THREAD

**Issue by aakash1313** [mobile-dev-inc/maestro#274]
Getting the below exception while running flows : 

```
io.grpc.StatusRuntimeException: UNKNOWN                      
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)                                                           
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at maestro_android.MaestroDriverGrpc$MaestroDriverBlockingStub.viewHierarchy(MaestroDriverGrpc.java:270)                             
        at maestro.drivers.AndroidDriver.contentDescriptor(AndroidDriver.kt:254)
        at maestro.ViewHierarchy$Companion.from-c1iYVAs(ViewHierarchy.kt:28)
        at maestro.Maestro.viewHierarchy-prqvCes(Maestro.kt:271)
        at maestro.Maestro.waitForAppToSettle-prqvCes(Maestro.kt:313)
        at maestro.Maestro.tap(Maestro.kt:183)               
        at maestro.Maestro.tap(Maestro.kt:140)               
        at maestro.orchestra.Orchestra.tapOnElement(Orchestra.kt:235)
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:121)
        at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:108)
        at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:70)
        at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:98)                                                   
        at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2$1.invoke(TestRunner.kt:82)                                             
        at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2$1.invoke(TestRunner.kt:81)                                             
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:116)
	at maestro.cli.runner.TestRunner.access$runCatching(TestRunner.kt:21)
	at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2.invoke(TestRunner.kt:81)
	at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2.invoke(TestRunner.kt:69)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)


```

**Comment by aakash1313** [comment]
This seems to be happening when the emulator is running for a long time, restarting the emulator fixes this issue.

**Comment by aakash1313** [comment]
Closing this one, as it could be my emulator was in a bad state.
