### ISSUE TITLE
Java 8 should be supported 

### ISSUE THREAD

**Issue by haci56** [mobile-dev-inc/maestro#289]
Once i execute following command 
**`maestro test -c flow.yaml`**
i get following java exception
`Exception in thread "main" java.lang.UnsupportedClassVersionError: maestro_android/MaestroDriverGrpc has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at maestro.drivers.AndroidDriver.<init>(AndroidDriver.kt:63)
	at maestro.Maestro$Companion.android(Maestro.kt:406)
	at maestro.Maestro$Companion.android$default(Maestro.kt:405)
	at maestro.cli.util.MaestroFactory.createAndroid(MaestroFactory.kt:56)
	at maestro.cli.util.MaestroFactory.autoDetectPlatform(MaestroFactory.kt:73)
	at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:34)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:58)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:30)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:94)`
It seems that you have compiled project in Java 11 but there are many users that uses the lower versions
`49 = Java 5
50 = Java 6
51 = Java 7
52 = Java 8
53 = Java 9
54 = Java 10
55 = Java 11
56 = Java 12
57 = Java 13
58 = Java 14
59 = Java 15
60 = Java 16
61 = Java 17
62 = Java 18
63 = Java 19`
So Java 7, 8, 9, 10 support would be great

**Comment by dmitry-zaitsev** [comment]
Updating your local machine to Java 11 (or higher) is comparatively trivial, so there are currently no plans to support older Java versions.
