### ISSUE TITLE
Running a repeat loop crashes Maestro

### ISSUE THREAD

**Issue by TheBishopOfSoho** [mobile-dev-inc/maestro#303]
Im getting the following error when trying to repeat an action in a test (Ive replaced the actiual app id with a dummy value):

`
 java.io.IOException: Shell command failed (run-as my.app.id find -type d):
run-as: package not debuggable: my.app.id

        at maestro.android.AndroidAppFiles.shell(AndroidAppFiles.kt:75)
        at maestro.android.AndroidAppFiles.listRemoteFiles(AndroidAppFiles.kt:66)
        at maestro.android.AndroidAppFiles.pull(AndroidAppFiles.kt:19)
        at maestro.drivers.AndroidDriver.pullAppState(AndroidDriver.kt:201)
        at maestro.Maestro.pullAppState(Maestro.kt:81)
        at maestro.orchestra.Orchestra.runInitFlow(Orchestra.kt:96)
        at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:98)
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:32)
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:29)
        at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:116)
        at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:29)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:60)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:30)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at maestro.cli.AppKt.main(App.kt:94)
`
The test that caused this is here (note all the steps in the init file work fine:

appId: my.app.id
initFlow: valid_user_signin.yml
---
- repeat:
    times: 3
    commands:
        - tapOn: "Settings"
        - scroll
        - back

**Comment by TheBishopOfSoho** [comment]
Sorry, formatting is not working for the latter block
