### ISSUE TITLE
`PatternSyntaxException: Illegal repetition near index 0` - runFlow when visible based on env variable

### ISSUE THREAD

**Issue by lgawin** [mobile-dev-inc/maestro#328]
I'm working with `1.11.0` release and env variables inlining feature introduced there but I have some problem.
I wanted to run some sub flow conditionally based on variable, so my very simple setup is like this:
```yaml
# flow.yaml

appId: "com.example.myfirstapp"
env:
    CHECK: "some text"
---
- launchApp
- runFlow:
    when:
        visible: ${CHECK}
    file: sub_flow.yaml
```

```yaml
# sub_flow.yaml

appId: "com.example.myfirstapp"
---
- assertVisible: "Hello World!"
```

Unfortunately it fails with:
```
java.util.regex.PatternSyntaxException: Illegal repetition near index 0
${CHECK}                                                  
^                                                         
        at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
        at java.base/java.util.regex.Pattern.closure(Pattern.java:3320)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2213)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1094)
        at kotlin.text.Regex.<init>(Regex.kt:95)          
        at maestro.orchestra.Orchestra.buildFilter(Orchestra.kt:421)
        at maestro.orchestra.Orchestra.findElement(Orchestra.kt:395)
        at maestro.orchestra.Orchestra.evaluateCondition(Orchestra.kt:212)
        at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:198)
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:152)
        at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:111)
        at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:73)
        at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:109)
        at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2$1.invoke(TestRunner.kt:86)
        at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2$1.invoke(TestRunner.kt:85)
        at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:121)
        at maestro.cli.runner.TestRunner.access$runCatching(TestRunner.kt:22)
        at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2.invoke(TestRunner.kt:85)
        at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2.invoke(TestRunner.kt:73)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

Am I doing something wrong?

the latest `1.11.1` still has the same problem

**Comment by dmitry-zaitsev** [comment]
@lgawin I just realised that conditions (`when`) do not support env variables of any kind in them yet (even prior to 1.11.1). We are going to fix it by Monday
