### ISSUE TITLE
Unable to call onTap, it throws io.grpc.StatusRuntimeException: UNKNOWN

### ISSUE THREAD

**Issue by senenpalanca97** [mobile-dev-inc/maestro#332]
Hi! When I call onTap when executing `maestro test <flow.yaml> ` it always throws the next error:
```
io.grpc.StatusRuntimeException: UNKNOWN                         
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at maestro_android.MaestroDriverGrpc$MaestroDriverBlockingStub.tap(MaestroDriverGrpc.java:277)
        at maestro.drivers.AndroidDriver.tap(AndroidDriver.kt:209)
        at maestro.Maestro.tap(Maestro.kt:188)                  
        at maestro.Maestro.tap(Maestro.kt:147)                  
        at maestro.orchestra.Orchestra.tapOnElement(Orchestra.kt:358)
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:133)
        at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:111)
        at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:73) 
        at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:109)
        at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2$1.invoke(TestRunner.kt:86)
	at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2$1.invoke(TestRunner.kt:85)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:121)
	at maestro.cli.runner.TestRunner.access$runCatching(TestRunner.kt:22)
	at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2.invoke(TestRunner.kt:85)
	at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2.invoke(TestRunner.kt:73)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```
My yaml looks like this: 
```
 appId: <com.package.package>
---
- launchApp
- extendedWaitUntil:
    visible: <Text>
    timeout: 10000
- tapOn: <text>
```

I've search but I couldn't find anything related to the exception. 
Thank you for the help!

**Comment by dmitry-zaitsev** [comment]
@senenpalanca97 what Android API version are you using on your device?

**Comment by senenpalanca97** [comment]
I have Android 12 and API version 31. Thank you for answering so quickly!

**Comment by anandcpanchal** [comment]
Hi Folks,
+1 to the above issue.
I am facing exactly the same issue reproducible with the same steps and currently using Android 11 with API version 30 (Physical device).

`io.grpc.StatusRuntimeException: UNKNOWN      
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at maestro_android.MaestroDriverGrpc$MaestroDriverBlockingStub.tap(MaestroDriverGrpc.java:277)                                     
        at maestro.drivers.AndroidDriver.tap(AndroidDriver.kt:209)
        at maestro.Maestro.tap(Maestro.kt:188)
        at maestro.Maestro.tap(Maestro.kt:147)
        at maestro.orchestra.Orchestra.tapOnElement(Orchestra.kt:358)
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:133)
        at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:111)
        at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:73)
        at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:109)
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:34)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:31)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:121)
	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:31)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:65)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:31)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:97)`

**Comment by anandcpanchal** [comment]
Update: Tested with another physical device running Android 12 and API version 31. It is working on it.

**Comment by jonekdahl** [comment]
We're also seeing the same error on the emulator with an Android 12, API 31 device.

Emulator version:  31.3.13.0 (build_id 9189900

```
io.grpc.StatusRuntimeException: UNKNOWN                       
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at maestro_android.MaestroDriverGrpc$MaestroDriverBlockingStub.viewHierarchy(MaestroDriverGrpc.java:270)
        at maestro.drivers.AndroidDriver.contentDescriptor(AndroidDriver.kt:254)
        at maestro.ViewHierarchy$Companion.from-c1iYVAs(ViewHierarchy.kt:28)
        at maestro.Maestro.viewHierarchy-prqvCes(Maestro.kt:278)
        at maestro.Maestro.waitForAppToSettle-prqvCes(Maestro.kt:317)
        at maestro.Maestro.tap(Maestro.kt:190)                
        at maestro.Maestro.tap(Maestro.kt:147)                
        at maestro.orchestra.Orchestra.tapOnElement(Orchestra.kt:358)
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:133)
        at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:111)
        at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:73)
        at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:109)
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:34)
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:31)
        at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:121)
        at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:31)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:65)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:31)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058) 
        at maestro.cli.AppKt.main(App.kt:97)  
     ```

**Comment by migueldaipre** [comment]
i am facing the same problem in Poco F3 (Android 12) (Physical device).

**Comment by Manojrealtime-innovations** [comment]
> I have Android 12 and API version 31. Thank you for answering so quickly! Update: I've replaced my physic phone to an emulator and it seems to work pretty well with api 30

What was the problem and why you changed the device? Is there it was because of specific device?

**Comment by tajchert** [comment]
I have the same issue with the emulator Android API 33 arm64-v8a:
```
io.grpc.StatusRuntimeException: UNKNOWN at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) at maestro_android.MaestroDriverGrpc$MaestroDriverBlockingStub.viewHierarchy(MaestroDriverGrpc.java:376) at maestro.drivers.AndroidDriver.contentDescriptor(AndroidDriver.kt:252) at maestro.Maestro$findElementWithTimeout$1.invoke(Maestro.kt:344) at maestro.Maestro$findElementWithTimeout$1.invoke(Maestro.kt:343) at maestro.utils.MaestroTimer.withTimeout(MaestroTimer.kt:16) at maestro.Maestro.findElementWithTimeout(Maestro.kt:343) at maestro.orchestra.Orchestra.findElement(Orchestra.kt:646) at maestro.orchestra.Orchestra.evaluateCondition(Orchestra.kt:374) at maestro.orchestra.Orchestra.assertConditionCommand(Orchestra.kt:204) at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:174) at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:443) at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:358) at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:185) at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:443) at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:358) at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:185) at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:443) at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:358) at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:185) at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:137) at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:91) at maestro.orchestra.Orchestra.runFlow$default(Orchestra.kt:72) at maestro.cli.runner.TestSuiteInteractor.runFlow(TestSuiteInteractor.kt:134) at maestro.cli.runner.TestSuiteInteractor.runTestSuite(TestSuiteInteractor.kt:65) at maestro.cli.runner.TestSuiteInteractor.runTestSuite(TestSuiteInteractor.kt:34) at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:115) at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:97) at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:84) at maestro.cli.command.TestCommand.call(TestCommand.kt:97) at maestro.cli.command.TestCommand.call(TestCommand.kt:39) at picocli.CommandLine.executeUserObject(CommandLine.java:1933) at picocli.CommandLine.access$1200(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332) at picocli.CommandLine$RunLast.handle(CommandLine.java:2326) at picocli.CommandLine$RunLast.handle(CommandLine.java:2291) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159) at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22) at picocli.CommandLine.execute(CommandLine.java:2058) at maestro.cli.AppKt.main(App.kt:122)
```

**Comment by tajchert** [comment]
In my case, it might be an issue with the emulator state. Removing the emulator and creating it (same spec) as before seems to solve it (at least I cannot replicate it now).

**Comment by migueldaipre** [comment]
Hey, I captured my workflow and error

https://user-images.githubusercontent.com/21174859/213335446-58dcf416-547c-4c71-854b-96481d5e3bc4.mp4



[maestro.log](https://github.com/mobile-dev-inc/maestro/files/10452656/maestro.log)
[system_info.log](https://github.com/mobile-dev-inc/maestro/files/10452657/system_info.log)

**Comment by axelniklasson** [comment]
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on Maestro since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues, please open a new issue with reproduction steps. Thanks again for using maestro!
