### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: java.io.InputStream.readAllBytes()

### ISSUE THREAD

**Issue by GainLee** [mobile-dev-inc/maestro#337]
Error in my app and sample

maestro test android-flow.yaml
Exception in thread "main" java.lang.NoSuchMethodError: java.io.InputStream.readAllBytes()[B
	at maestro.cli.device.ios.Simctl.list(Simctl.kt:14)
	at maestro.cli.device.DeviceService.listIOSDevices(DeviceService.kt:164)
	at maestro.cli.device.DeviceService.listDevices(DeviceService.kt:124)
	at maestro.cli.device.DeviceService.listConnectedDevices(DeviceService.kt:114)
	at maestro.cli.device.PickDeviceInteractor.pickDeviceInternal(PickDeviceInteractor.kt:33)
	at maestro.cli.device.PickDeviceInteractor.pickDevice(PickDeviceInteractor.kt:14)
	at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:35)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:63)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:31)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:97)

**Comment by anandcpanchal** [comment]
+1
Getting exact same error 

Exception in thread "main" java.lang.NoSuchMethodError: java.io.InputStream.readAllBytes()[B
        at maestro.cli.device.ios.Simctl.list(Simctl.kt:14)
        at maestro.cli.device.DeviceService.listIOSDevices(DeviceService.kt:164)
        at maestro.cli.device.DeviceService.listDevices(DeviceService.kt:124)
        at maestro.cli.device.DeviceService.listConnectedDevices(DeviceService.kt:114)
        at maestro.cli.device.PickDeviceInteractor.pickDeviceInternal(PickDeviceInteractor.kt:33)
        at maestro.cli.device.PickDeviceInteractor.pickDevice(PickDeviceInteractor.kt:14)
        at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:35)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:63)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:31)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at maestro.cli.AppKt.main(App.kt:97)

**Comment by amanjeetsingh150** [comment]
Hey folks @anandcpanchal @GainLee , can you post your java version with `java -v`. Right now maestro works with java 11 can you try setting up java 11 in your path and then try executing maestro commands.

**Comment by anandcpanchal** [comment]
@amanjeetsingh150 Thanks for your response. 
I am currently using **java version 8.0.332-zulu**. Will try Java 11 and update. Could you please specify the exact java version that you are using?

**Comment by amanjeetsingh150** [comment]
I have following java version:

```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

**Comment by anandcpanchal** [comment]
Thanks @amanjeetsingh150! 
I updated to java 11 and now issue is resolved.

**Comment by amanjeetsingh150** [comment]
Hey, @GainLee can you also try with java 11. Feel free to re-open the issue if you face the same error.
