### ISSUE TITLE
Test not running

### ISSUE THREAD

**Issue by Nimade42** [mobile-dev-inc/maestro#375]
Hello I am testing Maestro and I can't manage to run it. 

I created this simple yaml file:

# test.yaml

appId: com.maptitebalise.MPB
---
- launchApp
- tapOn: "Tous mes traceurs"

Then tried to run it with command maestro test test.yaml but i have this error every time:

Exception in thread "main" java.lang.NoSuchMethodError: java.io.InputStream.readAllBytes()[B
	at maestro.cli.device.ios.Simctl.list(Simctl.kt:14)
	at maestro.cli.device.DeviceService.listIOSDevices(DeviceService.kt:181)
	at maestro.cli.device.DeviceService.listDevices(DeviceService.kt:141)
	at maestro.cli.device.DeviceService.listConnectedDevices(DeviceService.kt:131)
	at maestro.cli.device.PickDeviceInteractor.pickDeviceInternal(PickDeviceInteractor.kt:33)
	at maestro.cli.device.PickDeviceInteractor.pickDevice(PickDeviceInteractor.kt:14)
	at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:35)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:63)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:31)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:100)

I tried with a physical device et two different emulator same result. I reproduced this error first in 1.11.0 and in last version 1.13.0

**Comment by Nimade42** [comment]
Sure:

java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)
