### ISSUE TITLE
Pass device id to maestro test

### ISSUE THREAD

**Issue by edgarlealbd** [mobile-dev-inc/maestro#431]
Sometimes I have more than one device connected to my Mac, and Maestro will ask for the number of the device.

I want to add a `-d` | `--device` to send Maestro the ID of the device that I want to run. Note that here we should use the unique device ID, just like Flutter does with `flutter run -d DEVICE_ID`.

It should look something like this:
```
maestro test -d 296BA331-027F-4832-845D-520B186D717E
maestro test --device 296BA331-027F-4832-845D-520B186D717E
```

**Comment by dmitry-zaitsev** [comment]
In fact, this is already possible :) You can send either the emulator name or simulator UDID

**Comment by alteral** [comment]
Just to confirm, I see this argument exists on the root level [here](https://github.com/mobile-dev-inc/maestro/blob/main/maestro-cli/src/main/java/maestro/cli/App.kt#L71), but:

❯ `maestro --udid="9E79ADD3-9558-4DCE-87EF-B9245D22434F" test flow.yaml` leads to:
```bash
com.github.michaelbull.result.UnwrapException: kotlin.Unit io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at maestro.drivers.IOSDriver.open(IOSDriver.kt:54)
	at maestro.Maestro$Companion.ios(Maestro.kt:450)
	at maestro.Maestro$Companion.ios(Maestro.kt:445)
	at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:49)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:74)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:36)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:111)
```

❯ `maestro test --udid="9E79ADD3-9558-4DCE-87EF-B9245D22434F" flow.yaml` leads to:
```bash
Unknown option: '--udid=9E79ADD3-9558-4DCE-87EF-B9245D22434F'
Usage: maestro test [-c] [--format=<format>] [--output=<output>] [-e=<String=String>]... <flowFile>
      <flowFile>
  -c, --continuous
  -e, --env=<String=String>

      --format=<format>
      --output=<output>
```

All works fine when starting maestro without these arguments: `maestro test flow.yaml`

**Comment by rohan20** [comment]
@dmitry-zaitsev Could you please clarify how to make this work?
