### ISSUE TITLE
Fatal error when using environment variables with apostrophes on Android and maestro >= 1.15.0

### ISSUE THREAD

**Issue by edgarlealbd** [mobile-dev-inc/maestro#448]
When I add the character `'` as an environment variable on `maestro test`, I get the following error:

 <details>
  <summary>Click to expand</summary>
<p>

  ```
org.mozilla.javascript.EvaluatorException: missing ; before statement (inline-script#1)
        at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:79)
        at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:66)
        at org.mozilla.javascript.Parser.addError(Parser.java:257)
        at org.mozilla.javascript.Parser.reportError(Parser.java:336)
        at org.mozilla.javascript.Parser.reportError(Parser.java:327)
        at org.mozilla.javascript.Parser.reportError(Parser.java:320)
        at org.mozilla.javascript.Parser.autoInsertSemicolon(Parser.java:1279)
        at org.mozilla.javascript.Parser.statementHelper(Parser.java:1254)
	at org.mozilla.javascript.Parser.statement(Parser.java:1104)
	at org.mozilla.javascript.Parser.parse(Parser.java:632)
	at org.mozilla.javascript.Parser.parse(Parser.java:562)
	at org.mozilla.javascript.Context.parse(Context.java:2470)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2401)
	at org.mozilla.javascript.Context.compileString(Context.java:1369)
	at org.mozilla.javascript.Context.compileString(Context.java:1357)
	at org.mozilla.javascript.Context.evaluateString(Context.java:1135)
	at maestro.js.JsEngine.evaluateScript(JsEngine.kt:97)
	at maestro.js.JsEngine.evaluateScript$default(JsEngine.kt:69)
	at maestro.orchestra.Orchestra.defineVariablesCommand(Orchestra.kt:238)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:186)
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:136)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:90)
	at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:118)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:33)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:29)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:120)
	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:29)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:108)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:36)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:109)
```
</p>
</details>

### 2. Have an emulator up and running.
Here are the commands to create the image/SDK I'm using on my Mac M1 Max Machine to reproduce the error. Haven't tested on any other Android API/SDK,

<details>
  <summary>If you're using a computer with ARM architecture</summary>
<p>
``` bash
echo y | sdkmanager "system-images;android-33;google_apis_playstore;arm64-v8a"
echo no | avdmanager create avd -n emulator -k "system-images;android-33;google_apis_playstore;arm64-v8a" --device "pixel_6" --force
</p>
</details>
<details>
  <summary>If you're using a computer with x86_64 architecture</summary>
<p>
``` bash
echo y | sdkmanager "system-images;android-33;google_apis;x86_64"
echo no | avdmanager create avd -n emulator -k "system-images;android-33;google_apis;x86_64" --force
```
</p>
</details>

### 3. Boot the emulator
You can do it with Android Studio or any preferred tool.

### 4. Create the file `test.yaml` with the following content:

``` yaml
appId: com.android.settings
---
- pressKey: home
- launchApp
```

### 5. Run maestro test
Use the following command:
```
maestro test -e APOSTROPHE_VAR="Foo's" test.yaml
```

Video evidence:
https://user-images.githubusercontent.com/97473744/204572895-4a774bdc-6eee-4463-97b2-f626107bdad3.mov

**Comment by axelniklasson** [comment]
Hi there @edgarlealbd! I just tried this on `1.27.0` and I was able to run a flow with `maestro test -e VAR_NAME="Foo's" ...`, so please try [upgrading to the latest version of maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli) and let us know if this issue still persists? Thanks!
