### ISSUE TITLE
"eraseText" cannot clear an edittext

### ISSUE THREAD

**Issue by RobinCaroff** [mobile-dev-inc/maestro#495]
## Description

After editing an edittext with wrong data I try to go back to the edittext and remove its content before inputting a new content.

### Problem

When selecting the edittext, the cursor is placed at the middle of the EditText and the `eraseText` instruction only removes what's on the left of the cursor.

### Environment

Pixel 3a / Android 12
Maestro 1.17.2

### Steps to reproduce

```
- tapOn:
    id: "edittext_signup_email"
- inputText: "invalidemail.fr"
- tapOn:
    id: "some_other_view"
- tapOn:
    id: "edittext_signup_email"
- eraseText
- inputText: "valid@email.fr"
```

_In case you cannot reproduce try to use a very long initial input._

### Expected result

The EditText should contain "valid@email.fr"

### Observed result

The EditText contains "valid@email.fr.fr" <-- the end of the previous input remains.

### Temporary fix

As a temporary fix, I select the Edittext and `eraseText` twice before editing it:

```
- tapOn:
    id: "edittext_signup_email"
- eraseText
- tapOn:
    id: "edittext_signup_email"
- eraseText
- inputText: "valid@email.fr"
```

**Comment by ArthurSav** [comment]
We have made a lot of improvements and fixes since, can you upgrade to the latest version of Maestro and try again? If you still experience issues, we can re-open this. Thanks again for using Maestro!

**Comment by phuchuynhStrong** [comment]
@ArthurSav I still experience this issue with version 1.27.0 

## Environment
Pixel 6a / Android 13
Maestro 1.27.0

## Steps to reproduce
```
- launchApp
- assertVisible:
    text: "Sign in"
- tapOn: "Email"
- eraseText
```

**Comment by aakashfmk** [comment]
Hi, 
is there any update on this? I'm still facing this issue on Maestro 1.28.0

**Comment by ferdy-roz** [comment]
Also running into this on iOS, only on maestro cloud. Please provide some guidance here -- I am trying to onboard our process onto this tool but this makes the cloud product unusable

**Comment by TheLastProject** [comment]
Can confirm this is still a thing on 1.33.0.

My workaround is to use `repeat` to at least lower the amount of code (which is really just a slightly more DRY version of @RobinCaroff's original workaround, thank!):
```
- repeat:
  times: 2
  commands:
    - tapOn: <field that needs to be erased>
    - eraseText
```

**Comment by hormesiel** [comment]
Still running into the same problem with Maestro CLI v1.38.1 when executing tests on a physical Android device (OnePlus Nord, Android 12, connected to Windows 11 via USB).

**Comment by Fishbowler** [comment]
There's some workarounds here.

One is:
```
- tapOn:
    id: myTextField
    point: "95%,50%"
- eraseText
```

This will erase more text than the simple version, by setting the text caret further along the input.

Another is to write a flow that does a longpress on the text field, hits Select All, then `eraseText: 1`.

**Comment by Fishbowler** [comment]
Future folks: take a look at #1777 for more info - there's a bunch of good conversation there on other workarounds.

**Comment by renanmav** [comment]
we're observing this on Android only with shards

```
- retry:
    maxRetries: 3
    commands:
      - tapOn:
          id: email-input
      - eraseText
      - inputText: '${MAESTRO_E2E_TEST_EMAIL_PREFIX}.${MAESTRO_E2E_TEST_EMAIL_DOMAIN}'
      - extendedWaitUntil:
          visible:
            id: error-message
          timeout: 5000
- assertVisible: Please enter a valid email address
- assertVisible:
    id: onboarding-signup-button
    enabled: false
- eraseText
```

this becomes flaky when sharding, with this error:

```
[shard 2] maestro.android.DeviceServerDiedException: Device server died during 'eraseText' on emulator-5556 (120008ms since last byte, connection age 166601ms): StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 119.999798329s. [closed=[], open=[[remote_addr=/127.0.0.1:36535]]]
	at maestro.android.AndroidDeviceConnection.onGrpcDeath(AndroidDeviceConnection.kt:309)
	at maestro.android.AndroidDeviceConnection.mapTransport(AndroidDeviceConnection.kt:296)
	at maestro.android.AndroidDeviceConnection.execute(AndroidDeviceConnection.kt:121)
	at maestro.drivers.AndroidDriver.eraseText$lambda$53(AndroidDriver.kt:684)
	at maestro.utils.Metrics.measured(Metrics.kt:48)
	at maestro.drivers.AndroidDriver.eraseText(AndroidDriver.kt:683)
	at maestro.Maestro.eraseText$lambda$52(Maestro.kt:724)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:48)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:40)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 119.999798329s. [closed=[], open=[[remote_addr=/127.0.0.1:36535]]]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:275)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:256)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:169)
	at maestro_android.MaestroDriverGrpc$MaestroDriverBlockingStub.eraseAllText(MaestroDriverGrpc.java:775)
	at maestro.drivers.AndroidDriver.eraseText$lambda$53$lambda$52(AndroidDriver.kt:685)
	at maestro.android.AndroidDeviceConnection.execute(AndroidDeviceConnection.kt:119)
	... 15 more
```

**Comment by Fishbowler** [comment]
@renanmav Connectivity errors whilst sharding are likely unrelated to this issue.

**Comment by renanmav** [comment]
@Fishbowler sorry if this is a bit out of scope for this issue, but this seems to have degraded on Android with sharding after release v2.7.0 (from 2 days ago).

At first I thought it was just with `eraseText` instruction, but we're seeing `DeviceServerDiedException` with `inputText` as well.

```
[shard 4] maestro.android.DeviceServerDiedException: Device server died during 'inputText' on emulator-5560 (120009ms since last byte, connection age 167801ms): StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 119.999782510s. [closed=[], open=[[remote_addr=/127.0.0.1:38661]]]
```

**Comment by Fishbowler** [comment]
Definitely not this issue. I suggest you put together all of your bits and open a new issue. Include whether you can reproduce this only when sharding. Include as much information as possible.
