### ISSUE TITLE
TimeoutException

### ISSUE THREAD

**Issue by FunnyDevs** [mobile-dev-inc/maestro#510]
Hello,
i'm using wsl with adb through wifi. When i try to launch a test i obtain this exception

java.util.concurrent.TimeoutException
        at dadb.forwarding.TcpForwarder.waitFor(TcpForwarder.kt:153)
        at dadb.forwarding.TcpForwarder.start(TcpForwarder.kt:49)
        at dadb.Dadb$DefaultImpls.tcpForward(Dadb.kt:221)
        at dadb.adbserver.AdbServerDadb.tcpForward(AdbServer.kt:118)
        at maestro.drivers.AndroidDriver.allocateForwarder(AndroidDriver.kt:107)
        at maestro.drivers.AndroidDriver.open(AndroidDriver.kt:98)
        at maestro.Maestro$Companion.android(Maestro.kt:510)
        at maestro.Maestro$Companion.android$default(Maestro.kt:508)
        at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:40)

**Comment by FunnyDevs** [comment]
Yes, it works. Thank you
