### ISSUE TITLE
Maestro Android driver did not start up in time

### ISSUE THREAD

**Issue by nikolapopovic** [mobile-dev-inc/maestro#553]
When executing test again Android Emulator, getting following error:

```
java.util.concurrent.TimeoutException: Maestro Android driver did not start up in time
	at maestro.drivers.AndroidDriver.awaitLaunch(AndroidDriver.kt:128)
	at maestro.drivers.AndroidDriver.open(AndroidDriver.kt:92)
	at maestro.Maestro$Companion.android(Maestro.kt:498)
	at maestro.Maestro$Companion.android$default(Maestro.kt:496)
	at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:43)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:84)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:40)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:119)
```
I'm using following:

- macOS Monterey 12.6
- Apple M1 Pro chip
- Maestro 1.18.3
- openjdk 11.0.17 2022-10-18 LTS
- OpenJDK Runtime Environment Zulu11.60+19-CA (build 11.0.17+8-LTS)
- OpenJDK 64-Bit Server VM Zulu11.60+19-CA (build 11.0.17+8-LTS, mixed mode)

**Comment by testifyqa** [comment]
I am sadly also seeing this, any updates?

**Comment by MrRahulR** [comment]
I was facing same issue and I noticed something in the Installed Applications in device, Maestro didn't removed the default apps `dev.mobile.maestro` and `dev.mobile.maestro.test` while clean up .

Try remove these apps manually and reexecute your tests, it will work! 

Cheers!

**Comment by testifyqa** [comment]
So I believe my issue is I am trying to run `maestro` on a payments terminal that uses a special flavour of Android called PayDroid.

I just tried on a normal Samsung Galaxy phone I have and it worked fine.

**Comment by MrRahulR** [comment]
Okay, I see, by any chance do you have Appium apps installed on your device `io.appium.uiautomator2.server`, `io.appium.uiautomator2.server.test`.

I tried `maestro studio` and it failed but later when I uninstalled those apps and rerun - now it worked. I think Maestro's internal applications are clashing with the Appium internal apps.

Let's see if it works for you!

**Comment by testifyqa** [comment]
Will double check tomorrow morning but I don't think so as we use native Android Espresso framework.

**Comment by axelniklasson** [comment]
Hi there folks! Could you try [upgrading to the latest version of maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli) and let us know if this issue still persists? Thanks!

**Comment by axelniklasson** [comment]
I'll go ahead and close this out for now. Please file a new bug report [here](https://github.com/mobile-dev-inc/maestro/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BMaestro+version%2C+e.g.+v1.2.3%5D) if you are still experiencing issues!

**Comment by axelniklasson** [comment]
There is a PR https://github.com/mobile-dev-inc/maestro-docs/pull/10 that adds configurable startup timeout that might also resolve this issue once released.
