### ISSUE TITLE
Maestro CLI fails to find free port when launching studio without elevated permissions

### ISSUE THREAD

**Issue by supoved** [mobile-dev-inc/maestro#557]
I have port `9999` in use by one of docker containers. 

When executing `maestro studio` command it fails with following exception:
```
java.net.BindException: Address already in use (Bind failed)
        at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:452)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:395)
        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:257)
        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:149)
        at maestro.cli.command.StudioCommand.getFreePort(StudioCommand.kt:62)
        at maestro.cli.command.StudioCommand.call(StudioCommand.kt:39)
        at maestro.cli.command.StudioCommand.call(StudioCommand.kt:19)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at maestro.cli.AppKt.main(App.kt:119)
```

`getFreePort` doesnt enumerate ports and fails on the first one, unless command is run with elevated permissions, i.e. `sudo maestro studio`.

Few thoughts on this:
- the error is not very verbose, doesnt even say with port its trying to use
- Its not great to require elevated permissions for such small thing
- it would be great to have ability to manually define or configure port to use

macOS Ventura 13.0.1 (22A400)
Apple M1 Pro chip
Maestro 1.18.3

**Comment by axelniklasson** [comment]
Hi there @supoved! This has been resolved in a more recent version of maestro. Please [upgrade to the latest version of maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli) and let us know if this issue still persists? Thanks!
