### ISSUE TITLE
`maestro record` throws exception: No route to host

### ISSUE THREAD

**Issue by b099l3** [mobile-dev-inc/maestro#570]
Is there a size limit to the `record` command? 

I was testing this out to show my team. Ran a short example (Open app, click on button) to see what it looked like, then ran one of our proper flows but hit this error when "Uploading raw files for render..." :

It looks like it is a connection issue? but my network is fine and I have ran it three times with the same result, sometimes the progress is further. Shorter flows do work tho

```
Rendering your video. This usually takes a couple minutes...

Uploading raw files for render...
████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░
java.net.NoRouteToHostException: No route to host
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:579)
        at java.base/sun.nio.ch.Net.connect(Net.java:568)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at maestro.cli.api.ApiClient.render(ApiClient.kt:182)
        at maestro.cli.command.RecordCommand.call(RecordCommand.kt:103)
        at maestro.cli.command.RecordCommand.call(RecordCommand.kt:38)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at maestro.cli.AppKt.main(App.kt:119)
        Suppressed: java.net.SocketException: Broken pipe
                at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
                at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
                at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
                at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035)
                at java.base/sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:345)
                at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1298)
                at okio.OutputStreamSink.write(JvmOkio.kt:57)
                at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
                at okhttp3.internal.http1.Http1ExchangeCodec$KnownLengthSink.write(Http1ExchangeCodec.kt:271)
                at okio.ForwardingSink.write(ForwardingSink.kt:29)
                at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
                at okio.ForwardingSink.write(ForwardingSink.kt:29)
                at maestro.cli.api.ApiClient$observable$1$writeTo$forwardingSink$1.write(ApiClient.kt:324)
                at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
                at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:194)
                at okhttp3.RequestBody$Companion$asRequestBody$1.writeTo(RequestBody.kt:167)
                at maestro.cli.api.ApiClient$observable$1.writeTo(ApiClient.kt:330)
                at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
                at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
                at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
                ... 21 more
```

**Comment by janyk** [comment]
Getting similar issues trying to record, let me know if there's any info I can help add to reproduce!

**Comment by ben-milanko** [comment]
I'm also seeing something similar, it looks like an issue with the server:

```
Uploading raw files for render...
...
java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2600:1f16:d83:1201:0:0:6e:4:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at maestro.cli.api.SystemInformationInterceptor.intercept(ApiClient.kt:481)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at maestro.cli.api.ApiClient.render(ApiClient.kt:182)
	at maestro.cli.command.RecordCommand$call$1.invoke(RecordCommand.kt:100)
	at maestro.cli.command.RecordCommand$call$1.invoke(RecordCommand.kt:72)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:98)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:53)
	at maestro.cli.command.RecordCommand.call(RecordCommand.kt:72)
	at maestro.cli.command.RecordCommand.call(RecordCommand.kt:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:124)
```

**Comment by axelniklasson** [comment]
Thanks for reporting this! Are you still experiencing these issues? Is it on iOS, Android or both?

**Comment by TheAlmightyBob** [comment]
@axelniklasson I see the same error as @ben-milanko on both iOS and Android, however I suspect it's unrelated to the original issue (different error, fails almost immediately, fails even for a very short recording)

**Comment by axelniklasson** [comment]
@TheAlmightyBob Strange, I'm not able to reproduce this.. If you run `ping maestro-record.ngrok.io` from your shell, are you able to reach the server?

**Comment by axelniklasson** [comment]
@TheAlmightyBob Hm, weird to hear that it doesn't work for you. Could you share the error message?

**Comment by TheAlmightyBob** [comment]
@axelniklasson The error message is exactly what @ben-milanko already shared, but I do have slightly more of a stack trace in case that helps:

```
java.net.ConnectException: Failed to connect to maestro-record.ngrok.io/2600:1f16:d83:1201:0:0:6e:1:443
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at maestro.cli.api.SystemInformationInterceptor.intercept(ApiClient.kt:487)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at maestro.cli.api.ApiClient.render(ApiClient.kt:185)
        at maestro.cli.command.RecordCommand$call$1.invoke(RecordCommand.kt:100)
        at maestro.cli.command.RecordCommand$call$1.invoke(RecordCommand.kt:72)
        at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:99)
        at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:57)
        at maestro.cli.command.RecordCommand.call(RecordCommand.kt:72)
        at maestro.cli.command.RecordCommand.call(RecordCommand.kt:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at maestro.cli.AppKt.main(App.kt:136)
        Suppressed: javax.net.ssl.SSLException: Connection reset
                at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
                at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
                at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
                at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
                at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:144)
                at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1418)
                at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1324)
                at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
                at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
                at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
                at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
                at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
                ... 32 more
                Suppressed: java.net.SocketException: Broken pipe (Write failed)
                        at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
                        at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
                        at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
                        at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
                        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:380)
                        ... 42 more
        Caused by: java.net.SocketException: Connection reset
                at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
                at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
                at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
                at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
                at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
                at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
                ... 39 more
Caused by: java.net.ConnectException: No route to host (connect failed)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        ... 33 more
```

(also, since @b099l3 's problem was resolved, let me know if you'd rather I create a new issue for this. I only commented here because @ben-milanko had already done so with the same error)

**Comment by axelniklasson** [comment]
Thanks for the context @TheAlmightyBob! If you would be able to file a new issue with as much details as possible and steps to reproduce that would be much appreciated so we don't clutter this issue too much. Thanks!
