### ISSUE TITLE
runScript throws "missing : after property id"

### ISSUE THREAD

**Issue by dansimau** [mobile-dev-inc/maestro#576]
I am trying to execute an external script to acquire a phone number from Twilio before my test runs.

**Configuration**

```yaml
// flow.yaml

appId: com.myapp

---

- runScript: scripts/get-phone-number.js
```

```js
// scripts/get-phone-number.js

const {execSync} = require("child_process");

function exec(command) {
  return execSync(command, {encoding: "utf-8"}).trim();
}

// Lock an available phone number for testing
output.testPhoneNumber = exec(
  "../../../../backend/go/bin/app twilio numbers acquire",
);
```

**Result**

```
$ maestro test signup.yaml
Running on iPhone 14 - iOS 16.2 - 560E417E-7C9D-41C6-A896-43B7F869EDE8
Waiting for idb service to start..
Waiting for Simulator to boot..
Waiting for successful taps
Simulator ready

org.mozilla.javascript.EvaluatorException: missing : after property id (scripts/get-phone-number.js#1)
        at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:79)
        at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:66)
        at org.mozilla.javascript.Parser.addError(Parser.java:257)
        at org.mozilla.javascript.Parser.reportError(Parser.java:336)
        at org.mozilla.javascript.Parser.reportError(Parser.java:332)
        at org.mozilla.javascript.Parser.mustMatchToken(Parser.java:473)
        at org.mozilla.javascript.Parser.mustMatchToken(Parser.java:464)
	at org.mozilla.javascript.Parser.plainProperty(Parser.java:3601)
	at org.mozilla.javascript.Parser.objectLiteral(Parser.java:3501)
	at org.mozilla.javascript.Parser.primaryExpr(Parser.java:3049)
	at org.mozilla.javascript.Parser.destructuringPrimaryExpr(Parser.java:3028)
	at org.mozilla.javascript.Parser.variables(Parser.java:2103)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1197)
	at org.mozilla.javascript.Parser.statement(Parser.java:1104)
	at org.mozilla.javascript.Parser.parse(Parser.java:632)
	at org.mozilla.javascript.Parser.parse(Parser.java:562)
	at org.mozilla.javascript.Context.parse(Context.java:2470)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2401)
	at org.mozilla.javascript.Context.compileString(Context.java:1369)
	at org.mozilla.javascript.Context.compileString(Context.java:1357)
	at org.mozilla.javascript.Context.evaluateString(Context.java:1135)
	at maestro.js.JsEngine.evaluateScript(JsEngine.kt:88)
	at maestro.orchestra.Orchestra.runScriptCommand(Orchestra.kt:222)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:190)
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:138)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:92)
	at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:120)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:36)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:32)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:123)
	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:32)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:124)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:40)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:119)
```

**Expected**

I execute it to run the script without error and allow me to use the phone number later in the test.

**Version**

```
$ maestro --version
1.18.3
```

As a side note, it would be great if I could execute a command and get the result directly in maestro without requiring any JavaScript boilerplate. Something like:

```yaml
// flow.yaml

appId: com.myapp

---

- runCommand: ../../bin/app twilio numbers acquire
    id: acquireNumber

- inputText: ${acquireNumber.stdout.trim()}
```

**Comment by dmitry-zaitsev** [comment]
External script execution is not currently supported for safety reasons, as the same configuration should be able to run in cloud without producing side effects.

That said, we would like to hear more about your use case. What are you trying to achieve?

**Comment by dansimau** [comment]
Hey Dmitry 👋 😁 

> What are you trying to achieve?

Two examples:

1. I am doing an end-to-end test of an onboarding flow that involves sending an SMS code to a phone number. I have a pool of phone numbers purchased in Twilio for testing. Before each test run, the test executes an external command to acquire and lock a phone number for the test and query this number to receive the SMS.

    I could work around that by rewriting it in JS I guess.

2. My tests run a local API server (written in Go) that the mobile client communicate with during the test. If I can't execute this then the mobile client will just return errors or I have to somehow deploy the API client somewhere externally accessible for the mobile client to talk to.

I'd say not being able to run or execute external commands before the test run is a bit of a non-starter for me. I can see why it might not be supported on Maestro Cloud but if I'm running it locally or own my own CI system I would expect to be able to do this.

(Even if there were just the ability to pass in data to the test via the CLI then I could wrap the whole maestro execution in another script that runs the commands and then passes the data in, e.g. https://github.com/mobile-dev-inc/maestro/issues/569)

**Comment by testableapple** [comment]
Hey @dmitry-zaitsev, any news on this issue? It's quite an unpleasant limitation for non-MaestroCloud users. It would be great to have this feature 🙂

**Comment by testableapple** [comment]
Alrighty, while this is not supported out of the box on Maestro, I came up with a [workaround](https://testableapple.com/gaining-access-to-command-line-from-maestro/) if anyone's interested.

**Comment by nathanalderson** [comment]
Agreed. Would _really_ love an option to run external tools when not using Maestro Cloud.

**Comment by dansimau** [comment]
I want to share how I solved this issue:
https://gist.github.com/dansimau/6657920a51c83212ebff929f85b5d309

(This builds on the idea from @testableapple.)

Essentially, you gain the ability to run commands in a generic way and parse/access the results in other execution steps.

See an example flow here:
https://gist.github.com/dansimau/6657920a51c83212ebff929f85b5d309#file-example-flow-yaml

Hope this is useful for someone.
