### ISSUE TITLE
maestro studio doest not start if java.awt.Desktop could not handle BROWSE

### ISSUE THREAD

**Issue by fortytool** [mobile-dev-inc/maestro#579]
I am running on Kubuntu 10.22 and it turns out that Java AWT-Toolkit is not developed on QT frameworks anymore.
```
$ maestro studio
Running on QV700JSX1B
╭────────────────────────────────────────────────────────╮
│                                                        │
│   Maestro Studio is running at http://localhost:9999   │
│                                                        │
╰────────────────────────────────────────────────────────╯
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
		at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:380)
		at java.desktop/java.awt.Desktop.browse(Desktop.java:524)
		at maestro.cli.command.StudioCommand.call(StudioCommand.kt:47)
		at maestro.cli.command.StudioCommand.call(StudioCommand.kt:19)
		at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
		at picocli.CommandLine.access$1200(CommandLine.java:145)
		at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
		at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
		at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
		at picocli.CommandLine.execute(CommandLine.java:2058)
		at maestro.cli.AppKt.main(App.kt:119)
```
See:
https://stackoverflow.com/questions/102325/not-supported-platforms-for-java-awt-desktop-getdesktop
https://java-hamster.blogspot.com/2007/06/troubles-with-javaawtdesktop-browse.html

Since the BROWSE is only to ease it to the user and it is not necessary to open the browser by maestro I  created a simple patch. 
```
diff --git a/maestro-cli/src/main/java/maestro/cli/command/StudioCommand.kt b/maestro-cli/src/main/java/maestro/cli/command/StudioCommand.kt
index 92e14e6..eb7d39d 100644
--- a/maestro-cli/src/main/java/maestro/cli/command/StudioCommand.kt
+++ b/maestro-cli/src/main/java/maestro/cli/command/StudioCommand.kt
@@ -44,7 +44,11 @@ class StudioCommand : Callable<Int> {
         println()
         println(message)
         if (Desktop.isDesktopSupported()) {
-            Desktop.getDesktop().browse(URI(studioUrl))
+            try {
+                Desktop.getDesktop().browse(URI(studioUrl))
+            } catch (e: Exception){
+                println("Sorry, I am not able to open your browser.")
+            }
         }
 
         println()
```
Sadly I could not upload the patch as file, github was complaining.

**Comment by dmitry-zaitsev** [comment]
Interesting catch, we will patch it out in the next release 👍
