### ISSUE TITLE
Couldn't close Maestro iOS driver due to gRPC timeout

### ISSUE THREAD

**Issue by arctouch-moisessilva** [mobile-dev-inc/maestro#624]
Hello folks, I just got started using maestro. 
So, following the "Run a sample Flow" section I installed the requirements (including the sample app) and tried to run the _ios-flow test_
The result we can see below. I'm getting this error all the time. Only for iOS _(Android worked perfectly)_ 

Am I doing something wrong?

**My environment is:** 
macOS 12.6.2 (M1)
Simulator 14.2 (986.5)
SimulatorKit 627
CoreSimulator 857.14
Virtual device : iPhone 14 Pro (iOS 16.2)

**spool from execution :** 
maestro test ios-flow.yaml 
Running on iPhone 14 Pro - iOS 16.2 - 1C2CE8C7-9F68-4CCC-9747-FF2C18EB589B
Waiting for idb service to start..
Waiting for Simulator to boot..
Waiting for successful taps
Simulator ready

java.util.concurrent.TimeoutException: Couldn't close Maestro iOS driver due to gRPC timeout
	at ios.idb.IdbIOSDevice.close(IdbIOSDevice.kt:500)
	at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseable.kt:61)
	at maestro.cli.device.DeviceService.startIdbCompanion(DeviceService.kt:106)
	at maestro.cli.device.DeviceService.prepareDevice(DeviceService.kt:73)
	at maestro.cli.device.PickDeviceInteractor.pickDevice(PickDeviceInteractor.kt:26)
	at maestro.cli.session.MaestroSessionManager.selectDevice(MaestroSessionManager.kt:93)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:50)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:97)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:39)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:122)

**Comment by dmitry-zaitsev** [comment]
The fix was landed, it will be published tomorrow
