### ISSUE TITLE
Limit to record size

### ISSUE THREAD

**Issue by idrakimuhamad** [mobile-dev-inc/maestro#635]
What's the limit for `maestro record`, in terms of length or size? I've received multiple time request failed during uploading or during rendering, with error below.

```
Render request failed (413): {"message":"E_REQUEST_ENTITY_TOO_LARGE: request entity too large"}
```

The flow are quite lengthy, around 1-2 minutes. I've tried with a simple screen open, and it able to render and return the download link.

**Comment by walkerdb** [comment]
+1, we're seeing the same with a ~25-step flow that finishes in around a minute.

```
Rendering your video. This usually takes a couple minutes...

Uploading raw files for render...
██████████████████████████████████████████████████
Render request failed (413): {"message":"E_REQUEST_ENTITY_TOO_LARGE: request entity too large"}

```

This is on an M1 Max macbook pro running macOS 13.0

**Comment by idrakimuhamad** [comment]
I've tested in latest version (.5) it seems to be able to render longer flow now.

**Comment by tenhobi** [comment]
I saw somewhere (https://github.com/mobile-dev-inc/maestro/pull/447#discussion_r1034801183) that the recording limit is around 1 minute.

**Comment by idrakimuhamad** [comment]
> I saw somewhere (https://github.com/mobile-dev-inc/maestro/pull/447#discussion_r1034801183) that the recording limit is around 1 minute.

Indeed it did mentioned there. I have tried a medium number of flow, and seems to be successful yesterday after latest update. Will try a longer one later.

**Comment by idrakimuhamad** [comment]
Tested today to run a huge set of flows, around 5 minutes. It throwing an error during generating render.

<details>

```
Running on iPhone 14 - iOS 16.2 - 15822A20-1DB9-4DDB-B8C6-194AC7C3361C

 ║
 ║  > Flow
 ║
 ║    ✅  Launch app "com.x.x.app" with clear state
 ║    ✅  Run splashFlow.yaml
 ║    ✅  Run welcomeFlow.yaml
 ║    ✅  Tap on id: loginSectionButton
 ║    ✅  Run loginScreenFlow.yaml
 ║    ✅  Run dashboardFlow.yaml
 ║    ✅  Tap on id: allAccountSummaryButton
 ║    ✅  Run allAccountsSummaryFlow.yaml
 ║    ✅  Tap on id: tabBarItem, Index: 1
 ║    ✅  Run accountsTabFlow.yaml
 ║    ✅  Tap on id: tabBarItem, Index: 2
 ║    ✅  Run activityTabFlow.yaml
 ║

Rendering your video. This usually takes a couple minutes...

Uploading raw files for render...
██████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░
java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:345)
	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1304)
	at okio.OutputStreamSink.write(JvmOkio.kt:57)
	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
	at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
	at okhttp3.internal.http1.Http1ExchangeCodec$KnownLengthSink.write(Http1ExchangeCodec.kt:271)
	at okio.ForwardingSink.write(ForwardingSink.kt:29)
	at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
	at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
	at okio.ForwardingSink.write(ForwardingSink.kt:29)
	at maestro.cli.api.ApiClient$observable$1$writeTo$forwardingSink$1.write(ApiClient.kt:334)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
	at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:194)
	at okhttp3.RequestBody$Companion$asRequestBody$1.writeTo(RequestBody.kt:167)
	at maestro.cli.api.ApiClient$observable$1.writeTo(ApiClient.kt:340)
	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
	at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at maestro.cli.api.SystemInformationInterceptor.intercept(ApiClient.kt:433)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at maestro.cli.api.ApiClient.render(ApiClient.kt:182)
	at maestro.cli.command.RecordCommand$call$1.invoke(RecordCommand.kt:100)
	at maestro.cli.command.RecordCommand$call$1.invoke(RecordCommand.kt:72)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:97)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:52)
	at maestro.cli.command.RecordCommand.call(RecordCommand.kt:72)
	at maestro.cli.command.RecordCommand.call(RecordCommand.kt:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:122)
	Suppressed: java.net.SocketException: Broken pipe (Write failed)
		... 52 more
```

</details>

Anyway, I guess I'd be keeping record on a smaller test for now. Probably should mentioned the time limit in the doc too.

**Comment by axelniklasson** [comment]
Hi there folks. The maximum duration for `maestro record` is two minutes - thanks for the suggestion to add it to the docs, the [FAQ section](https://maestro.mobile.dev/cli/recording-your-flow#faq) has been updated!
