### ISSUE TITLE
[Maestro 1.21.0] Maestro timing out when typing large strings

### ISSUE THREAD

**Issue by BrentMifsud** [mobile-dev-inc/maestro#677]
We have a method of bypassing the login flow of our app by entering a jwt token.

We fetch the jwt token using a javascript step in our flow.

I noticed that since version 1.21.0, the typing seems to be slower, and its causing that step to time out with the following error:

```
com.github.michaelbull.result.UnwrapException: kotlin.Unit java.net.SocketTimeoutException: timeout                         at maestro.drivers.IOSDriver.inputText(IOSDriver.kt:437)
        at maestro.Maestro.inputText(Maestro.kt:397)                                                                        at maestro.orchestra.Orchestra.inputTextCommand(Orchestra.kt:557)                                                   at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:177)                                                     at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:465)                                                         at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:380)                                                     at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:187)
        at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:138)                                                    at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:92)                                                             at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:120)                                 at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:36)                                        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:32)                                        at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:123)
        at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:32)                                                        at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:154)                                                at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:115)                                                at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:97)                                at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:52)                        at maestro.cli.command.TestCommand.call(TestCommand.kt:115)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:41)                                                          at picocli.CommandLine.executeUserObject(CommandLine.java:1933)                                                     at picocli.CommandLine.access$1200(CommandLine.java:145)                                                            at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)               at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)                                                        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)                                    at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)                                 at picocli.CommandLine.execute(CommandLine.java:2058)                                                               at maestro.cli.AppKt.main(App.kt:122)  
```

**Comment by berikv** [comment]
Hi @BrentMifsud, there is an update to maestro available (1.21.1) that addresses the slower text input. Could you test if the update fixes the issue?

**Comment by BrentMifsud** [comment]
Awesome will check!

**Comment by berikv** [comment]
Ah, I was just a bit too early to tell you. Could you try again, the new release should be available now.

**Comment by berikv** [comment]
Hi @BrentMifsud, did you get a chance to test the latest maestro version?

**Comment by BrentMifsud** [comment]
Hey sorry I've been completely swamped. Will test it later today.

**Comment by BrentMifsud** [comment]
I can confirm its now working on version 1.21.3

**Comment by berikv** [comment]
Thanks for confirming 🙏
