### ISSUE TITLE
TimeOutException on wifi and usb connected device on Linux

### ISSUE THREAD

**Issue by FrancoisG-WIMT** [mobile-dev-inc/maestro#707]
Hi,

I am busy evaluating how Maestro compares against Waldo and whether it could be a viable option for us to test our Android applications with.

However, I can't seem to get my Linux desktop to run maestro studio, even though it works on MacOS against the same Android phone.

```
Running on 192.168.88.29:45667

java.util.concurrent.TimeoutException
	at dadb.forwarding.TcpForwarder.waitFor(TcpForwarder.kt:153)
	at dadb.forwarding.TcpForwarder.start(TcpForwarder.kt:49)
	at dadb.Dadb$DefaultImpls.tcpForward(Dadb.kt:221)
	at dadb.adbserver.AdbServerDadb.tcpForward(AdbServer.kt:118)
	at maestro.drivers.AndroidDriver.allocateForwarder(AndroidDriver.kt:107)
	at maestro.drivers.AndroidDriver.open(AndroidDriver.kt:98)
	at maestro.Maestro$Companion.android(Maestro.kt:545)
	at maestro.Maestro$Companion.android$default(Maestro.kt:538)
	at maestro.cli.session.MaestroSessionManager.createMaestro(MaestroSessionManager.kt:150)
	at maestro.cli.session.MaestroSessionManager.access$createMaestro(MaestroSessionManager.kt:44)
	at maestro.cli.session.MaestroSessionManager$newSession$session$1.invoke(MaestroSessionManager.kt:79)
	at maestro.cli.session.MaestroSessionManager$newSession$session$1.invoke(MaestroSessionManager.kt:78)
	at maestro.cli.db.KeyValueStore.withExclusiveLock(KeyValueStore.kt:37)
	at maestro.cli.session.SessionStore.withExclusiveLock(SessionStore.kt:74)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:78)
	at maestro.cli.command.StudioCommand.call(StudioCommand.kt:36)
	at maestro.cli.command.StudioCommand.call(StudioCommand.kt:18)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:122)
```

Any ideas of where to look for what may be causing it?

Thank you!
[2023-01-30_120824.zip](https://github.com/mobile-dev-inc/maestro/files/10534678/2023-01-30_120824.zip)

**Comment by FrancoisG-WIMT** [comment]
Anything I can do from my end to help diagnose what's going wrong?

**Comment by axelniklasson** [comment]
Hi there @FrancoisG-WIMT, are you still experiencing these issues?

**Comment by FrancoisG-WIMT** [comment]
Not with the latest version 1.27.0 :tada:
