### ISSUE TITLE
Running scrollUntilVisible/scroll on iOS throws exception in certain scenarios

### ISSUE THREAD

**Issue by AlexanderEggers** [mobile-dev-inc/maestro#724]
When running the scrollUntilVisible/scroll on iOS, the maestro CLI is unable to excute the command in certain scenarios and throws the following exception.

We are displaying a bottom sheet integration which is using react navigation to handle the different steps inside the bottom sheet modal.

```
java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:9080
    at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)          
    at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)             
    at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)         
    at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)      
    at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)    at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)                                          at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)                                       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)                                       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at xcuitest.XCTestDriverClient.runningAppId(XCTestDriverClient.kt:69)
	at ios.xctest.XCTestIOSDevice.activeAppId(XCTestIOSDevice.kt:219)
	at ios.xctest.XCTestIOSDevice.contentDescriptor(XCTestIOSDevice.kt:49)
	at ios.LocalIOSDevice.contentDescriptor(LocalIOSDevice.kt:30)
	at maestro.drivers.IOSDriver.contentDescriptor(IOSDriver.kt:175)
	at maestro.ViewHierarchy$Companion.from-c1iYVAs(ViewHierarchy.kt:28)
	at maestro.Maestro.viewHierarchy-prqvCes(Maestro.kt:353)
	at maestro.Maestro.waitForAppToSettle-EoVL2FI(Maestro.kt:396)
	at maestro.Maestro.waitForAppToSettle-EoVL2FI$default(Maestro.kt:395)
	at maestro.Maestro.swipeFromCenter(Maestro.kt:156)
	at maestro.orchestra.Orchestra.scrollUntilVisible(Orchestra.kt:294)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:173)
	at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:463)
	at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:378)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:188)
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:139)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:93)
	at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:120)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:36)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:32)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:123)
	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:32)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:154)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:115)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:96)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:51)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:115)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:41)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:122)
	Suppressed: java.io.IOException: unexpected end of stream on http://localhost:9080/...
		at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202)
		at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
		at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
		... 46 more
	Caused by: java.io.EOFException: \n not found: limit=0 content=…
		at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
		at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
		at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
		... 50 more
	Suppressed: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:9080
		... 53 more
	Caused by: java.net.ConnectException: Connection refused (Connection refused)
		at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
		at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
		at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
		at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
		at java.base/java.net.Socket.connect(Socket.java:609)
		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
		... 52 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	... 52 more
```

**Comment by AartiTew** [comment]
Hi I'm trying to use this function to scroll left but it doesn't seem to work but on Android. I'm not sure what am I doing wrong. 
The test fails at that step.

- scrollUntilVisible:
    element: "Departure"
    direction: "LEFT"
    speed: 40
- assertVisible: "On the day, download your key, unlock the doors and complete the\
    \ damage report. It's time to start the engine."
- scrollUntilVisible:
    element: "Return"
    direction: "LEFT"
    speed: 30

Could pls tell me what am I doing wrong? The same code works for Down scroll without any issue.

<img width="348" alt="Screenshot 2023-04-27 at 15 49 47" src="https://user-images.githubusercontent.com/47413775/234882743-cdc252c1-b5de-4695-ac7b-b2a89c7c8591.png">

**Comment by Leland-Takamine** [comment]
@AlexanderEggers We've made some improvements to how scrolling works on iOS. Can you please try this again on the [latest maestro version](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli)?

**Comment by axelniklasson** [comment]
@AartiTew Could you please open another bug report if you are experiencing issues with scroll on Android? Thanks!

**Comment by axelniklasson** [comment]
Hi @AlexanderEggers, I'll go ahead and close this out for now. Please file a new bug report [here](https://github.com/mobile-dev-inc/maestro/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BMaestro+version%2C+e.g.+v1.2.3%5D) if you are still experiencing issues!
