### ISSUE TITLE
Support Windows without WSL2

### ISSUE THREAD

**Issue by lsaudon** [mobile-dev-inc/maestro#760]
Hello,

According to this issue #99, it is supported.
I found that it worked up to version 1.14.0
With 1.15.0, I have this `The syntax of the command is incorrect.`

Is the support completely out of date?

**Comment by Colorofbest** [comment]
> `The input line is too long. The syntax of the command is incorrect.`
Hello, yes I confirm I have the same error today (The input line is too long. The syntax of the command is incorrect. )
Windows cmd allow only 8191 characters :-/ (https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation)

To fix this, just open the bin/maestro.bat and replace all the CLASSPATH=[a lot of jar]
With
`set CLASSPATH=%APP_HOME%\lib\*`
To include all jar without specifying one by one.

Looks better.

**Comment by Colorofbest** [comment]
I did not found the maestro.bat file on this github project. Where is it ? ;-)

**Comment by Colorofbest** [comment]
It looks like it, but it only contains (in tag 1.21.3), this one must be for project build
`set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar`
and not the one with 10 000 characters^^

ps : I did not clone the project yet to search :)

**Comment by lsaudon** [comment]
It's ok for `maestro --version` but not for `maestro test flow.yaml` I have this error :
```sh
java.io.IOException: The process cannot access the file because another process has locked a portion of the file
        at java.base/java.io.FileInputStream.readBytes(Native Method)
        at java.base/java.io.FileInputStream.read(FileInputStream.java:293)
        at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:333)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:376)
        at java.base/sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:219)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:173)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:189)
        at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.base/java.io.BufferedReader.implReadLine(BufferedReader.java:371)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:348)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:437)
        at kotlin.io.LinesSequence$iterator$1.hasNext(ReadWrite.kt:79)
        at kotlin.io.TextStreamsKt.forEachLine(ReadWrite.kt:154)
        at kotlin.io.FilesKt__FileReadWriteKt.forEachLine(FileReadWrite.kt:190)
        at kotlin.io.FilesKt__FileReadWriteKt.readLines(FileReadWrite.kt:219)
        at kotlin.io.FilesKt__FileReadWriteKt.readLines$default(FileReadWrite.kt:217)
        at maestro.cli.db.KeyValueStore.getCurrentDB(KeyValueStore.kt:46)
        at maestro.cli.db.KeyValueStore.keys(KeyValueStore.kt:28)
        at maestro.cli.session.SessionStore.activeSessions(SessionStore.kt:55)
        at maestro.cli.session.SessionStore.hasActiveSessions(SessionStore.kt:68)
        at maestro.cli.session.MaestroSessionManager$newSession$session$1.invoke(MaestroSessionManager.kt:80)
        at maestro.cli.session.MaestroSessionManager$newSession$session$1.invoke(MaestroSessionManager.kt:77)
        at maestro.cli.db.KeyValueStore.withExclusiveLock(KeyValueStore.kt:37)
        at maestro.cli.session.SessionStore.withExclusiveLock(SessionStore.kt:74)
        at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:77)
        at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:51)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:115)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:41)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at maestro.cli.AppKt.main(App.kt:122)
```

**Comment by lsaudon** [comment]
on 1.15.0:
```sh
 ║
 ║  > Flow
 ║
 ║    ?  Launch app "com.android.vending"
 ║
java.io.IOException: The process cannot access the file because another process has locked a portion of the file
        at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at java.base/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:54)
        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:245)
        at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:223)
        at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
        at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107)
        at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101)
        at java.base/java.io.InputStream.transferTo(InputStream.java:704)
        at java.base/java.nio.file.Files.copy(Files.java:3195)
        at maestro.utils.FileUtils.zipDir(FileUtils.kt:33)
        at maestro.cli.debuglog.DebugLogStore.finalizeRun(DebugLogStore.kt:84)
        at maestro.cli.AppKt.main(App.kt:107)
```

**Comment by lsaudon** [comment]
I don't know much about Kotlin and Java.
Wouldn't the problem be that `hasActiveSessions` locks `keyValueStore` and `activeSessions` which is called by `hasActiveSessions` locks it too?

https://github.com/mobile-dev-inc/maestro/blob/7376e027a8895bd6151888955c49829d9b6154af/maestro-cli/src/main/java/maestro/cli/session/SessionStore.kt#L52-L71

**Comment by FunnyDevs** [comment]
same problem...

**Comment by JakeAi** [comment]
I also have this problem

**Comment by j2esu** [comment]
Same, did anybody find a workaround?

**Comment by Leland-Takamine** [comment]
Today, WSL is the only supported workflow for Windows. We've made some improvements to the documentation so make sure to check that out here: https://maestro.mobile.dev/getting-started/installing-maestro/windows

We may consider non-WSL workflows in the future but closing this out for now.

**Comment by trekvartista** [comment]
@lsaudon The same error - java.io.IOException: The process cannot access the file because another process has locked a portion of the file. 

How did you solve this issue?

**Comment by vynguyenbao28** [comment]
I also encountered this error,
 whether anyone has a solution yet? Because now I installed Maestro through the WSL environment that was faulty I could not recognize Emulator

**Comment by Colorofbest** [comment]
Hello @vynguyenbao28
Sorry, no solution for me... Because of this error I abandoned Maestro which seemed great to me :(

(Linked to #99)
