### ISSUE TITLE
Crash on 1.24.0 related to "Define variables" command and system env variables

### ISSUE THREAD

**Issue by erykrutkowski** [mobile-dev-inc/maestro#879]
In version 1.24.0 Maestro command: **Define variables**, causes crash whenever in system env we have a variable that  contains `${#}` (I believe sequence matters so `#` have to be inside `${}` , I assume only then it is interpreted like regular JS). 
In general it is not a huge problem as we could simply avoid doing such things, but it is something to remember(maybe mention in docs) and possible fix in future release. Especially that nowadays CI/CD services tends to keep whole script in global/system variable and i.e. for bash script such combination might be used to print array length. Of course again, on such CI/CD you could just override that one env variable, as it’s usually don’t needed but first you have to find it, which is not easy.
Maybe some option/parameter  to enable/disable obtaining all system env variables, or maybe some other option/parameter which accepts file/list that will limit this ” system env copying” to take only what’s on the list/in the file. That might be helpful.

It doesn’t happen on previous versions.

Crashlog:
```org.mozilla.javascript.EvaluatorException: illegal character: # (inline-script#1)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:79)
	at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:66)
	at org.mozilla.javascript.Parser.addError(Parser.java:257)
	at org.mozilla.javascript.Parser.addError(Parser.java:235)
	at org.mozilla.javascript.Parser.addError(Parser.java:241)
	at org.mozilla.javascript.TokenStream.getToken(TokenStream.java:1271)
	at org.mozilla.javascript.Parser.peekToken(Parser.java:396)
	at org.mozilla.javascript.Parser.parse(Parser.java:611)
	at org.mozilla.javascript.Parser.parse(Parser.java:562)
	at org.mozilla.javascript.Context.parse(Context.java:2470)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2401)
	at org.mozilla.javascript.Context.compileString(Context.java:1369)
	at org.mozilla.javascript.Context.compileString(Context.java:1357)
	at org.mozilla.javascript.Context.evaluateString(Context.java:1135)
	at maestro.js.JsEngine.evaluateScript(JsEngine.kt:86)
	at maestro.js.JsEngine.evaluateScript$default(JsEngine.kt:58)
	at maestro.orchestra.util.Env$evaluateScripts$result$1.invoke(Env.kt:15)
	at maestro.orchestra.util.Env$evaluateScripts$result$1.invoke(Env.kt:11)
	at kotlin.text.Regex.replace(Regex.kt:195)
	at maestro.orchestra.util.Env.evaluateScripts(Env.kt:11)
	at maestro.orchestra.DefineVariablesCommand.evaluateScripts(Commands.kt:635)
	at maestro.orchestra.DefineVariablesCommand.evaluateScripts(Commands.kt:624)
	at maestro.orchestra.MaestroCommand.evaluateScripts(MaestroCommand.kt:135)
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:133)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:92)
	at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:120)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:36)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:32)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:123)
	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:32)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:163)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:124)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:98)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:53)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:124)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:42)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:125)```

**Comment by axelniklasson** [comment]
Hi @erykrutkowski, we've made some changes regarding to env injection from the shell so please try the latest version and open a new bug report if this is still an issue. Thanks!
