### ISSUE TITLE
onTap causes Crash (Android, Mac, 1.25.0)

### ISSUE THREAD

**Issue by iapetus98** [mobile-dev-inc/maestro#893]
Test runs until the first onTap, at which point it crashes with the following (unhelpful) stack trace:

`io.grpc.StatusRuntimeException: UNKNOWN
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
        at maestro_android.MaestroDriverGrpc$MaestroDriverBlockingStub.tap(MaestroDriverGrpc.java:496)
        at maestro.drivers.AndroidDriver.tap(AndroidDriver.kt:217)
        at maestro.Maestro.hierarchyBasedTap-9V-jo0g(Maestro.kt:298)
        at maestro.Maestro.performTap-9V-jo0g(Maestro.kt:253)
        at maestro.Maestro.tap-egYXmKw(Maestro.kt:187)
        at maestro.orchestra.Orchestra.tapOnElement(Orchestra.kt:599)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:163)
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:141)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:92)
	at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:120)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:36)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:32)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:123)
	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:32)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:163)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:124)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:96)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:54)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:124)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:42)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:125)`

**Comment by iapetus98** [comment]
[2023-03-14_165144.zip](https://github.com/mobile-dev-inc/maestro/files/10971544/2023-03-14_165144.zip)
[2023-03-14_164915.zip](https://github.com/mobile-dev-inc/maestro/files/10971546/2023-03-14_164915.zip)

**Comment by iapetus98** [comment]
`# flow.yaml

appId: com.student
---
- launchApp
- assertVisible: "Summer School: English"
- tapOn: "Summer School: English"`

**Comment by olttwa** [comment]
+1 to this. Even we faced this issue and downgrading to `1.23.0` worked. 

FYI @dmitry-zaitsev

**Comment by S-ipk** [comment]
+1 to this as well as I am currently facing this issue. Is there any update @dmitry-zaitsev?

**Comment by dhruvgoyal762** [comment]
I am also facing this issue. Is there any update @dmitry-zaitsev?

**Comment by ArthurSav** [comment]
We have made a lot of improvements and fixes since, can you upgrade to the latest version of Maestro and try again?

**Comment by axelniklasson** [comment]
Related issue: #1026

**Comment by saihemanth121** [comment]
Facing this issue consistently in one of my flows. Using latest version of maestro: 1.31.0. cc: @axelniklasson

**Comment by Fishbowler** [comment]
Anyone still hitting this on v1.39.x?

**Comment by Fishbowler** [comment]
No instances in 8 months, I'm happy to call this done :)

Thanks everyone!
