### ISSUE TITLE
runScript throws missing ; before statement

### ISSUE THREAD

**Issue by stefanosheaDeputy** [mobile-dev-inc/maestro#896]
I am trying to run a js script to get a date in a particular format.
```yaml
// test.yaml
appId: com.myApp.prod
---
- runScript: getLastMonthDate.js
```

```javascript
// getLastMonthDate.js
// Create a new Date object for today's date
let date = new Date();

// Get the month and year for last month
let month = date.getMonth() - 1;
let year = date.getFullYear();

// If the current month is January, adjust the year accordingly
if (month === -1) {
  month = 11; // December
  year--;
}

// Create a new Date object for the 12th of last month
let lastMonthDate = new Date(year, month, 12);

// Format the date string as "Mon, Feb 15"
output.result = lastMonthDate.toLocaleDateString("en-US", { day: "2-digit", month: "short", weekday: "short" });

```

Result:
```
org.mozilla.javascript.EvaluatorException: missing ; before statement (getLastMonthDate.js#2)
        at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:79)
        at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:66)
        at org.mozilla.javascript.Parser.addError(Parser.java:257)
        at org.mozilla.javascript.Parser.reportError(Parser.java:336)
        at org.mozilla.javascript.Parser.reportError(Parser.java:327)
        at org.mozilla.javascript.Parser.reportError(Parser.java:320)
        at org.mozilla.javascript.Parser.autoInsertSemicolon(Parser.java:1279)
        at org.mozilla.javascript.Parser.statementHelper(Parser.java:1254)
        at org.mozilla.javascript.Parser.statement(Parser.java:1104)
        at org.mozilla.javascript.Parser.parse(Parser.java:632)
        at org.mozilla.javascript.Parser.parse(Parser.java:562)
        at org.mozilla.javascript.Context.parse(Context.java:2470)
        at org.mozilla.javascript.Context.compileImpl(Context.java:2401)
        at org.mozilla.javascript.Context.compileString(Context.java:1369)
        at org.mozilla.javascript.Context.compileString(Context.java:1357)
        at org.mozilla.javascript.Context.evaluateString(Context.java:1135)
        at maestro.js.JsEngine.evaluateScript(JsEngine.kt:81)
        at maestro.orchestra.Orchestra.runScriptCommand(Orchestra.kt:236)
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:194)
        at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:141)
        at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:92)
        at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:120)
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:36)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:32)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:123)
	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:32)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:163)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:124)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:96)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:54)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:124)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:42)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:125)
```

**Expected**
I expect the script to run and give me the date string in the format I want so I can use it in my tests

Maestro version is `1.25.0`

Logs:
[2023-03-15_153802.zip](https://github.com/mobile-dev-inc/maestro/files/10976102/2023-03-15_153802.zip)
[2023-03-15_154512.zip](https://github.com/mobile-dev-inc/maestro/files/10976103/2023-03-15_154512.zip)
[xctest_runner_2023-03-15_153804.log](https://github.com/mobile-dev-inc/maestro/files/10976104/xctest_runner_2023-03-15_153804.log)

**Comment by fantpmas** [comment]
Had the same issue, solved it by using `var` instead of `let`.
