### ISSUE TITLE
Minimum Android OS version requirement?

### ISSUE THREAD

**Issue by vibin** [mobile-dev-inc/maestro#935]
This is an important piece of information - Is this documented somewhere? 

I tried Maestro Studio on Android 5 (SDK 21) and it failed with the below trace:

```

java.io.IOException: pm list packages --user 0 dev.mobile.maestro.test
	at maestro.drivers.AndroidDriver.shell(AndroidDriver.kt:759)
	at maestro.drivers.AndroidDriver.isPackageInstalled(AndroidDriver.kt:747)
	at maestro.drivers.AndroidDriver.uninstallMaestroApks(AndroidDriver.kt:722)
	at maestro.drivers.AndroidDriver.open(AndroidDriver.kt:91)
	at maestro.Maestro$Companion.android(Maestro.kt:543)
	at maestro.Maestro$Companion.android$default(Maestro.kt:536)
	at maestro.cli.session.MaestroSessionManager.createMaestro(MaestroSessionManager.kt:149)
	at maestro.cli.session.MaestroSessionManager.access$createMaestro(MaestroSessionManager.kt:46)
	at maestro.cli.session.MaestroSessionManager$newSession$session$1.invoke(MaestroSessionManager.kt:78)
	at maestro.cli.session.MaestroSessionManager$newSession$session$1.invoke(MaestroSessionManager.kt:77)
	at maestro.cli.db.KeyValueStore.withExclusiveLock(KeyValueStore.kt:37)
	at maestro.cli.session.SessionStore.withExclusiveLock(SessionStore.kt:74)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:77)
	at maestro.cli.command.StudioCommand.call(StudioCommand.kt:36)
	at maestro.cli.command.StudioCommand.call(StudioCommand.kt:18)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:125)
Caused by: java.io.IOException: Command failed (shell,v2,raw:pm list packages --user 0 dev.mobile.maestro.test): closed
	at dadb.adbserver.AdbServer.send$dadb(AdbServer.kt:99)
	at dadb.adbserver.AdbServerDadb.open(AdbServer.kt:138)
	at dadb.Dadb$DefaultImpls.openShell(Dadb.kt:43)
	at dadb.adbserver.AdbServerDadb.openShell(AdbServer.kt:118)
	at dadb.Dadb$DefaultImpls.shell(Dadb.kt:36)
	at dadb.adbserver.AdbServerDadb.shell(AdbServer.kt:118)
	at maestro.drivers.AndroidDriver.shell(AndroidDriver.kt:757)
	... 23 more
```

**Comment by igorsmotto** [comment]
After a quick test, apparently, the minimum version that Maestro Studio works on is Android 8 (SDK 26)

**Comment by vibin** [comment]
@igorsmotto thanks for the information. Is this same for the maestro command/runner itself?

**Comment by Leland-Takamine** [comment]
> @igorsmotto thanks for the information. Is this same for the maestro command/runner itself?

Yes @vibin that's correct.
