### ISSUE TITLE
Maestro in GitHub Action times out "Maestro Android driver did not start up in time"

### ISSUE THREAD

**Issue by latorante** [mobile-dev-inc/Maestro#965]
Hey hey,

I've got a GitHub Action, which runs on `macos-12` and starts up an emulator to run tests on. The Action fails to start and ends up with this error:

```
java.util.concurrent.TimeoutException: Maestro Android driver did not start up in time
	at maestro.drivers.AndroidDriver.awaitLaunch(AndroidDriver.kt:138)
	at maestro.drivers.AndroidDriver.open(AndroidDriver.kt:102)
	at maestro.Maestro$Companion.android(Maestro.kt:543)
	at maestro.Maestro$Companion.android$default(Maestro.kt:536)
	at maestro.cli.session.MaestroSessionManager.createMaestro(MaestroSessionManager.kt:149)
	at maestro.cli.session.MaestroSessionManager.access$createMaestro(MaestroSessionManager.kt:46)
	at maestro.cli.session.MaestroSessionManager$newSession$session$1.invoke(MaestroSessionManager.kt:78)
	at maestro.cli.session.MaestroSessionManager$newSession$session$1.invoke(MaestroSessionManager.kt:77)
	at maestro.cli.db.KeyValueStore.withExclusiveLock(KeyValueStore.kt:37)
	at maestro.cli.session.SessionStore.withExclusiveLock(SessionStore.kt:74)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:77)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:54)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:124)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:42)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:125)
```

I have noticed others already mentioned this, and there was a PR updating the timeout to 15 seconds (here: https://github.com/mobile-dev-inc/maestro/blob/main/maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt#L781) but is there a way to pass this down as a ENV Variable possibly? 

That way I could see if the issue is the wait time, or perhaps something else?

This is how the action looks like - Java and emulator runner.

```
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Cold boot device, test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        target: google_apis_playstore
        arch: x86_64
        profile: pixel_4
        avd-name: AVD
        force-avd-creation: false
        emulator-options: -no-snapshot-load -gpu swiftshader_indirect -no-window -noaudio -no-boot-anim -camera-back none
        script: |
          maestro test ./maestro/flows/Login.yaml;
```

**Comment by felipevolpone** [comment]
@latorante Right now there isn't a way to customize the wait time, but if you want to contribute to Maestro, please feel free to open a PR and drive the solution.

**Comment by theinterlocker7** [comment]
Thanks @felipevolpone and @retyui . I will consider those options!

**Comment by ashishb** [comment]
@theinterlocker7 did it work?

**Comment by Ademsk1** [comment]
If you have access to large github runners, try linux 4core and install KVM. 
See [here](https://github.com/ReactiveCircus/android-emulator-runner/issues/46)

**Comment by bartekpacia** [comment]
likely a duplicate of #1585

**Comment by Fishbowler** [comment]
The Maestro Driver timeout was made configurable some time back.

https://maestro.mobile.dev/advanced/configuring-maestro-driver-timeout
