### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by humazed** [mobile-dev-inc/maestro#99]
I can only see getting started steps for mac and Linux.

Does maestro currently support windows? 
If not do you have a timeline for when we could expect to have windows support?

**Comment by dmitry-zaitsev** [comment]
Maestro does, in theory, support Windows as it purely a JVM application. However, we do not have means to test it at this very moment so any input would be much appreciated!

**Comment by Colorofbest** [comment]
Hello,
I'm on Windows and I can use maestro.
- Just download the latest release : https://github.com/mobile-dev-inc/maestro/releases
- Unzip it;
- with PowerShell : 
  - cd to this directory
  - `maestro test you_flow.yaml`

### Bonus steps to add maestro command alias in PowerShell
The maestro command will be available to each PowerShell session. 
- `Test-Path $Profile`
  - if False, create profile file :
    `New-Item -Path $Profile -ItemType file -Force`
- Add in this file the alias so that it is persistent
- `New-Alias maestro C:/full-path/maestro-1.4.0/bin/maestro.bat`

### If you have a java version error
- download a recent java version (Java 18 for example) : https://www.oracle.com/java/technologies/javase/jdk18-archive-downloads.html (Windows x64 Compressed Archive - so it's system independent)
- unzip it where you want
- with PowerShell (or in your previous profile file to make it persistent)
```
[System.Environment]::SetEnvironmentVariable("JAVA_HOME", "D:\mypath\jdk-18.0.2.1")
[System.Environment]::SetEnvironmentVariable("Path", "$($env:JAVA_HOME)\bin;" + [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::Machine))
```

Enjoy !

To the Maestro team :
Thank you for this promising tool !

**Comment by dmitry-zaitsev** [comment]
Thank you @Colorofbest! I have included a part of your guide into our docs 👍

**Comment by johnmc-tc** [comment]
The docs on the website do not cover the alias part and as such, do not work. 

Without setting the alias up on the machine, you need to do the following command:

.\'maestro.bat' test ...

I think the docs should be updated to reflect this.

**Comment by lsaudon** [comment]
@Colorofbest Hey, I have this error on Windows `The input line is too long. The syntax of the command is incorrect.` when I run `.\maestro.bat --version`.
Don't you have this error now?

**Comment by Colorofbest** [comment]
> `The input line is too long. The syntax of the command is incorrect.`
Hello, yes I confirm I have the same error today (The input line is too long. The syntax of the command is incorrect. )

Windows cmd allow only 8191 characters :-/ (https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation)

To fix this, just open the bin/maestro.bat and replace all the CLASSPATH=[a lot of jar]
With
`set CLASSPATH=%APP_HOME%\lib\*`
To include all jar without specifying one by one.

Looks better.

**Comment by vynguyenbao28** [comment]
I got the following error
java.lang.IllegalArgumentException: Illegal base64 character d
        at java.util.Base64$Decoder.decode0(Unknown Source)
        at java.util.Base64$Decoder.decode(Unknown Source)
        at java.util.Base64$Decoder.decode(Unknown Source)
        at dadb.PKCS8.parse(PKCS8.kt:32)
        at dadb.AdbKeyPair$Companion.read(AdbKeyPair.kt:86)
        at dadb.AdbKeyPair$Companion.readDefault(AdbKeyPair.kt:80)
        at dadb.Dadb$Companion.list$default(Dadb.kt:243)
        at maestro.cli.device.DeviceService.listAndroidDevices(DeviceService.kt:140)
        at maestro.cli.device.DeviceService.listDevices(DeviceService.kt:124)
        at maestro.cli.device.DeviceService.listConnectedDevices(DeviceService.kt:114)
        at maestro.cli.device.PickDeviceInteractor.pickDeviceInternal(PickDeviceInteractor.kt:40)
        at maestro.cli.device.PickDeviceInteractor.pickDevice(PickDeviceInteractor.kt:17)
        at maestro.cli.session.MaestroSessionManager.selectDevice(MaestroSessionManager.kt:116)
        at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:65)
        at maestro.cli.command.StudioCommand.call(StudioCommand.kt:51)
        at maestro.cli.command.StudioCommand.call(StudioCommand.kt:19)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at maestro.cli.AppKt.main(App.kt:117)
